### ISSUE TITLE
Required parameter "vendor" not documented

### ISSUE THREAD

**Issue by peterbecker** [javafx-maven-plugin/javafx-maven-plugin#12]
Trying to run the plugin I ran into the following error:

    [ERROR] Failed to execute goal com.zenjava:javafx-maven-plugin:1.3:build-jar (build-jar) on project epik-protocol-tools: The parameters 'vendor' for goal com.zenjava:javafx-maven-plugin:1.3:build-jar are missing or invalid -> [Help 1]

By looking at the source code I figured out that I should set /project/organization/name in the POM, but that wasn't obvious and I didn't see it documented anywhere.

**Comment by FibreFoX** [comment]
It's documented (not in the best place): http://zenjava.com/javafx/maven/basic-config.html

After creation of a new website, this will be documented in a better way.
