### ISSUE TITLE
Broken links on http://zenjava.com/javafx/maven/

### ISSUE THREAD

**Issue by malafeev** [javafx-maven-plugin/javafx-maven-plugin#123]
There are several broken links on http://zenjava.com/javafx/maven/
- http://zenjava.com/javafx/maven/basic-config.html
- http://zenjava.com/javafx/maven/native-bundle.html
- http://zenjava.com/javafx/maven/jar-bundle.html

etc

They always open the same page without requested info.

**Comment by FibreFoX** [comment]
Doublicate of #121 

Please be patient, we work on it. Meanwhile you can take a look at web-archives:
https://web.archive.org/web/20141010065531/http://zenjava.com/javafx/maven/basic-config.html

I will leave this open to have new users finding this more easily.

**Comment by damnhandy** [comment]
Would it be easier to move those docs in a GotHub wiki under the gh-pages branch? At least everything would be under one roof and it'd be much easier to accept contributions :)

**Comment by FibreFoX** [comment]
As I said some time ago, we are working on this.

**Comment by kishaningithub** [comment]
When can we expect this documentation?

**Comment by FibreFoX** [comment]
As this is a spare-time project, where normal-life and business-life is ruling over the time left for this project, please be patient. As mentioned on the readme-file (which was updated some days before), you can use the archived site until its available from zenjava again.

https://web.archive.org/web/20141009064442/http://zenjava.com/javafx/maven/

**Comment by damnhandy** [comment]
Since the docs are generated using the Maven Site Plugin, have you considered using the [Github Pages](https://pages.github.com/) feature? It's pretty easy to get up an running and it ends up being nicely integrated with your build and deployment process via Maven. The only downside is that the domain changes, but that is a minor issue for those of us just looking for the documentation. I'd be happy submit a PR for this if you'd be interested in going that route. 

I'm using Github Pages for one of my projects here:

http://damnhandy.github.io/Handy-URI-Templates/

**Comment by FibreFoX** [comment]
Just short update on this:
* yes, we have considered github-pages feature
* javafx-maven-plugin.github.io will become a new "configuration-generator" powered by github-pages
* zenjava will stay full documentation about the plugin itself, but not by depending on javadoc-comments and will reside on non-github-pages

**Comment by onstottj** [comment]
It seems like one of the best options right now is to look at the source, under src/site/apt.  The documentation is pretty readable there, and is for the latest version of the plugin.

**Comment by FibreFoX** [comment]
Just to mention, the beta-version of the new github-provided website is available:
http://javafx-maven-plugin.github.io/

**Comment by RobzInadE** [comment]
Hey guys sorry to bump an old issue. I was wondering where the documentation on how to sign your application went? I recall it being in the old version. I thought it might be handy.

**Comment by FibreFoX** [comment]
It seems that someone caught that domain ... I'm currently not sure, why the domain was moved to another person ... will have to investigate ...

**Comment by cshubhamrao** [comment]
Any update?

**Comment by og0815** [comment]
It seams, that the web.archive link has become unusable. So no full documentation can be found online right now.

**Comment by PaulWoods4422** [comment]
As og0815 said, the we archive link is dead - so there is no documentation other than the source itself. Is this project dead?
