### ISSUE TITLE
No way to set fx:platform basedir

### ISSUE THREAD

**Issue by hinerm** [javafx-maven-plugin/javafx-maven-plugin#127]
JavaFX has a [fx:platform](https://blogs.oracle.com/talkingjavadeployment/entry/packaging_improvements_in_jdk_7#2) element, where you can set `basedir=""` to allow self-contained apps to launch with system java.

Exposing this in the `javafx-maven-plugin` configuration would be very useful.

**Comment by maxd** [comment]
Just pass it through `bundleArguments` parameter:

    <bundleArguments>
      ...
      <runtime/>
    </bundleArguments>

**Comment by hinerm** [comment]
Thanks, this worked for me. I don't see  `bundleArguments` in the archived plugin documentation.. hope it gets sorted out when your site comes back up!

**Comment by AugustKarlstedt** [comment]
Could you post the exact markup that you used? This doesn't seem to be working for me.

**Comment by hinerm** [comment]
@AugustKarlstedt sure; you can see how we were using the configuration [in this pom](https://github.com/imagej/imagej/blob/d9537944a8aced0e2fde5a3ce4b661747f97fae9/pom.xml#L161-L186). Haven't tried it recently though.

**Comment by AugustKarlstedt** [comment]
@hinerm: Thanks! It doesn't seem like you're setting the fx:platform basedir, but instead just setting runtime="" (which doesn't include JRE in the bundle).

The issue I'm having is that running the built EXE still looks for the runtime to be included and throws an error.

**Comment by hinerm** [comment]
@AugustKarlstedt Our use case was that we wanted the ability to build a [self-contained](http://docs.oracle.com/javase/8/docs/technotes/guides/deploy/deploy_overview.html) version of our application *without* bundling a JRE - allowing a user's system JRE installation to be picked up instead.

You may want to [verify that your JRE installation](https://docs.oracle.com/goldengate/1212/gg-winux/GDRAD/java.htm#BGBFHBEA) - e.g. if you open a command prompt can you use Java? If not, then a JavaFX app built with `runtime=""` will not be able to start up.

Note that if you're running 32-bit windows, it sounds like you also need to [add `JAVA_HOME` to your `PATH`](http://www.oracle.com/technetwork/java/javase/install-windows-64-142952.html).

If you are able to verify your Java installation and are still having problems starting your app, I recommend opening a new issue and providing more information about your particular setup/pom configuration, and what you're trying to accomplish, as you may be coming up against a bug or other limitation.

**Comment by AugustKarlstedt** [comment]
@hinerm: That's what I was attempting to do. I have verified that my JRE installation is correct and working.

Thanks for your help, it seems like I should open a new issue.
