### ISSUE TITLE
Image displayed in the OSx PKG Installer

### ISSUE THREAD

**Issue by sselvia** [javafx-maven-plugin/javafx-maven-plugin#133]
What image file name is used for the PKG image in the installer?  I would like to not have the native Java image.

![pkgimage](https://cloud.githubusercontent.com/assets/3527730/8767824/3094da46-2e37-11e5-8e9e-40ed5e631a54.png)

**Comment by FibreFoX** [comment]
The javafx-maven-plugin used underlying packager provided by the OS, please check oracle-documentation for this. I assume it's called "background_pkg.png", have a look here: https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/java/com/oracle/tools/packager/mac/MacPkgBundler.java#L65

**Comment by sselvia** [comment]
I turned on verbose and dived into the /var folder structure last night. I did not have a chance to update the issue. The file name needs to be the application name plus -background.png

Thanks,

Scott
