### ISSUE TITLE
Is there any support for multi module builds?

### ISSUE THREAD

**Issue by purringpigeon** [javafx-maven-plugin/javafx-maven-plugin#137]
I have successfully moved to your latest build with my simple, single project pom.xml.  Works great.

I am attempting now to apply these principles to a multi module project for code separation, etc.  I am running into issues packaging with the plug in.  Here is my pom.xml from the master project:

    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.mycompany</groupId>
	<artifactId>myapp-master-module</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>My App Master Module</name>
	<description>Master Module for the Application </description>

	<organization>
		<name>My Company</name>
	</organization>

	<modules>
		<module>javafx-http-framework</module>
		<module>javafx-workspace-framework</module>
		<module>javafx-mstech-viewer</module>
	</modules>

	<repositories>
		<repository>
			<id>Private-Artifact-Repo</id>
			<url>file://G:/IT/Private-Artifact-Repo</url>
		</repository>
	</repositories>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.3</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>2.6</version>
				<configuration>
					<archive>
						<manifestEntries>
							<Main-Class>com.mycompany.myapp</Main-Class>
							<implementation-version>1.0</implementation-version>
						</manifestEntries>
						<manifest>
							<addClasspath>true</addClasspath>
						</manifest>
					</archive>
				</configuration>
			</plugin>

			<plugin>
				
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.3</version>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>package</phase>
						<configuration>
							<overWriteReleases>false</overWriteReleases>
							<overWriteSnapshots>false</overWriteSnapshots>
							<overWriteIfNewer>true</overWriteIfNewer>
						</configuration>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			
			<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<version>2.6</version>
				<executions>
					<execution>
						<id>copy-resources-1</id>
						<phase>validate</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${basedir}/target/additionalResources/properties</outputDirectory>
							<resources>
								<resource>
									<directory>properties</directory>
									<filtering>true</filtering>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>com.zenjava</groupId>
				<artifactId>javafx-maven-plugin</artifactId>
				<version>8.1.3</version>
				<configuration>
					<mainClass>com.mycompany.myapp</mainClass>
					<verbose>true</verbose>
					<bundler>EXE</bundler>
					<additionalAppResources>${project.build.directory}/additionalResources</additionalAppResources>
				</configuration>
				<executions>
					<execution>
						<id>create-jfxjar</id>
						<phase>package</phase>
						<goals>
							<goal>build-jar</goal>
						</goals>
					</execution>
					<execution>
						<id>create-native</id>
						<phase>package</phase>
						<goals>
							<goal>build-native</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>org.controlsfx</groupId>
			<artifactId>controlsfx</artifactId>
			<version>8.40.9</version>
		</dependency>
		<dependency>
			<groupId>commons-logging</groupId>
			<artifactId>commons-logging</artifactId>
			<version>1.2</version>
		</dependency>
	</dependencies>
</project>

This is throwing the following error:
[ERROR] Failed to execute goal com.zenjava:javafx-maven-plugin:8.1.3:build-jar (create-jfxjar) on project myapp-master-module: Unable to build JFX JAR for application: Error: Failed to create jar file myapp-master-module-0.0.1-SNAPSHOT-jfx.jar: Input folder does not exist [C:\workspace\myapp\myapp-master-module\target\classes] -> [Help 1]

If I remove the execution from the plug in, it will run without issue, but I get no exe or other output in the master project.

I checked the cached documentation, and didn't see anything there on this.

Thanks

**Comment by FibreFoX** [comment]
You are using this plugin wrong, please look at your packaging: it's POM. Only JAR-projects can be used here. Would be the same as using javafxpackager via ANT, you have to be at the project you are building your jar.

You have to specify the plugin at pom.xml from the GUI-application.

**Comment by purringpigeon** [comment]
Thank you - appreciate the pointer.  Do you have any documentation you could point me to on how to accomplish this?  I have moved it as you state, but seem to have other issues with it.  Like I mentioned before, I am pretty new to maven, and am having a bit of a learning curve getting this all set up.  I looked through the documentation but couldn't see how to make it work, like the standard ant build with multiple fx projects worked.  Thank you.  I am pretty close, but getting an exe that doesn't run after installed, but that runs from eclipse.

**Comment by FibreFoX** [comment]
When building you could move the plugin into the module ```<module>javafx-mstech-viewer</module>```, all other dependencies are build before, so when you are using maven-lifecycle via two executions "build-jar", "build-native" you should archive your wanted result.

**Comment by purringpigeon** [comment]
I had an error in my POM set up, which I have corrected (I think) - there are three actually 4 modules, and the plug in is on the 4th which has the dependency on the other three (i.e. the one with the JavaFX Application class).

However, the installer generates the following cfg file in this case:

app.runtime=$APPDIR\runtime
app.mainjar=lib\javafx-workspace-framework-0.0.1-SNAPSHOT.jar
app.version=1.0
app.id=org.idahosif.application
app.preferences.id=org/idahosif/application
app.mainclass=org/idahosif/application/PowerSuiteFX
app.classpath=jackson-databind-2.6.0.jar jackson-annotations-2.6.0.jar jackson-core-2.6.0.jar controlsfx-8.40.9.jar openjfx-dialogs-1.0.3.jar commons-logging-1.2.jar

however the main class lives in the PowerSuiteFX-jfx.jar at the same level as the jar cfg file, and it appears the other three snapshot projects aren't included in the class path.  Probably something pretty stupid that I am not seeing.

**Comment by purringpigeon** [comment]
I cleaned it up a little more, and got it working.  Thanks for the help!
