### ISSUE TITLE
Invalid system link to ant-javafx.jar in the pom.xml

### ISSUE THREAD

**Issue by Lonzak** [javafx-maven-plugin/javafx-maven-plugin#143]
I got a dependecy problem using the current (8.1.3) version of the plugin. I use it from eclipse which tells me it can not resolve one of its depencies.
The JAVA_HOME path is definied to point to the JDK directory which is e.g.
C:\Program Files\Java\jdk1.8.0_45
Compare: http://docs.oracle.com/cd/E19182-01/820-7851/inst_cli_jdk_javahome_t/index.html

The system path defined in the pom.xml contains **two dots** which results in the following directory:
C:\Program Files\Java\lib\ant-javafx.jar which of course does not exist.

    <dependency>
     <groupId>javafx-packager</groupId>
     <artifactId>javafx-packager</artifactId>
     <version>1.8.0_20</version>
     <scope>system</scope>
     <systemPath>${java.home}/../lib/ant-javafx.jar</systemPath>
    </dependency>

Or am I missing something here?

**Comment by FibreFoX** [comment]
Yes, you are missing something, because `${java.home}` is not JAVA_HOME, it's a system-property, see here: https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html

Maybe it's just a fluke within eclipse?

**Comment by Lonzak** [comment]
It may be a system property but it is defined like that: "Installation directory for Java Runtime Environment (JRE)" HOWEVER the result is the same since this system property points to e.g.  C:\Program Files\Java\jre1.8.0_45
So also in this case the two dots with your path doesn't make sense:
${java.home}/../lib/ant-javafx.jar
would result into
C:\Program Files\Java\lib\ant-javafx.jar and not C:\Program Files\Java\jre1.8.0_45\lib\ant-javafx.jar

But there is an explanation:
The maven ant plugin (which you probably use internally) sets the java_home to java_home\bin and thus you need to add your two dots...
http://stackoverflow.com/questions/2022622/java-home-gets-mangled-by-maven

**Comment by FibreFoX** [comment]
I now do see your point, I will check why this works ;)

**Comment by FibreFoX** [comment]
When having JAVA_HOME point to the JDK, maven outputs me this:
```
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 17:22:22+0200)
Maven home: C:\develop\tools\maven\apache-maven-3.1.1\bin\..
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: c:\Program Files\Java\jdk1.8.0_45\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "dos"
```

The interesting part is this:
`Java home: c:\Program Files\Java\jdk1.8.0_45\jre`
It point's to the JRE inside the JDK, and this is what I want and that I get inside that maven-plugin. 

I think Eclipse is selecting the wrong JRE for this, because we need the JDK one, not normal JRE:
http://stackoverflow.com/questions/23975000/maven-adds-jre-instead-of-jdk-to-build-path-in-eclipse

**Comment by FibreFoX** [comment]
Just leaving this here for documentation purpose:
[Stackoverflow: Java_home in Maven](http://stackoverflow.com/questions/15279586/java-home-in-maven)
[Apache issue: Java home output in mvn -v is misleading](https://issues.apache.org/jira/browse/MNG-5756)
