### ISSUE TITLE
Missing plugin for jfx:web and jfx:generate-key-store goals

### ISSUE THREAD

**Issue by txtdis** [javafx-maven-plugin/javafx-maven-plugin#148]
Error dump when either goals are executed. In eclipse, missing prefix is 'javafx' while on the command prompt, it's 'jfx'

"...No plugin found for prefix 'javafx' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\User\.m2\repository), central (https://repo.maven.apache.org/maven2)]..."

**Comment by FibreFoX** [comment]
Could you provide more details? I assume these are warnings while compiling javafx-maven-plugin, am I right? If so, this is no bug, its intended by the maven-plugin-plugin, there is nothing wrong about it.

Calling `mvn jfx:generate-key-store` only works when having the plugin setup inside your pom.xml

**Comment by FibreFoX** [comment]
This is a problem with eclipse, the prefix is "jfx", not "javafx" (maybe you are using some old version, this was "javafx" in some dated release, but was reverted very fast).
