### ISSUE TITLE
Bundler Arguments not setting OSx Info.plist Settings

### ISSUE THREAD

**Issue by sselvia** [javafx-maven-plugin/javafx-maven-plugin#152]
I set these tags in the maven POM for my build, even though these items are set they are not making their way into the generated Info.plist file generated by the JavaFX Packager.

                    <bundleArguments>
                        <LSApplicationCategoryType>public.app-category.business</LSApplicationCategoryType>
                        <CFBundleShortVersionString>2.0.1</CFBundleShortVersionString>
                    </bundleArguments>

Info.plist generated settings:

  <key>CFBundleShortVersionString</key>
  <string>2.0.0</string>
  <key>LSApplicationCategoryType</key>
  <string>Unknown</string>

**Comment by FibreFoX** [comment]
Have you looked if they are picked up by the bundler? We only pass these parameters to the packager, we don't manipulate any generated file.

**Comment by FibreFoX** [comment]
https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html
```
The resulting package on OS X is an "application bundle".

Several configuration parameters are placed in the Info.plist file in the application bundle and must conform to the following rules:

    Application ID (or main class name if ID is not specified) is used as CFBundleIdentifier.

    Application version is used as CFBundleShortVersionString.
```

**Comment by sselvia** [comment]
I have verified that those arguments are not reflected in the plist. I posted the issue to the openjfx mailing list. 

Does the javafx packager command line show up in the verbose output?  I don't recall seeing it, that would show what is going to the packager

**Comment by FibreFoX** [comment]
Could you post the corresponding JIRA-ticket here? Would be good for others to find it here too. :smile:

**Comment by FibreFoX** [comment]
Hi @sselvia , do you have any feedback from openjfx-malinglist? Any bug-ticket or something? Would be nice to have these listed here.

**Comment by sselvia** [comment]
Danny, no feedback from Oracle, I’ve been mainly concerned with trying to get the app up on the OS X store.  I worked around the bundler arguments by just having an info.plist in my deploy -> macosx folder

As soon as I get back to that I’ll let everyone know.

**Comment by FibreFoX** [comment]
@sselvia Hi, do you have any response from openjfx-mailinglist? If it's a bug inside the JDK, could you show me where to look? (dont own a mac-system)

**Comment by FibreFoX** [comment]
After looking at the [Info.plist.template](https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/resources/com/oracle/tools/packager/mac/Info.plist.template#L30) I may have found something ;)

"DEPLOY_BUNDLE_CATEGORY" is mapped to [BundleParams.PARAM_CATEGORY](https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/java/com/sun/javafx/tools/packager/bundlers/BundleParams.java#L77), while "DEPLOY_BUNDLE_SHORT_VERSION" is mapped to [StandardBundlerParam.VERSION](https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/java/com/oracle/tools/packager/StandardBundlerParam.java#L303), so this should be your configuration:

```
<bundleArguments>
    <applicationCategory>public.app-category.business</applicationCategory>
    <appVersion>2.0.1</appVersion>
</bundleArguments>
```

**Comment by FibreFoX** [comment]
There is another thing I'm a bit confused: is there any reason you are not using the [bundlers special argument](https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/java/com/oracle/tools/packager/mac/MacAppBundler.java#L67)?
```
<bundleArguments>
    <mac.category>Business</mac.category>
</bundleArguments>
```

**Comment by sselvia** [comment]
Danny,

No I don't they never acknowledged the issue and when I got so wrapped up in my Mac App Store release it never came back up as part of the conversation. I have not reviewed the changes you made recently, I believe you thought you found something in the maven plugin?  I will pick up your changes and test this again to see if I can get a response. As it stands now, I have to have my own info plist file so I can update the version manually for the App Store. Is the changed code in a snapshot I can download?

Thanks,

Scott

**Comment by FibreFoX** [comment]
Hi @sselvia ,

I didn't need to change anything, it's already existing, just the names of the bundle-arguments you were using are the wrong ones.

**Comment by sselvia** [comment]
I will look again but I thought I used the names that Apple has defined in their info plist. Maybe the items I'm setting are not supported by the packager and that is why they are not being set. So it would then be an enhancement to the packager and not the maven plugin

**Comment by FibreFoX** [comment]
I think you are misunderstanding, how these specific bundle-arguments are passed.

When setting `<bundleArguments>` you DONT have to use the names within the plist-file, you have to check that native bundler yourself, if these names are valid, and what they are.

To make sure, you can replace/set some field, you first have to check the used template-file [`Info.plist.template`](https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/resources/com/oracle/tools/packager/mac/Info.plist.template#L30), to make sure the OpenJDK-master-branch does not diverge from the local installed JDK, you have to check that file inside local `JDK_HOME\lib\ant-javafx.jar` (with the corresponding path).
When you found some entry, e.g. `DEPLOY_BUNDLE_CATEGORY`, you are required to check [for it's replacement/usage](https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/java/com/oracle/tools/packager/mac/MacAppBundler.java#L638).

It is very inconvenient, I know, but it's the only way I'm dealing with ... maybe it is documented somewhere on the oracle sites, but I don't know where these "hidden"/"special" bundler-arguments are listed, sorry.

Therefore, I will close this issue, please feel free to re-open when your problem isn't fixed and relates to something of this maven-plugin.

**Comment by sselvia** [comment]
I understand and no problem. I will continue to use my own info plist

Thanks,

Scott

**Comment by FibreFoX** [comment]
Just out of curiosity: are you watching these issue-messages via mail? I'm asking because I'm using markup to create links, to show you the places/files I've found to look into, and as far is I see, these links are not displayed correctly in github-mails.

**Comment by sselvia** [comment]
Yes mostly on my phone during the day and my mail client in the evening. I'm able to use the links so far
