### ISSUE TITLE
Linux native bundle not executable

### ISSUE THREAD

**Issue by hotzst** [javafx-maven-plugin/javafx-maven-plugin#156]
Using this configuration on my OpenPatrician project will create an executable *.exe on Windows. The execution runs through successfully on Linux as well, but the produced executable fails to run with the following two lines:
     OpenPatricianDisplay-0.5.0-SNAPSHOT No main class specified
     OpenPatricianDisplay-0.5.0-SNAPSHOT Failed to launch JVM
Here is the plugin configuration:
```xml
<plugin>
  <groupId>com.zenjava</groupId>
  <artifactId>javafx-maven-plugin</artifactId>
  <executions>
    <execution>
      <phase>package</phase>
      <goals>
	<goal>native</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <mainClass>ch.sahits.game.OpenPatrician</mainClass>
    <verbose>true</verbose>
  </configuration>
</plugin>
```
I tried also a more simpler project: https://github.com/TheItachiUchiha/MediaPlayerFX with the same results. It seams that a simple HelloWorld project (no dependencies, no modules) created an executable artefact.
To verify if the issues lies with the JDK packager, the system or the Maven plugin I created an ant build script which creates an artefact, which is executable:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
 
<project name="OpenPatrician Linux Native build" default="zip" basedir="target"
  xmlns:fx="javafx:com.sun.javafx.tools.ant">
  <!-- TODO this property must match the JDK 8 installation on the system -->
  <property name="JAVA_HOME" value="/usr/lib/jvm/java-8-oracle"/>

   <property name="app.name" value="OpenPatrician"/>
  <property name="build.classes.dir" value="classes"/>
  <property name="build.dist.dir" value="dist"/>
  <property name="native.output.dir" value="../bundles/${app.name}"/>
  <property name="mainClass" value="ch.sahits.game.OpenPatrician"/>
  <property name="app.version" value="0.5.0-SNAPSHOT"/>
 
  <target name="bundle">
    <taskdef resource="com/sun/javafx/tools/ant/antlib.xml"
      uri="javafx:com.sun.javafx.tools.ant"
      classpath="${JAVA_HOME}/lib/ant-javafx.jar"/>
      <fx:application id="OpenPatrician"
        name="${app.name}"
        mainClass="${mainClass}"/>
      <fx:resources id="appRes">
        <fx:fileset dir="." includes="OpenPatricianDisplay-${app.version}.jar"/>
        <fx:fileset dir="jfx/app/lib"/>
      </fx:resources>
      <fx:jar destfile="${build.dist.dir}/${app.name}-${app.version}.jar">
        <fx:application refid="OpenPatrician"/>
        <fx:resources refid="appRes"/>
        <fx:fileset dir="${build.classes.dir}"/>
    <manifest>
        <attribute name="Implementation-Vendor" value="Sahits"/>
        <attribute name="Implementation-Version" value="1.0"/>
	<attribute name="Main-Class" value="${mainClass}" />
    </manifest>
    </fx:jar>
      <fx:deploy outdir="." embedJNLP="true"
        outfile="${app.name}"
        nativeBundles="all">
        <fx:application refId="OpenPatrician"/>
        <fx:resources refid="appRes"/>
        <fx:info title="OpenPatrician Linux"
          vendor="Sahits"/>
      </fx:deploy>
  </target>
</project>```
JDK version used for both cases was 1.8.0_60 together with the javafx-maven-plugin version 8.1.4 on a Linux Mint KDE.

**Comment by FibreFoX** [comment]
Hi @hotzst, the problem is inside existing JDK and [got reported by me](https://bugs.openjdk.java.net/browse/JDK-8137114), the problem was documented in issue #124 , current version of javafx-maven-plugin (which is 8.1.5) provided a workaround for this. Mostly the DOT inside the appname is the source of the problem, because used libpackage.so does not do the right thing to find everything (you really should read the linked issue :smile: )

**Comment by FibreFoX** [comment]
@hotzst to just create the linux native files, use `<bundler>linux.app</bundler>` inside `<configuration>`-block of javafx-maven-plugin, reduces build-time to check with the new 8.1.5-version
