### ISSUE TITLE
NumberFormatException in version check for "1.8.0_45-internal"

### ISSUE THREAD

**Issue by totalvoidness** [javafx-maven-plugin/javafx-maven-plugin#159]
During some tests I noticed, that there is a NumberFormatException in `com.zenjava.javafx.maven.plugin.AbstractJfxToolsMojo:isAtLeastOracleJavaUpdateVersion(int)`, if the reported Java version is "1.8.0_45-internal", which is the case for the OpenJDK in Ubuntu Vivid.

A workaround is to override this by invoking maven with `-Djava.version=1.8.0_45`. Thus I wouldn't consider this a critical bug. But still worth fixing as such suffixes are quite common on various Linux distributions.

**Comment by FibreFoX** [comment]
Currently only oracle jdk is supported, thanks for the hint.

**Comment by totalvoidness** [comment]
Well with the Oracle packager I never had the #124 problem at all. The whole point in my tests was to switch to the OpenJDK, if you remember ;)
Is there a particular incompatibility, because of which you don't want to support the OpenJDK or is it just a bad feeling cause it's untested?

**Comment by FibreFoX** [comment]
Implementation of JavaFX of the Oracle-JDK was the first and main target of this maven-plugin, mostly because of the support of oracle. Let me setup up another ubuntu-vm and check it myself.

Upgrading tests on TravisCI wasn't as expected: https://github.com/javafx-maven-plugin/javafx-maven-plugin/pull/160

**Comment by FibreFoX** [comment]
@totalvoidness just to make sure: how did you install openjfx on your system? Just found [this](https://www.chrisnewland.com/building-openjdk-9-and-openjfx-from-source-on-debian-378) tutorial for openjdk and openjfx, I'm not sure if `javapackager` is present. Having TravisCI running openjdk8 without modifications didn't provide required `ant-javafx.jar`. As far as I understood, the FX-part is separated from openjdk.

**Comment by totalvoidness** [comment]
@FibreFoX yes, it's still separated currently. I just apt-get install'ed it and it somehow worked. I can provide a Docker file based on vanilla ubuntu:vivid, if that helps

**Comment by FibreFoX** [comment]
The problem comes with TravisCI currently, because they are just offering Ubuntu Trusty, but not Vivid. But meanwhile I will make some changes to the version-checker (which hopefully just makes everything else running ... we need that for some workarounds).

**Comment by totalvoidness** [comment]
Still waiting for a backport: https://github.com/travis-ci/travis-ci/issues/2968

**Comment by FibreFoX** [comment]
I'll push a snapshot-version online, would be nice, if you could check your build when I'm finished (will add a new comment here).

**Comment by FibreFoX** [comment]
Hi @totalvoidness, could you try using `8.1.6-SNAPSHOT`? Just add this to your `pom.xml`

```
<pluginRepositories>
    <pluginRepository>
        <id>oss-sonatype-snapshots</id>
        <url>https://oss.sonatype.org/content/groups/public/</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </pluginRepository>
</pluginRepositories>
```

**Comment by totalvoidness** [comment]
mvn package runs without errors and resulting .deb is executable after installation :+1:
