### ISSUE TITLE
How to set additional entries in manifest file

### ISSUE THREAD

**Issue by treimers** [javafx-maven-plugin/javafx-maven-plugin#163]
Hello,

I have been searching for a longer time now but I was unable to understand how to solve my issue.

I would like to set additional parameters in the manifest file in order to read values like application vendor, application title, application version etc. from the application code at runtime.

How can I set additionally entries in the manifest file? I tried something like below but it did not work:

	<plugin>
		    <groupId>com.zenjava</groupId>
			    <artifactId>javafx-maven-plugin</artifactId>
			    <version>8.1.5</version>
			    <configuration>
			        <mainClass>de.softquadrat.workbench.gui.App</mainClass>
			        <archive>
				        <manifestEntries>
				        	<url>http://www.softquadrat.de</url>
				        	<mode>development</mode>
				        </manifestEntries>
			        </archive>
			    </configuration>
			    <executions>
			    	<execution>
			    		<id>native</id>
						<goals>
							<goal>native</goal>
						</goals>
			    	</execution>
			    </executions>
	</plugin>

Maybe it is impossible due to restrictions of the java fx packager? Is it possible to provide a complete manifest file instead?

Thanks and best regards
Thorsten

**Comment by russ-p** [comment]
try this
```<groupId>com.zenjava</groupId>
            <artifactId>javafx-maven-plugin</artifactId>
            <version>8.1.5</version>
           <configuration>
                <mainClass>de.softquadrat.workbench.gui.App</mainClass>
                <manifestAttributes>
                        <url>http://www.softquadrat.de</url>
                        <mode>development</mode>
                 </manifestAttributes>
            </configuration>
...
```

**Comment by treimers** [comment]
This did not work, am I missing anything?

*pom.xml:*
			<plugin>
				<groupId>com.zenjava</groupId>
				<artifactId>javafx-maven-plugin</artifactId>
				<version>8.1.5</version>
				<configuration>
					<mainClass>de.softquadrat.workbench.gui.App</mainClass>
					<manifestAttributes>
						<url>http://www.softquadrat.de</url>
						<mode>development</mode>
					</manifestAttributes>
				</configuration>
			</plugin>

*MANIFEST.MF:*
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven
Built-By: treimers
Build-Jdk: 1.8.0_45

**Comment by russ-p** [comment]
try 'mvn jfx:jar' and check target\jfx\app\{finalName}-jfx.jar!\META-INF\MANIFEST.MF

**Comment by treimers** [comment]
Yepp, this worked. Thank you very much!
