### ISSUE TITLE
Something wrong with quotes and spaces in jvmArgs

### ISSUE THREAD

**Issue by aliebelt** [javafx-maven-plugin/javafx-maven-plugin#164]
I want to add a jvmArg to my application which contains spaces:

&lt;jvmArgs>
	&lt;jvmArg>-Dvisualvm.display.name="My Super App"&lt;/jvmArg>
&lt;/jvmArgs>

But in VisualVM the shown application-name is: "My

Escaping " with &amp;quot; or with \" did not work either.

**Comment by FibreFoX** [comment]
I would suggest to use `<jvmProperties>` for this, the escaping is the main reason this exists. I've already made a project for that: https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/master/src/it/11-access-application-and-jvm-parameters/pom.xml

Add this to your plugin-configuration:
```xml
<jvmProperties>
    <visualvm.display.name>My Super App</visualvm.display.name>
</jvmProperties>
```

**Comment by FibreFoX** [comment]
@aliebelt any progress/feedback on this?

**Comment by aliebelt** [comment]
Hi Danny, I found out that the javafx-maven-plugin is not the problem, it seems to be VisualVM. Apparently it can't handle spaces in an application name: http://stackoverflow.com/questions/4433979/how-do-i-give-a-name-to-a-visualvm-unknown-application#comment11367969_4436208

Following things work:
```xml
<jvmArgs>
    <jvmArg>-Dvisualvm.display.name=My_Super_App</jvmArg>
</jvmArgs>
<jvmProperties>
    <visualvm.display.name>My_Super_App</visualvm.display.name>
</jvmProperties>
```

**Comment by FibreFoX** [comment]
@aliebelt thanks for the feedback, never did something with VisualVM.

But i suggest to use the latter version for your configuration (jvmProperties).
