### ISSUE TITLE
Splash and Icon

### ISSUE THREAD

**Issue by rodsnjr** [javafx-maven-plugin/javafx-maven-plugin#165]
Hello, the project looks great.

I'm trying to generate a Windows Native Desktop Bundle.

I've followed the guide from [this topic](http://stackoverflow.com/questions/15880102/how-to-set-custom-icon-for-javafx-native-package-icon-on-windows?answertab=votes#tab-top)

I have an ${project.build.finalName}.ico on the directory from src/main/deploy/package/windows/

But that was and old topic, and it's not working, I'm not sure why. It may be something simple.

My Plugin in the pom

```
<plugin>
				<groupId>com.zenjava</groupId>
				<artifactId>javafx-maven-plugin</artifactId>
				<version>8.1.2</version>
				<configuration>
					<vendor>BigRiver</vendor>

					<mainClass>com.bigriver.erp.application.MainSplash</mainClass>

					<fork>true</fork>
					<source>1.8</source>
					<target>1.8</target>

					<transformers>
						<transformer
							implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
							<mainClass>com.bigriver.erp.application.MainSplash</mainClass>
						</transformer>
					</transformers>
					<artifactSet>
						<excludes>
							<exclude>junit:junit</exclude>
						</excludes>
					</artifactSet>

					<filters>
						<filter>
							<artifact>*:*</artifact>
							<excludes>
								<exclude>META-INF/*.SF</exclude>
								<exclude>META-INF/*.DSA</exclude>
								<exclude>META-INF/*.RSA</exclude>
							</excludes>
						</filter>
					</filters>
				</configuration>
			</plugin>
```

I've also tried the splash.jpg inside the deploy folder too, it's not working.

What I might be doing wrong?

Thanks for the help! And the lifesaving bundling plugin!

**Comment by FibreFoX** [comment]
Hi @rodsnjr 
beside my notes in the comment above, could you try this configuration?
```xml
<plugin>
    <groupId>com.zenjava</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version>8.1.5</version>
    <configuration>
        <vendor>BigRiver</vendor>
        <mainClass>com.bigriver.erp.application.MainSplash</mainClass>
        <appName>MainSplash</appName>
        
        <!-- DO SHOW DEBUG-OUTPUT -->
        <verbose>true</verbose>
    </configuration>
</plugin>
```

When having activated `verbose` output, you should see something like this:
`Using custom package resource [application icon]  (loaded from package/windows/MainSplash.ico)`

**Comment by FibreFoX** [comment]
@rodsnjr any progress on this?

**Comment by FibreFoX** [comment]
Please feel free to reopen this issue when providing new information.
