### ISSUE TITLE
build-jar failed: A required class was missing while executing com.zenjava:javafx-maven-plugin:8.1.4:build-jar: com/oracle/tools/packager/Log$Logger

### ISSUE THREAD

**Issue by JuKu** [javafx-maven-plugin/javafx-maven-plugin#166]
Hi,

I want to make sure, application is compatible to linux, so i have added your JavaFX plugin, but it doesnt works.
Maven coulnd found com.oracle.tools package.

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.zenjava:javafx-maven-plugin:8.1.4:build-jar (create-jfxjar) on project client-launcher: Execution create-jfxjar of goal com.zenjava:javafx-maven-plugin:8.1.4:build-jar failed: A required class was missing while executing com.zenjava:javafx-maven-plugin:8.1.4:build-jar: com/oracle/tools/packager/Log$Logger
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.zenjava:javafx-maven-plugin:8.1.4
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/Justin/.m2/repository/com/zenjava/javafx-maven-plugin/8.1.4/javafx-maven-plugin-8.1.4.jar
[ERROR] urls[1] = file:/C:/Users/Justin/.m2/repository/org/twdata/maven/mojo-executor/2.2.0/mojo-executor-2.2.0.jar
[ERROR] urls[2] = file:/C:/Users/Justin/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
[ERROR] urls[3] = file:/C:/Users/Justin/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
[ERROR] urls[4] = file:/C:/Users/Justin/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
[ERROR] urls[5] = file:/C:/Users/Justin/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
[ERROR] urls[6] = file:/C:/Users/Justin/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[7] = file:/C:/Users/Justin/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[8] = file:/C:/Users/Justin/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[9] = file:/C:/Users/Justin/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.1/plexus-utils-1.5.1.jar
[ERROR] urls[10] = file:/C:/Users/Justin/.m2/repository/org/codehaus/mojo/keytool-maven-plugin/1.5/keytool-maven-plugin-1.5.jar
[ERROR] urls[11] = file:/C:/Users/Justin/.m2/repository/org/codehaus/mojo/keytool-api/1.5/keytool-api-1.5.jar
[ERROR] urls[12] = file:/C:/Users/Justin/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.5/maven-shared-utils-0.5.jar
[ERROR] urls[13] = file:/C:/Users/Justin/.m2/repository/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
[ERROR] urls[14] = file:/C:/Users/Justin/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
[ERROR] urls[15] = file:/C:/Users/Justin/.m2/repository/org/codehaus/mojo/keytool-api-1.7/1.5/keytool-api-1.7-1.5.jar
[ERROR] urls[16] = file:/C:/Program%20Files/Java/jdk1.8.0/jre/../lib/ant-javafx.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: com.oracle.tools.packager.Log$Logger
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by FibreFoX** [comment]
Hi @JuKu , could you provide me with the requested information please? Otherwise I'll close this issue-ticket in the next time. Thanks

**Comment by JuKu** [comment]
@FibreFoX I have JDK Version 1.8.0_65 and Java 1.8.0_65.
I am using the intellij integrated maven version, something like 2.2.
I will send your details.

**Comment by JuKu** [comment]
Here is the maven version.

Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 14:51:28+0100)
Maven home: D:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 14.1.4\plugins\maven\lib\maven3
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_65\jre
Default locale: de_DE, platform encoding: windows-1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

**Comment by JuKu** [comment]
Here is the pom.xml.

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId><!-- ... --></groupId>
    <artifactId><!-- ... --></artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <slf4j.version>1.6.1</slf4j.version>
    </properties>

    <!-- distributation management code here -->

    <pluginRepositories>
        <pluginRepository>
            <id>oss-sonatype-snapshots</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>

    <repositories>
        <repository>
            <id>maven-central</id>
            <name>Maven Central</name>
            <url>http://repo1.maven.org/maven2/</url>
        </repository>

        <repository>
            <!-- nexus repository information -->
        </repository>

        <repository>
            <!-- nexus repository information -->
        </repository>
    </repositories>

    <dependencies>
        <!-- some internal dependencies -->

        <dependency>
            <groupId>org.diirt.javafx</groupId>
            <artifactId>javafx</artifactId>
            <version>3.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.oracle.tools</groupId>
            <artifactId>oracle-tools-all</artifactId>
            <version>2.0.0-RC9</version>
        </dependency>

        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>

        <dependency>
            <groupId>org.ini4j</groupId>
            <artifactId>ini4j</artifactId>
            <version>0.5.4</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>8.1.6-SNAPSHOT</version>
                <configuration>
                    <mainClass><!-- main class --></mainClass>
                </configuration>
                <executions>
                    <execution>
                        <id>create-jfxjar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build-jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.3.2</version>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass><!-- main class --></mainClass>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.googlecode.mavennatives</groupId>
                <artifactId>maven-nativedependencies-plugin</artifactId>
                <version>0.0.7</version>
                <executions>
                    <execution>
                        <id>unpacknatives</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- deploy to nexus -->
            <plugin>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>2.7</version>
                <executions>
                    <execution>
                        <id>default-deploy</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>


</project>
```

Because it doesnt works, i have tried also the 8.1.6-SNAPSHOT version.

**Comment by FibreFoX** [comment]
Please make sure to check `C:\Program Files\Java\jdk1.8.0_65\lib\ant-javafx.jar` containing that missing class/package. Something is messing up with the maven-classloader somehow, normal installed Oracle JDK should contain that package/class :(

**Comment by tarkal** [comment]
I have the near identical issue with the exception that I'm running on OSX. Apart from that, same version of IntelliJ, Maven etc. I've tried adding the following dependencies as per a couple of forum suggestions but without success so far:

```
<dependencies>
                    <dependency>
                        <groupId>com.oracle.tools</groupId>
                        <artifactId>oracle-tools-all</artifactId>
                        <version>1.2.2</version>
                    </dependency>
                    <dependency>
                        <groupId>com.oracle</groupId>
                        <artifactId>javaFX</artifactId>
                        <version>2.2</version>
                        <scope>system</scope>
                        <systemPath>${java.home}/lib/ext/jfxrt.jar</systemPath>
                    </dependency>
                </dependencies>
```

**Comment by FibreFoX** [comment]
@tarkal 
You don't need to add that system-scoped `jfxrt.jar`, because it's automatically used by maven (as it is a plugin-dependency, so your application does not have to depend on it). Maybe removing that dependency solves the issue. Could you try that? And please make sure current JDK 8 is installed.

**Comment by tarkal** [comment]
The problem originated without the dependencies. I only added them in after to try to solve the issue. I have the latest JDK installed.

Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)

**Comment by FibreFoX** [comment]
Hi @tarkal , could you please create a small project to recreate that issue? As this is on MacOSX, please open another ticket for this, as this one is windows-specific.

**Comment by tarkal** [comment]
Done. See #197.

**Comment by mozzy11** [comment]
am having the same issu and so far failed to sove it

**Comment by FibreFoX** [comment]
@mozzy11 please open a new bug, unless you are 100% sure this is the exact same problem, thanks
