### ISSUE TITLE
Found unsigned entry in resource

### ISSUE THREAD

**Issue by bito4ek** [javafx-maven-plugin/javafx-maven-plugin#171]
Hello,
I'm using jfx for generating web.
At the start jnlp i have a trouble: 
ExitException[ 3]java.lang.SecurityException: com.sun.deploy.net.JARSigningException: Found unsigned entry in resource: file:(project_link)/target/jfx/web/lib/javax.inject-1.jar
	at sun.plugin2.applet.JNLP2Manager.prepareLaunchFile(Unknown Source)
	at sun.plugin2.applet.JNLP2Manager.loadJarFiles(Unknown Source)
	at sun.plugin2.applet.Plugin2Manager$AppletExecutionRunnable.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Java - 1.8_60 x64.

**Comment by bito4ek** [comment]
temporary solving this problem is:
<dependency>
            <groupId>org.wildfly</groupId>
            <artifactId>wildfly-client-all</artifactId>
            <version>9.0.1.Final</version>
            <exclusions>
                <exclusion>
                    <artifactId>javax.inject</artifactId>
                    <groupId>javax.inject</groupId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by FibreFoX** [comment]
Some things first:
- what version of javafx-maven-plugin are you using?
- what version of java are you using `java -version` (full version-string)?
- what version of maven are you using `mvn -v`?

Would be nice to have some example-projsect from you, to reproduce that problem.

**Comment by bito4ek** [comment]
```
<groupId>com.zenjava</groupId>
<artifactId>javafx-maven-plugin</artifactId>
<version>8.1.5</version>
````

```
java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T14:57:37+03:00)
Maven home: /home/atelizhenko/Build-tools/apache-maven-3.3.3
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: ru_UA, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-33-generic", arch: "amd64", family: "unix"
```

```
OS - Ubuntu
uname -a
Linux odmin-Inspiron-5720 3.19.0-33-generic #38~14.04.1-Ubuntu SMP Fri Nov 6 18:17:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by FibreFoX** [comment]
You have specified `<verbose>true</verbose>`, is there any output? There should be any output (source listed below), could you check for it on your build?
https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/java/com/sun/javafx/tools/packager/PackagerLib.java#L648
http://hg.openjdk.java.net/openjfx/8u-dev/rt/file/f836b37cd22c/modules/fxpackager/src/main/java/com/sun/javafx/tools/packager/PackagerLib.java#l466

**Comment by bito4ek** [comment]
Signing (BLOB) "project_link"/target/jfx/web/lib/javax.inject-1.jar
Signed as "project_link"/target/jfx/web/lib/javax.inject-1.jar

**Comment by FibreFoX** [comment]
Could you check, if the signature is inside that jar-file you are using? 
javax.inject-1.jar -> the file `META-INF/SIGNATURE.BSF` should be there

**Comment by FibreFoX** [comment]
I haven't any web-project with that dependency ... and I can see that file being signed :( maybe your uploaded version of the javax.inject-file wasn't the signed one?!

**Comment by bito4ek** [comment]
http://www.filedropper.com/javaxinject-1
i upload my javax.inject lib after assembling.

Yes, it has  the file META-INF/SIGNATURE.BSF

**Comment by FibreFoX** [comment]
I'm very sorry, but I really can't help here, it's no issue of the plugin itself, the file gets signed. As this does not have anything to do with the plugin, I'll close this issue. When you are having a [full mcve example](http://stackoverflow.com/help/mcve), I doubt that I can help here. Please reopen, when you have such project. If you managed to find any solution, would be nice of you to drop some information about it here.

**Comment by FibreFoX** [comment]
@bito4ek While crawling through all old issues, I might want to add some information here:
The java(fx)packager introduced a new way of "signing", which never really worked out (it was called blob-signing). You might try it again having `<noBlobSigning>` set to `true` which was [introduced with version 8.4.0](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/javafx-maven-plugin-8.4.0/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L349). This way you are using the real `jarsigner` which itself should produce a working signed jar.

Could you retry that?

**Comment by FibreFoX** [comment]
@bito4ek ping

**Comment by bito4ek** [comment]
Thank you, I will try it on next week.

**Comment by FibreFoX** [comment]
@bito4ek I know I'm annoying ;) but did you get some time to check this issue?

**Comment by FibreFoX** [comment]
I will close this issue, but feel free to re-open or to drop some feedback after evaluation

**Comment by bito4ek** [comment]
@FibreFoX 
Hi there, sorry for my late.
I tried - i have an error:
`Failed to execute goal com.zenjava:javafx-maven-plugin:8.4.0:build-web (create-web) on project primosoft-gui: An error occurred while generating web deployment bundle: Error: Signing failed: duplicate entry: org/apache/xmlbeans/xml/stream/Location.class -> [Help 1]`

**Comment by FibreFoX** [comment]
@bito4ek do you have any project to reproduced on?

**Comment by bito4ek** [comment]
i have tried on my working production project...

**Comment by bito4ek** [comment]
@FibreFoX 
if i comment `<allPermissions>true</allPermissions>` - build ok, but jnlp didnt start

**Comment by FibreFoX** [comment]
Oh, I kinda see the problem ;)
https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/30b56fff864dc8ec05b302e62c29e7ae9d000289/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L600

It only works when you are using `mvn jfx:native`-command or `build-native`-goal (as part of the build-phase). There is a new (and more modern) jnlp-bundler, but needs some adjustments to get triggered. You have to specify some bundleArguments:
```xml
<configuration>
    <!-- snippet -->
    <noBlobSigning>true</noBlobSigning>
    <bundleArguments>
        <jnlp.allPermisions>true</jnlp.allPermisions>
        <jnlp.appName>yourApplication</jnlp.appName>
    </bundleArguments>
</configuration>
```

**Comment by bito4ek** [comment]
@FibreFoX 
i will try, thank you

**Comment by bito4ek** [comment]
@FibreFoX 
I tried, but it fails.
`ExitException[ 3]com.sun.deploy.net.FailedDownloadException: Unable to load resource: file:/${project path}/target/jfx/web/lib/xmlbeans-2.6.0.jar
	at sun.plugin2.applet.JNLP2Manager.downloadResources(Unknown Source)
	at sun.plugin2.applet.JNLP2Manager.prepareLaunchFile(Unknown Source)
	at sun.plugin2.applet.JNLP2Manager.loadJarFiles(Unknown Source)
	at sun.plugin2.applet.Plugin2Manager$AppletExecutionRunnable.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by bito4ek** [comment]
i run maven jfx:native and started in html webstart and it failed with error such as class not found, exaclty my class that extended jfx application.

**Comment by bito4ek** [comment]
when i changed bundler to `<bundler>ALL</bundler>` and run `mvn package` i have the same error:
`ExitException[ 3]com.sun.deploy.net.FailedDownloadException: Unable to load resource: file:/{path to project}/target/jfx/web/lib/xmlbeans-2.6.0.jar
	at sun.plugin2.applet.JNLP2Manager.downloadResources(Unknown Source)
	at sun.plugin2.applet.JNLP2Manager.prepareLaunchFile(Unknown Source)
	at sun.plugin2.applet.JNLP2Manager.loadJarFiles(Unknown Source)
	at sun.plugin2.applet.Plugin2Manager$AppletExecutionRunnable.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by FibreFoX** [comment]
Everything inside `target/jfx/web/` was produced by "build-web", please change that to "build-native". I really need some reproducable project, doesn't matter if application has realy function, but this setup seems very special.

**Comment by FibreFoX** [comment]
please change `<jnlp.appName>` to `<jnlp.outfile>` when calling build-native, I got confused when writing my previous post ;)
