### ISSUE TITLE
Set JVM args for native application.

### ISSUE THREAD

**Issue by mthiele** [javafx-maven-plugin/javafx-maven-plugin#18]
When generating a native application (we use Windows), the given ```<jreArgs>``` in the configuration are completely ignored. This is a real showstopper for us, since we have to increase the standard heap space and pass other parameters as well.
As far as I understand, the JavaFXPackager does support custom JVM arguments, so this should be possible from within this plugin, too.

**Comment by longweiquan** [comment]
Hello, I use the version 8.1.2 and I try to pass some command line arguments like this, but it doesn't work, could you help me ?

<configuration>
       <jvmArgs>
               <jvmArg>-Dspring.profiles.active=prod</jvmArg>
        </jvmArgs>
</configuration>

**Comment by maxd** [comment]
How are you decided that this doesn't work?

**Comment by longweiquan** [comment]
In the static main method, I try to log the "args" parameters and I get nothing. I have the maven configuration set as last command and launch the application by maven

```
public static void main(String[] args){
  if(args.length > 0){
     System.out.println(args[0]) ;
  }   
   ...
}
```

```
mvn jfx:run
```

**Comment by maxd** [comment]
`jvmArg` - command line arguments for JVM, not for application. You should use `userJvmArgs` but it has been broken (see #92).

**Comment by freabemania** [comment]
This is really great tool, much grateful! However i wonder if it's possible to get an argument from commandline into main(String[] args) like "open my.app --args -Dmyarg=value1" or equal in windows. I have no problem pushing args into my javaprocess but i would like to do something like this: <jvmArg>-Dmyval={$1}</jvmArg>

**Comment by FibreFoX** [comment]
@freabemania hi there, as this is a rather old issue, this might not be the right place ;)

But to answer your question: have you tried the [launcherArguments](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/3d2a4b9e46de4a6e42e925c2de4607e494168994/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L145)-property?
Something like this:
```xml
<launcherArguments>
    <launcherArgument>arg1</launcherArgument>
    <launcherArgument>arg2</launcherArgument>
    <launcherArgument>arg3</launcherArgument>
</launcherArguments>
```

**Comment by freabemania** [comment]
No i haven't, tried now, and yes i get them as arg1 arg2 arg3 into my app nicely! But how can i get the substituted from like 'open my.app --args myval1 myval2 etc....
Thx :-)

**Comment by FibreFoX** [comment]
@freabemania please open a new issue for this
