### ISSUE TITLE
Old/Unused dependencies collected

### ISSUE THREAD

**Issue by aliebelt** [javafx-maven-plugin/javafx-maven-plugin#180]
I have some lib-entries which are not part of my dependency graph (older versions of dependencies or unused ones):

   Compressing: C:\Users\aliebelt\AppData\Local\Temp\fxbundler9194108517832756673\images\win-exe.image\Fraunhofer IWES.vpp 1.68-SNAPSHOT\app\lib\brownies-collections-0.9.12.jar
   Compressing: C:\Users\aliebelt\AppData\Local\Temp\fxbundler9194108517832756673\images\win-exe.image\Fraunhofer IWES.vpp 1.68-SNAPSHOT\app\lib\commons-collections-3.2.1.jar
   Compressing: C:\Users\aliebelt\AppData\Local\Temp\fxbundler9194108517832756673\images\win-exe.image\Fraunhofer IWES.vpp 1.68-SNAPSHOT\app\lib\commons-collections-3.2.2.jar
   Compressing: C:\Users\aliebelt\AppData\Local\Temp\fxbundler9194108517832756673\images\win-exe.image\Fraunhofer IWES.vpp 1.68-SNAPSHOT\app\lib\commons-collections4-4.0.jar
   Compressing: C:\Users\aliebelt\AppData\Local\Temp\fxbundler9194108517832756673\images\win-exe.image\Fraunhofer IWES.vpp 1.68-SNAPSHOT\app\lib\commons-collections4-4.1.jar
   Compressing: C:\Users\aliebelt\AppData\Local\Temp\fxbundler9194108517832756673\images\win-exe.image\Fraunhofer IWES.vpp 1.68-SNAPSHOT\app\lib\commons-digester-1.8.1.jar
   Compressing: C:\Users\aliebelt\AppData\Local\Temp\fxbundler9194108517832756673\images\win-exe.image\Fraunhofer IWES.vpp 1.68-SNAPSHOT\app\lib\commons-io-2.4.jar
   Compressing: C:\Users\aliebelt\AppData\Local\Temp\fxbundler9194108517832756673\images\win-exe.image\Fraunhofer IWES.vpp 1.68-SNAPSHOT\app\lib\commons-lang3-3.4.jar
   Compressing: C:\Users\aliebelt\AppData\Local\Temp\fxbundler9194108517832756673\images\win-exe.image\Fraunhofer IWES.vpp 1.68-SNAPSHOT\app\lib\commons-math3-3.5.jar
   Compressing: C:\Users\aliebelt\AppData\Local\Temp\fxbundler9194108517832756673\images\win-exe.image\Fraunhofer IWES.vpp 1.68-SNAPSHOT\app\lib\commons-math3-3.6.jar
   Compressing: C:\Users\aliebelt\AppData\Local\Temp\fxbundler9194108517832756673\images\win-exe.image\Fraunhofer IWES.vpp 1.68-SNAPSHOT\app\lib\commons-net-3.3.jar
   Compressing: C:\Users\aliebelt\AppData\Local\Temp\fxbundler9194108517832756673\images\win-exe.image\Fraunhofer IWES.vpp 1.68-SNAPSHOT\app\lib\commons-net-3.4.jar
   Compressing: C:\Users\aliebelt\AppData\Local\Temp\fxbundler9194108517832756673\images\win-exe.image\Fraunhofer IWES.vpp 1.68-SNAPSHOT\app\lib\commons-validator-1.4.1.jar
   Compressing: C:\Users\aliebelt\AppData\Local\Temp\fxbundler9194108517832756673\images\win-exe.image\Fraunhofer IWES.vpp 1.68-SNAPSHOT\app\lib\commons-validator-1.5.0.jar
   Compressing: C:\Users\aliebelt\AppData\Local\Temp\fxbundler9194108517832756673\images\win-exe.image\Fraunhofer IWES.vpp 1.68-SNAPSHOT\app\lib\controlsfx-8.40.10.jar
   Compressing: C:\Users\aliebelt\AppData\Local\Temp\fxbundler9194108517832756673\images\win-exe.image\Fraunhofer IWES.vpp 1.68-SNAPSHOT\app\lib\controlsfx-8.40.9.jar
   Compressing: C:\Users\aliebelt\AppData\Local\Temp\fxbundler9194108517832756673\images\win-exe.image\Fraunhofer IWES.vpp 1.68-SNAPSHOT\app\lib\guava-18.0.jar
   Compressing: C:\Users\aliebelt\AppData\Local\Temp\fxbundler9194108517832756673\images\win-exe.image\Fraunhofer IWES.vpp 1.68-SNAPSHOT\app\lib\guava-19.0.jar

etc.

**Comment by FibreFoX** [comment]
So what does it have to do with this plugin? What does `mvn dependency:tree` print? Are you running `mvn clean` before running the `jfx:native`-goal?

**Comment by aliebelt** [comment]
Hi Danny, I'm sorry. It seems that it has been my fault. We switched to maven clean plugin 3.0.0 which was not executed correctly. After cleaning target folder everything works as expected again :)
