### ISSUE TITLE
JNLP-generation: path for dependency-lib on windows with backslash

### ISSUE THREAD

**Issue by FibreFoX** [javafx-maven-plugin/javafx-maven-plugin#182]
http://stackoverflow.com/questions/35758949/how-to-specify-the-jnlp-output-file-when-using-javafx-maven-plugin-for-creating/35773771?noredirect=1#comment59234018_35773771

> I'm able to deploy the javafx app with web start using the javafx-maven-plugin.but when I add other dependency(fontawesome jar) to pom,the jar is copied to lib directory. path to the jar in the jnlp file is <jar href="lib\fontawesomefx-8.9.jar"size="571068" download="null" /> which results in an error xitException[ 3]com.sun.deploy.net.FailedDownloadException: Unable to load resource: localhost:8080/installer/lib\fontawesomefx-8.9.jar.when I modify the path by changing the backward slash to a forward slash it works .Correct path localhost:8080/installer/lib/fontawesomefx-8.9.jar – 

Might be a bug inside lib-path-generation or inside JDK (to be determined)

**Comment by FibreFoX** [comment]
http://hg.openjdk.java.net/openjfx/8u-dev/rt/file/7a0629ba396d/modules/fxpackager/src/main/java/com/oracle/tools/packager/jnlp/JNLPBundler.java#l746

The jar-references are created with relative file-path, which generated system-specific dividers (`\` on windows)

**Comment by lilyevsky** [comment]
I just tried the 8.4.0 release, and this bug is still there. Am I doing something wrong, or indeed the bug was not fixed?

**Comment by FibreFoX** [comment]
@lilyevsky what bundler are you using? Are you setting `<bundler>jnlp</bundler>` or are you generating this via `mvn jfx:web`? What JDK-version are you using?

**Comment by FibreFoX** [comment]
Leaving this here for reference: Already got reported ! but closed as incomplete :(
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8144165
