### ISSUE TITLE
Adding native libraries to the native release

### ISSUE THREAD

**Issue by joao-fidalgo** [javafx-maven-plugin/javafx-maven-plugin#183]
Is there any way to achieve this?

For example, adding msvcr70.dll to the package.

**Comment by FibreFoX** [comment]
There exists an option to do this:
https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/master/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L224

Just point your configuration so some folder containing your additional files.

**Comment by joao-fidalgo** [comment]
@FibreFoX not sure if intended, but that link pointed me to some <pre> comment

**Comment by FibreFoX** [comment]
;) I really need to post more time-resistant links, sorry, got messed up, because I pushed a new version.

The part I ment:
```java
    /**
     * When you need to add additional files to generated app-folder (e.g. README, license, third-party-tools, ...),
     * you can specify the source-folder here. All files will be copied recursively.
     *
     * @parameter
     */
    protected File additionalAppResources;
```
