### ISSUE TITLE
How to package only the app (without the runtime) using jfx:native ?

### ISSUE THREAD

**Issue by marcelohack** [javafx-maven-plugin/javafx-maven-plugin#184]
I have an application that is full packaged, containing an app folder, a data folder and a runtime folder, but in some cases i want to package only the app folder, how i can do this?

**Comment by FibreFoX** [comment]
@marcelohack 
As far as I understood, this is already possible by providing an empty runtime-configuration to the used bundler:

```xml
<configuration>
    <mainClass>com.zenjava.test.Main</mainClass>
    <bundleArguments>
        <runtime />
    </bundleArguments>
</configuration>
```
Example configuration is already existing in the testing projects: https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/master/src/it/07-lifecycle-build-jfx-native/pom.xml#L40

**Comment by marcelohack** [comment]
Thanks @FibreFoX, i will try it!!
