### ISSUE TITLE
Icons and Splash Screen Images are not Copied

### ISSUE THREAD

**Issue by Gyetko** [javafx-maven-plugin/javafx-maven-plugin#19]
I am placing my icon (icon.png) and splash (splash.jpg) into the correct template directories.

When I run the command 

mvn -e -X jfx:build-webstart -DskipTests

The output indicates that the icon file is found.  
Using icon file at 'C:\...\src\main\deploy\icon.png'

But is is not copied into the output directory.

Inspecting the code in AbstractBundleMojo.java, you are setting the local variable icon to the class level defined icon and then setting the local icon.  When the subclass for this class called BuildWebstartMojo.java attempts to use the class level icon variable, it is still null.  Your code checks for null and then does nothing, no icon file is copied.

The fix for this is to delete the lines

        File icon = this.icon;

        File splashImage = this.splashImage;

from AbstractBundleMojo.java.

I hope you can make a new revision for me as we are deploying our software by the end of April.

Sincerely,

Brian

**Comment by FibreFoX** [comment]
This gets closed, because plugin was rewritten.
