### ISSUE TITLE
Run java process with current runtime

### ISSUE THREAD

**Issue by bito4ek** [javafx-maven-plugin/javafx-maven-plugin#195]
Hello,
Runtime.getRuntime().exec("java -jar Somejar.jar"); will run another java process, but "java" will use system jre runtime. Is there some way to run this in current runtime (that bunlder includes in execution folder)? in that runtime path folder "bin" is absent...
Thank you.

**Comment by FibreFoX** [comment]
Hi @bito4ek , currently there is no way.

Just let us discuss that here: running the jfx-application with system-JRE is just a replacement of the old strategy calling another maven-plugin with a lot of problems. Calling `mvn jfx:run` creates the jfx-jar and calls that via system-JRE (as you mentioned).

Having your application using the "bundled-JRE" would depend on two things:
- having to run a bundler creating that JRE-copy
- having the bundler to be configured not skipping to copy JRE

The current solution does not require these steps to be considered.

Another thing you should think about: the bootstrapping-process of the native launchers are not running some java-command, they are loading the JVM via native includes. Launching your application will always be different, testing by launching your application with the bundled "JRE" would not be as equivalent as wished.

What do you think about this?

**Comment by bito4ek** [comment]
Hi @FibreFoX 
Ok.
Let me discuss my first question with you.
In my case, i have users, that have more than 2 jres installed.
When users have been using my program, they are not tied to cuurent jre the environment, because my program has own runtime.
In this case, when invoke System.getProperty("java.home"); it will show path to bundled runtime.
Else in my case, my program is updated frequently, so i wrote simple trivially updater program, that makes updating (copy from ftp etc jars) and run another main jar file.
Thats because i want to save runtime to run another java process in current runtime...
Thank you.

**Comment by FibreFoX** [comment]
In that case I would suggest to not use `mvn jfx:run`, because it is not intended to recreate the scenario you described, it's intended to reduce the manual steps for running the javafx-application, more like a quick-fix or helper-tool, not to recreating the real situation.

As the created native launcher does some magic to find it's JRE and the configuration which resides inside the generated `.cfg`-file inside the app-folder, and does some magic to find the main jar-file, you should run that file instead of using the maven-plugin.

**Comment by FibreFoX** [comment]
@bito4ek if this is okay with you, please close this issue, otherwise will be closed next week

**Comment by bito4ek** [comment]
@FibreFoX 
Thank you.
I will investigate by other methods..
