### ISSUE TITLE
MANIFEST.MF not contain Main-Class

### ISSUE THREAD

**Issue by dongwenting** [javafx-maven-plugin/javafx-maven-plugin#196]
here is my pom.xml:
    
             <plugins>
			<plugin>
				<groupId>com.zenjava</groupId>
				<artifactId>javafx-maven-plugin</artifactId>
				<version>8.4.0</version>
				<configuration>
					<mainClass>javafx.LoginApplication</mainClass>
				</configuration>
			</plugin>
		</plugins>

i run mvn jfx:jar to package, but target/xxx.jar/META-INF/MANIFEST.MF not contain Main-Class, why?

**Comment by FibreFoX** [comment]
@dongwenting You are looking at the wrong jar, the one being created by the plugin resides at the path `<your-project>/target/jfx/app/<appName>-jfx.jar`

Please close this issue if this answeres your question.

**Comment by dongwenting** [comment]
yes,  my question looks stupid > <.

I have another question. I have a system dependency, but it does not package into lib. 

		<dependency>
			<artifactId>xxx</artifactId>
			<groupId>oms</groupId>
			<version>1.0</version>
			<scope>system</scope>
			<systemPath>${basedir}/lib/oms.jar</systemPath>
		</dependency>

Right now, my solution is copying it to lib, and change /target/jfx/app/<appName>-jfx.jar/META-INF/MANIFEST.MF, add  lib/oms.jar to Class-Path.

Is there a better solution, thank you very much!

**Comment by FibreFoX** [comment]
The javafx-maven-plugin only uses runtime-dependencies and compile-dependencies.

If you really need that library, and can't use some local proxy-repository (sonatype nexus, apache archia, ...), you could use something like a project-repository:

```xml
    <repositories>
        <!-- in project repository, mostly for private libs -->
        <repository>
            <id>in-project</id>
            <name>In Project Repo</name>
            <url>file://${project.basedir}/private_libs</url>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </releases>
        </repository>
    </repositories>
```
You have to create some folder-structure: `groupId/artifactId/version/oms-1.0.jar`, so the dependency-entry changes to:
```xml
    <dependency>
        <artifactId>xxx</artifactId>
        <groupId>oms</groupId>
        <version>1.0</version>
    </dependency>
```

As this isn't related to jfx-m-p, I will close this issue.

**Comment by dongwenting** [comment]
yes, it works ! thank you very much.
just a little mistake in your answer.
      
    <dependency>
        <groupId>xxx</groupId>
        <artifactId>oms</artifactId>    
        <version>1.0</version>
    </dependency>
