### ISSUE TITLE
file association

### ISSUE THREAD

**Issue by jsyzthz** [javafx-maven-plugin/javafx-maven-plugin#198]
hello,
i create a file and renamed to "test.ext1",then i downloand example "22-create-fileassociations-single-mimetypes" and build a native installer, i have install the exe file on my computer. but i cannot double click the "test.ext1" to open my soft? 
```
<plugin>
                <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>8.2.0</version>
                <configuration>
                    <mainClass>com.zenjava.test.Main</mainClass>
                    <verbose>true</verbose>
                    <bundleArguments>
                        <runtime />
                    </bundleArguments>
                    <fileAssociations>
                        <fileAssociation>
                            <description>association 1</description>
                            <extensions>ext1</extensions>
                            <contentType>application/dummy</contentType>
                            <icon>somePathToIcon</icon>
                        </fileAssociation>
                        <fileAssociation>
                            <description>association 2</description>
                            <extensions>ext2</extensions>
                            <contentType>application/dummy2</contentType>
                        </fileAssociation>
                    </fileAssociations>
                </configuration>
            </plugin>
```
see my configuration. any issue about it? thanks!

**Comment by FibreFoX** [comment]
@jsyzthz you should try to upgrade to current version 8.4.0 :smile_cat: of the javafx-maven-plugin

**Comment by FibreFoX** [comment]
@jsyzthz the file association-feature [was added with version `8.3.0`](https://github.com/javafx-maven-plugin/javafx-maven-plugin/releases/tag/javafx-maven-plugin-8.3.0), so it is expected to not work on `8.2.0`

**Comment by jsyzthz** [comment]
@FibreFoX it woks! thanks. i have another question about the icon path,how to set? ico or icns?

**Comment by FibreFoX** [comment]
@jsyzthz this depends on the bundler itself.

To set the icon-path, you just have to set `<icon>somePathToIcon</icon>` to se corresponding icon you want to have. On systems running Windows, you have to set ICO-files (at least that I'm aware of). Don't have that much experience here as this is a very new feature :) but I hope you are find this very interesting.

**Comment by jsyzthz** [comment]
@FibreFoX 
i haven't any better idea. but i have one a solution to resolve this on mac,win and linux.

add following code into pom
```
<fileAssociations>
	<fileAssociation>
		<description>type1 File</description>
		<extensions>type1</extensions>
		<contentType>application/type1</contentType>
		<icon>${file.associationIcon}</icon>
	</fileAssociation>
</fileAssociations>
```
```
<profiles>
	<profile>
		<id>Windows</id>
		<activation>
			<os>
				<family>Windows</family>
			</os>
		</activation>
		<properties>
			<file.associationIcon>${project.basedir}/src/main/deploy/package/windows/${project.build.finalName}.ico</file.associationIcon>
		</properties>
	</profile>
	<profile>
		<id>Linux</id>
		<activation>
			<os>
				<family>Linux</family>
			</os>
		</activation>
		<properties>
			<file.associationIcon>${project.basedir}/src/main/deploy/package/linux/${project.build.finalName}.png</file.associationIcon>
		</properties>
	</profile>
	<profile>
		<id>Mac</id>
		<activation>
			<os>
				<family>Mac</family>
			</os>
		</activation>
		<properties>
			<file.associationIcon>${project.basedir}/src/main/deploy/package/macosx/${project.build.finalName}.icns</file.associationIcon>
		</properties>
	</profile>
</profiles>
```
it will depend on you os.thanks.

**Comment by FibreFoX** [comment]
@jsyzthz yes, providing that file icons is heavily dependend on the OS you are running the bundlers :) but that solution you provided here would have been the same solution I would work with :+1:
