### ISSUE TITLE
Failing the build when bunder fails (exe)

### ISSUE THREAD

**Issue by bjakke** [javafx-maven-plugin/javafx-maven-plugin#200]
Hi,

If I get errors from inno setup/signtool during the build, e.g.

> SignTool Error: The specified timestamp server either could not be reached or
returned an invalid response.

Which in turns shows

> java.io.IOException: Exec failed with code 2 command ...

However the build is still reported as SUCCESS. Is this expected behaviour? 
Currently I don't have task/execution that would fail after building the native installer if it is not present (I use antrun plugin + wildcard copy), probably as a workaround it is possible to make build fail there, but I wanted to report this in case it is a bug and not intended behavour.

**Comment by FibreFoX** [comment]
@bjakke sorry but I don't get what this is about. Issues related to Inno Setup are not related to the javafx-maven-plugin.

To verify your problem, could you make any project to reproduce your constellation? What do you mean with "SignTool", there is nothing about inside the WinExeBundler.

**Comment by bjakke** [comment]
Sorry, that probably wasn't that informative, I will try to write better when I'm back at work where I do have the problem (but I try to write here something now..). I'm also somewhat new to maven so it is possible that I have misunderstood something here.

I sign the executable which this plugin creates via .iss override which uses signtool.exe (windows sdk tool used to sign). This signing is configured in the .iss override file (+some in the inno setup installation). If this signing step (which is done during the building of the installer) executed by inno setup fails, all I see in the console is the

> java.io.IOException: Exec failed with code 2 command ...

error, but that error wont fail the build. I sort of half-expected that it should, therefore my question that is it expected of this plugin to fail the build if something goes wrong in the bundlers?

By looking at the NativeMojo.java in the .execute method there is a try-catch for the (Bundler) b.execute(...) if which throws PackagerException should result MojoExecutionException being thrown (which I assume would fail the build?). It is however possible that the failures in the signing tool (or others, I need to check) in inno setup wont be thrown as PackagerExceptions from the Bundler implementation (which are from the javapackager tools so outside the scope of this plugin).

**Comment by bjakke** [comment]
Also as a note this is not that big of a problem, as I probably can create a check when I copy the installers via an ant task (i.e. if there is no files -> fail the build). This was more of a check that is this plugin supposed to behave like this.

(Also a BIG thanks for all who have created/contributed this plugin)

**Comment by FibreFoX** [comment]
@bjakke Thanks for that explanation, now I DO understand what you mean. I will check that, but it MIGHT be something inside the bundler itself (and not by this maven-plugin).

This plugin is a wrapper of the provided java-interface used by the tool "javapackager", which is divided into separated "bundlers", separated for each operating system. It is possible to override some files and settings by changing some properties of this maven-plugin or by providing some files with a special name/position inside the `src/main/deploy/package`-folder (the "deploy"-folder is special to this plugin, but the package-folder is something that came frome the provided bundler of the JDK).

Regarding Inno Setup: it is called by the class [WinExeBundler](https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/java/com/oracle/tools/packager/windows/WinExeBundler.java), maybe there is some problem with your certificate which fails, but I will try to look into that.

for the next time: having some project to reproduce is always more than welcome :smile_cat:

**Comment by FibreFoX** [comment]
A quick look into OpenJFX might be the source of your exception and the behaviour of NOT failing the build: https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/java/com/oracle/tools/packager/windows/WinExeBundler.java#L370

As this is nothing regarding the plugin itself, do you want to close this issue?

**Comment by bjakke** [comment]
I guess I should have remembered that the packager was open source too; sorry. I guess this is at least documentation in case someone has the same problem. Closing issue.

**Comment by FibreFoX** [comment]
@bjakke no problem :) at least you have some more information about what is going on. If you have other problems which might not be any bug of the javafx-maven-plugin, just drop me a line via e-mail :smile_cat:
