### ISSUE TITLE
Calling jfx:run via NetBeans IDE 8.1 fails if no clean

### ISSUE THREAD

**Issue by FlorianWolters** [javafx-maven-plugin/javafx-maven-plugin#201]
I am using NetBeans 8.1, Maven 3.3.9, exec-maven-plugin 1.4.0 and javafx-maven-plugin 8.4.0 under Windows 7.

When I call `mvn jfx:run` from the CLI everything is fine, reproducible. But I have a problem invoking the goal `jfx:run` from NetBeans (via *Run*).

I defined `nbactions.xml` as follows:

    <?xml version="1.0" encoding="UTF-8"?>
    <actions>
      <action>
        <actionName>run</actionName>
        <goals>
          <goal>jfx:run</goal>
        </goals>
      </action>
    </actions>

If I select *Clean* in NetBeans and then *Run* everything is fine. But if I invoke *Run* now again, the following output is generated:

    cd D:\workspace\foo; JAVA_HOME=D:\\Programme\\Java\\jdk1.8.0_74 M2_HOME=D:\\Programme\\Java\\apache-maven-3.3.9 cmd /c "\"\"D:\\Programme\\Java\\apache-maven-3.3.9\\bin\\mvn.cmd\" -Dmaven.ext.class.path=D:\\Programme\\netbeans\\java\\maven-nblib\\netbeans-eventspy.jar;D:\\Programme\\netbeans\\java\\maven-nblib\\netbeans-cos.jar jfx:run\""
    Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
    Scanning for projects...
                                                                            
    ------------------------------------------------------------------------
    Building Foo 0.1.0-SNAPSHOT
    ------------------------------------------------------------------------

    >>> javafx-maven-plugin:8.4.0:run (default-cli) > :jar @ foo >>>

    >>> javafx-maven-plugin:8.4.0:jar (jar) > [jfxjar]package @ foo >>>

    --- maven-enforcer-plugin:1.4.1:enforce (enforce) @ foo ---

    --- properties-maven-plugin:1.0.0:set-system-properties (set-system-properties-parent) @ foo ---
    Set 12 system properties

    --- build-helper-maven-plugin:1.10:add-resource (add-resource) @ foo ---

    --- maven-resources-plugin:2.7:resources (default-resources) @ foo ---
    Using 'UTF-8' encoding to copy filtered resources.
    Copying 1 resource
    Copying 8 resources

    --- maven-compiler-plugin:3.5.1:compile (default-compile) @ foo ---
    Changes detected - recompiling the module!
    No processor claimed any of these annotations: javafx.fxml.FXML,javax.xml.bind.annotation.XmlAccessorType,com.sun.javafx.beans.IDProperty

    --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ foo ---
    Nothing to compile - all classes are up to date

    --- maven-jar-plugin:2.6:jar (default-jar) @ foo ---
    Building jar: D:\workspace\foo\target\foo-0.1.0-SNAPSHOT.jar

    --- javafx-maven-plugin:8.4.0:build-jar (create-jfxjar) @ foo ---
    call from CLI - skipping creation of JavaFX JAR for application

    <<< javafx-maven-plugin:8.4.0:jar (jar) < [jfxjar]package @ foo <<<

    --- javafx-maven-plugin:8.4.0:jar (jar) @ foo ---
    Building JavaFX JAR for application
    Adding 'deploy' directory to Mojo classpath: D:\workspace\foo/src/main/deploy

    <<< javafx-maven-plugin:8.4.0:run (default-cli) < :jar @ foo <<<

    --- javafx-maven-plugin:8.4.0:run (default-cli) @ foo ---
    Running JavaFX Application
    Exception in Application stop method
    java.lang.reflect.InvocationTargetException
    [...]
    Caused by: java.lang.ClassNotFoundException: de.florianwolters.util.Disposable
      at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
      at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
      ... 29 more
    Exception running application de.florianwolters.foo.Starter
    ------------------------------------------------------------------------
    BUILD FAILURE
    ------------------------------------------------------------------------
    Total time: 5.118 s
    Finished at: 2016-04-21T15:53:13+02:00
    Final Memory: 20M/51M
    ------------------------------------------------------------------------
    Failed to execute goal com.zenjava:javafx-maven-plugin:8.4.0:run (default-cli) on project foo: There was an exception while executing JavaFX Application. Please check build-log. -> [Help 1]

    To see the full stack trace of the errors, re-run Maven with the -e switch.
    Re-run Maven using the -X switch to enable full debug logging.

    For more information about the errors and possible solutions, please read the following articles:
    [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

It seems that the `target\jfx\app\lib` directory is not added to the classpath? What's the following all about?

> call from CLI - skipping creation of JavaFX JAR for application

How can I achieve a reproducible build, with and without NetBeans?

**Comment by FibreFoX** [comment]
Could you please paste your pom.xml? It's often something wrong with the configuration.

To make some parts a bit more clear: the javafx-maven-plugin creates a new java-process, because javafx is doing some bootstrapping, so it is not required to add something to the classloader.

**Comment by FibreFoX** [comment]
According to the output:

> Exception in Application stop method
> java.lang.reflect.InvocationTargetException
> [...]
> Caused by: java.lang.ClassNotFoundException: de.florianwolters.util.Disposable
>   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>   ... 29 more
> Exception running application de.florianwolters.foo.Starter

It seems that there are some parts missing in the bundle :( `Exception in Application stop method`

The message `call from CLI - skipping creation of JavaFX JAR for application` says, that you configured jfx-jar generation using maven-lifecycle (via executions), but the executions are skipped when using CLI-calls.

**Comment by FibreFoX** [comment]
@FlorianWolters just one personal note (aside the other notes): I'm developing with open CLI while running Netbeans :smile_cat: so it might not be well-tested on that part.

**Comment by FibreFoX** [comment]
@FlorianWolters ping

**Comment by FlorianWolters** [comment]
OK, I've been able to test this with a minimal project.

With the minimal project it works like expected (I can use the `nbactions.xml` posted before). Things seems start to get weird with multiple multi-module projects using parent POMs where the javafx-maven-plugin and/or exec-maven-plugin is (partially) configured in parent POMs.

Sadly I am not allowed to post the original project here. I am not able to reproduce the problem with a minimal "play" project. Therefore I created a demo project [here](https://github.com/FlorianWolters/tmp-javafx-maven-plugin-issue-201), which causes a similar issue.

1. Build everything with `mvn clean install`.
2. Open the parent project in NetBeans IDE.
3. Clean the project.
4. Run (F6) the project.
5. Run the project again. **Fail** with the following output:

        cd D:\Users\Florian\Dropbox\dev\java\example-parent\example-javafx-parent\example-javafx-mvvmfx; "JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_92" M2_HOME=C:\\java\\apache-maven-3.3.9 cmd /c "\"\"C:\\java\\apache-maven-3.3.9\\bin\\mvn.cmd\" -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans 8.1\\java\\maven-nblib\\netbeans-eventspy.jar;C:\\Program Files\\NetBeans 8.1\\java\\maven-nblib\\netbeans-cos.jar\" jfx:run\""
        Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
        Scanning for projects...

        ------------------------------------------------------------------------
        Building Example : JavaFX : mvvmFX 0.1-SNAPSHOT
        ------------------------------------------------------------------------

        >>> javafx-maven-plugin:8.4.0:run (default-cli) > :jar @ example-javafx-mvvmfx >>>

        >>> javafx-maven-plugin:8.4.0:jar (jar) > [jfxjar]package @ example-javafx-mvvmfx >>>

        --- maven-resources-plugin:2.6:resources (default-resources) @ example-javafx-mvvmfx ---
        Using 'UTF-8' encoding to copy filtered resources.
        Copying 2 resources

        --- maven-compiler-plugin:3.5.1:compile (default-compile) @ example-javafx-mvvmfx ---
        Nothing to compile - all classes are up to date

        --- maven-resources-plugin:2.6:testResources (default-testResources) @ example-javafx-mvvmfx ---
        Using 'UTF-8' encoding to copy filtered resources.
        skip non existing resourceDirectory D:\Users\Florian\Dropbox\dev\java\example-parent\example-javafx-parent\example-javafx-mvvmfx\src\test\resources

        --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ example-javafx-mvvmfx ---
        Nothing to compile - all classes are up to date

        --- maven-surefire-plugin:2.12.4:test (default-test) @ example-javafx-mvvmfx ---

        --- maven-jar-plugin:2.4:jar (default-jar) @ example-javafx-mvvmfx ---
        Building jar: D:\Users\Florian\Dropbox\dev\java\example-parent\example-javafx-parent\example-javafx-mvvmfx\target\example-javafx-mvvmfx-0.1-SNAPSHOT.jar

        --- javafx-maven-plugin:8.4.0:build-jar (create-jfxjar) @ example-javafx-mvvmfx ---
        call from CLI - skipping creation of JavaFX JAR for application

        <<< javafx-maven-plugin:8.4.0:jar (jar) < [jfxjar]package @ example-javafx-mvvmfx <<<

        --- javafx-maven-plugin:8.4.0:jar (jar) @ example-javafx-mvvmfx ---
        Building JavaFX JAR for application
        Adding 'deploy' directory to Mojo classpath: D:\Users\Florian\Dropbox\dev\java\example-parent\example-javafx-parent\example-javafx-mvvmfx/src/main/deploy

        <<< javafx-maven-plugin:8.4.0:run (default-cli) < :jar @ example-javafx-mvvmfx <<<

        --- javafx-maven-plugin:8.4.0:run (default-cli) @ example-javafx-mvvmfx ---
        Running JavaFX Application
        Fehler: Hauptklasse de.florianwolters.example.javafx.helloworld.Starter konnte nicht gefunden oder geladen werden
        ------------------------------------------------------------------------
        BUILD FAILURE
        ------------------------------------------------------------------------
        Total time: 3.690 s
        Finished at: 2016-04-24T17:37:16+02:00
        Final Memory: 14M/214M
        ------------------------------------------------------------------------
        Failed to execute goal com.zenjava:javafx-maven-plugin:8.4.0:run (default-cli) on project example-javafx-mvvmfx: There was an exception while executing JavaFX Application. Please check build-log. -> [Help 1]

        To see the full stack trace of the errors, re-run Maven with the -e switch.
        Re-run Maven using the -X switch to enable full debug logging.

        For more information about the errors and possible solutions, please read the following articles:
        [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Edit:** This is weird, after re-checking everyhing before commiting this, it **works** when opening the project to run directly. **I think I've found the reason** for this issue, it is related to the current working directory if opening a Parent POM project with NetBeans IDE with the option *Open Required Projects*.

If `process-classes exec:java` instead of `jfx:run` is used, everyhing works fine - it does not matter which project I opened:

    <?xml version="1.0" encoding="UTF-8"?>
    <actions>
      <action>
        <actionName>run</actionName>
        <goals>
          <goal>process-classes</goal>
          <goal>exec:java</goal>
        </goals>
      </action>
    </actions>

**Comment by FibreFoX** [comment]
Hi @FlorianWolters , I'm going to check it out :+1: thanks for the project and the feedback. Might take a while to find out what happens there ;)

**Comment by FibreFoX** [comment]
Hm ... thats strange, it only "fails" when opening the main project, making a "clean" before "run" seems to make it work. I suspect something with the maven-integration of Netbeans having something to do with this ... but I'm not sure about that. Workaround could be to have some terminal (cmd.exe) open while developing (might not be the best solution tho).

I'll let you know, if there is something to come up with.

**Comment by FibreFoX** [comment]
Hi,

I found some differences between calling via CLI or running via Netbeans:

*Using Netbeans-RUN*
```
Manifest-Version: 1.0
Permissions: sandbox
JavaFX-Version: 8.0
Class-Path: lib/mvvmfx-1.4.1.jar lib/slf4j-api-1.7.12.jar lib/typetool
 s-0.4.1.jar lib/doc-annotations-0.2.jar 
Created-By: JavaFX Packager
Main-Class: de.florianwolters.example.javafx.helloworld.Starter
```

*Using CLI `mvn clean jfx:jar`*
```
Manifest-Version: 1.0
Permissions: sandbox
JavaFX-Version: 8.0
Class-Path: lib/mvvmfx-1.4.1.jar lib/slf4j-api-1.7.12.jar lib/typetool
 s-0.4.1.jar lib/doc-annotations-0.2.jar lib/example-component-util-0.
 1-SNAPSHOT.jar 
Created-By: JavaFX Packager
Main-Class: de.florianwolters.example.javafx.helloworld.Starter
```

It seems that the dependency `example-component-util-0.1-SNAPSHOT.jar` gets lost when using Netbeans ... not sure why, but at least I'm having a clue now.

**Comment by FibreFoX** [comment]
Hi @FlorianWolters , I may have found something which works for me. It seems that Netbeans is messing with some maven-internals, so please turn of the "Compile on Save"-feature, e.g. by adding some `nb-configuration.xml`-file to the project "example-javafx-mvvmfx":

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project-shared-configuration>
    <!--
This file contains additional configuration written by modules in the NetBeans IDE.
The configuration is intended to be shared among all the users of project and
therefore it is assumed to be part of version control checkout.
Without this configuration present, some functionality in the IDE may be limited or fail altogether.
-->
    <properties xmlns="http://www.netbeans.org/ns/maven-properties-data/1">
        <!--
Properties that influence various parts of the IDE, especially code formatting and the like. 
You can copy and paste the single properties, into the pom.xml file and the IDE will pick them up.
That way multiple projects can share the same settings (useful for formatting rules for example).
Any value defined here will override the pom.xml file value but is only applicable to the current project.
-->
        <netbeans.compile.on.save>none</netbeans.compile.on.save>
    </properties>
</project-shared-configuration>
```

**Comment by FibreFoX** [comment]
@FlorianWolters after evaluation please close this issue ;) or provide more feedback

**Comment by FibreFoX** [comment]
Just to make it absolutely clear:
Calling `mvn jfx:jar` is a shortcut for generating jfxJar and creating a separated process of a new java-instance running that generated special jar-file.

Running the project via exec-maven-plugin does not the same thing, it is just running that main-class directly. Executing some javafx-jar-file does some special bootstrapping, where all JAR-files listed inside the `META-INF/MANIFEST.MF`-file. That's the reason I removed [the usage of exec-maven-plugin](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/cac55bd08090ad7e57ed973324e47838b215a367/src/main/java/com/zenjava/javafx/maven/plugin/RunMojo.java#L78) within `run`-mojo and switching to ProcessBuilder, which was the reason I removed deprecation for that maven-goal.

**Comment by FibreFoX** [comment]
@FlorianWolters ping

**Comment by FlorianWolters** [comment]
I will look at that workaround tomorrow. Seems like a legit workaound, I do not need *Compile On-Save* anyway...

**Comment by FlorianWolters** [comment]
Yeah, using the following minimal `nb-configuration.xml` file does seem to work after a quick test:

    <?xml version="1.0" encoding="UTF-8"?>
    <project-shared-configuration>
      <properties xmlns="http://www.netbeans.org/ns/maven-properties-data/1">
        <netbeans.compile.on.save>none</netbeans.compile.on.save>
      </properties>
    </project-shared-configuration>

I think this is some kind of bug in NetBeans IDE then. Maybe I should create an issue at <https://netbeans.org/community/issues.html>, referring to this issue here.

Thank you for finding a solution for that annoying behavior, though it hasn't been an error in your software. :+1:
