### ISSUE TITLE
Strip version

### ISSUE THREAD

**Issue by rguillens** [javafx-maven-plugin/javafx-maven-plugin#210]
Please add strip-version and/or strip-dependency-versions options.
Thank you.

**Comment by FibreFoX** [comment]
Can't follow you here. What  do you mean?

**Comment by rguillens** [comment]
I mean, that I need to remove the maven version number at the ending of the artifact names.

**Comment by FibreFoX** [comment]
Hi there, can you please describe, which version you mean?
If you wish the generated "-jfx.jar" to not contain any version, just set it via configuration:

```xml
<plugin>
    <groupId>com.zenjava</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version>8.5.0</version>
    <configuration>
        <appName>test</appName><!-- for generated native launcher -->
        <jfxMainAppJarName>test-jfx.jar</jfxMainAppJarName><!-- generated jar-file -->
    </configuration>
</plugin>
```

Stripping the version of the gathered dependencies is out of scope of this maven-plugin.

Does this answer your question/need?

**Comment by rguillens** [comment]
Yes, thank you very much. I'll work around to remove the dependencies versions with the maven dependency plugin.

**Comment by FibreFoX** [comment]
Okay :) looks like a "fix". Will close this issue.
