### ISSUE TITLE
When using takari-maven-plugin icons from icon-sets are not displayed

### ISSUE THREAD

**Issue by asukhyy** [javafx-maven-plugin/javafx-maven-plugin#211]
OS X: 10.11.5
Apache Maven: 3.3.9
Oracle JDK: 1.8.0_92
javafx-maven-plugin: 8.5.0
[takari-maven-plugin](https://github.com/takari/takari-maven-plugin)

_Note_:  Maybe it is becase of different parent class-loaders:
- plain maven: *sun.misc.Launcher$AppClassLoader*
- takari-maven-plugin: *java.net.URLClassLoader*

**Comment by FibreFoX** [comment]
Hi, do you have some reproducable project for this? And how does this relate to the javafx-maven-plugin?

**Comment by asukhyy** [comment]
[how to reproduce](https://github.com/asukhyy/issues/tree/master/issue-211)

**Comment by FibreFoX** [comment]
Hi @asukhyy ,

as I'm not having any MacOSX-system, I can't check it by myself, BUT: it seems to be a problem with the takari-maven-plugin, can't find any problems on windows-system. Please open a bug on that project instead here, if they are finding nothing, I might reopen this issue for further investigations.

**Comment by asukhyy** [comment]
@FibreFoX when I changed `com/zenjava/javafx/maven/plugin/AbstractJfxToolsMojo.java:110` to
`URLClassLoader sysloader = (URLClassLoader) Thread.currentThread().getContextClassLoader();`
it helps.

**Comment by FibreFoX** [comment]
Now I DO understand the problem :smile: and this seems to be a valid improvement. Will work on that.

**Comment by FibreFoX** [comment]
Can you try using the snapshot-version?
```xml
<version>8.5.1-SNAPSHOT</version>
```

Please add the sonatype-repository for "-SNAPSHOT"-versions of plugins:
```xml
<pluginRepositories>
    <pluginRepository>
        <id>oss-sonatype-snapshots</id>
        <url>https://oss.sonatype.org/content/groups/public/</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </pluginRepository>
</pluginRepositories>
```

**Comment by asukhyy** [comment]
@FibreFoX just verified - works.

**Comment by FibreFoX** [comment]
will be on maven-central with next release

**Comment by asukhyy** [comment]
+1
