### ISSUE TITLE
Command line current path

### ISSUE THREAD

**Issue by Adri7** [javafx-maven-plugin/javafx-maven-plugin#212]
I have a simple configuration for create both jar and native installer (Linux .deb). 
I install the .deb in /opt/MyApp. So the executable is /opt/MyApp/myapp and the jar is /opt/MyApp/app/myapp-jfx.jar
If i execute the jar (java -jar), inside my app i can do new File("") and it is relative to the current cmd location. BUT if i execute the executable, the path is not the cmd location, it is /opt/MyApp/app.
I tried multiple things instead of new File(""). The problem is not the code, is that the executable change the path qhen it calls the jar.

Thank you

**Comment by FibreFoX** [comment]
And what does this have to do with the javafx-maven-plugin? It's some issue with the native launcher, not this maven-plugin.

Have you tried this more ugly-looking code ([source](http://stackoverflow.com/a/15954821/1961102))?
```java
Path currentRelativePath = Paths.get("");
String s = currentRelativePath.toAbsolutePath().toString();
System.out.println("Current relative path is: " + s);
```
