### ISSUE TITLE
Platform specific icon for linux

### ISSUE THREAD

**Issue by erictwalker18** [javafx-maven-plugin/javafx-maven-plugin#214]
I'm using this wonderful plugin to create a native app across operating systems. I wanted to include the icon for the application in the app, which was done easily for Mac OSX and Windows by placing the icon file in src/main/deploy/macosx or src/main/deploy/windows, but didn't work for src/main/deploy/unix. Is there a specific way to include the icon in Linux/Unix native builds, or would this be part of an installer we would have to make?

**Comment by FibreFoX** [comment]
Did you try to use "linux" instead of "unix" as folder-name? ;)

**Comment by erictwalker18** [comment]
Yep. Sadly neither Linux nor Unix works.

**Comment by FibreFoX** [comment]
Just to clear some things: the icon is not part of the normal native launcher, it is only used when createing native installers.

This means:
* the icon is NOT copied while generating the native launcher: [see LinuxAppBundler](https://github.com/teamfx/openjfx-8u-dev-rt/blob/master/modules/fxpackager/src/main/java/com/oracle/tools/packager/linux/LinuxAppBundler.java#L227)
* the icon is used while generating [DEB-packages](https://github.com/teamfx/openjfx-8u-dev-rt/blob/master/modules/fxpackager/src/main/java/com/oracle/tools/packager/linux/LinuxDebBundler.java#L492) or [RPM-packages](https://github.com/teamfx/openjfx-8u-dev-rt/blob/master/modules/fxpackager/src/main/java/com/oracle/tools/packager/linux/LinuxRpmBundler.java#L371)

So this will be closed as invalid, as this has nothing to do with this maven-plugin.

**Comment by erictwalker18** [comment]
Thanks for the info!
