### ISSUE TITLE
External Configuration file

### ISSUE THREAD

**Issue by akabachkov** [javafx-maven-plugin/javafx-maven-plugin#215]
How can I add external configuration file. For example I have a GUI that communicates with some server, and I want keep server hostname in that external configuration file. Just now file is packaged inside *-jfx.jar file. Is it possible to say to plugin not package some file inside jar and add it to classpath?

**Comment by FibreFoX** [comment]
Hi there, you have to keep in mind, that you can have some ["multi-project-setup"](https://github.com/javafx-maven-plugin/javafx-maven-plugin/tree/master/src/it/16-multi-module-project). The core is inside "core/launcher", and the bundled result resides inside "application-bundle". You can set inside the "application-bundle"-project, you have to configure [additionalAppResources](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/master/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L207) which is a folder containing special/additional files like your configuration-file.

**Comment by akabachkov** [comment]
@FibreFoX, You right, by default to externalize some configuration is up to application logic. If I want to externalize some config in code I just need to retrieve file as resource from in code and run my application by adding required configuration file to classpath, but in case this javaFx plugin how can I affect to classpath calculation, which will be saved in MANIFEST file (Class-Path: lib/one.jar, lib/two.jar....). Is it possible to add some entry there?

**Comment by FibreFoX** [comment]
I think there is some misunderstanding of the whole process. Creating some "External Configuration file" implies, that this file is not on the existing classpath.

Normally you are creating a normal java-application, which might contain some resource-file. This is automatically available via `getResource()` from the classloader. All files that are inside `src/main/resource` are put into the generated jar when using normal `<package>jar</package>`-maven-project.

When using javafx-maven-plugin, you are using the normal official [javapackager](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javapackager.html) (formerly known as javafxpackager), this means that you are generating a "executable javafx archive" found at the `target/jfx/app`-folder. The whole conversion-process from "normal java" to "executable javafx" uses some maven-phase, the `[package](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html)`, this makes sure that some class-files are already compiled and existing, but the resource-files too.

When you want to put some file into the reach of your classloader, just put it into `src/main/resource` and get it via `[getResource(String name)](http://docs.oracle.com/javase/7/docs/api/java/lang/ClassLoader.html#getResource(java.lang.String))` or `[getResourceAsStream(String name)](http://docs.oracle.com/javase/7/docs/api/java/lang/ClassLoader.html#getResourceAsStream(java.lang.String))`, this has nothing to do with some option of this maven-plugin.

The previous [additionalAppResources](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/master/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L207)-property is ment to be used after the javafx-executable was generated.

To solve your puzzle, I would suggest to have that configuration-file reside into your jar-file as some default and before using it, checking if any file resides beside the jar-file and load it when existing, so you can have some override-mechanism.

Do you still think it's some bug of this javafx-maven-plugin?

**Comment by akabachkov** [comment]
@FibreFoX excuse me for misleading. This is not a bug. I just want to have some not jar packaged file in classpath of packaged application in runtime. In case of ordinary java application, I can run it with providing java -cp <external config file>, but in case of packaged JavaFX Application with this plugin I can't find a way how can I add this external file to classpath?

**Comment by FibreFoX** [comment]
I gave you a way, please do create some project (e.g. on github) where you can explain your problem, but as this is no bug, this get's closed!
