### ISSUE TITLE
File Association Error

### ISSUE THREAD

**Issue by fredfortier** [javafx-maven-plugin/javafx-maven-plugin#217]
I am able to execute the "native" goal except when including a "fileAssociations" element (following the "22-create-fileassociations-single-mimetypes").

Here is the error:
`
[ERROR] Failed to execute goal com.zenjava:javafx-maven-plugin:8.5.0:native (default-cli) on project kwcn-tray: Execution default-cli of goal com.zenjava:javafx-maven-plugin:8.5.0:native failed: An API incompatibility was encountered while executing com.zenjava:javafx-maven-plugin:8.5.0:native: java.lang.NoSuchFieldError: FA_DESCRIPTION
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.zenjava:javafx-maven-plugin:8.5.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/fredfortier/.m2/repository/com/zenjava/javafx-maven-plugin/8.5.0/javafx-maven-plugin-8.5.0.jar
[ERROR] urls[1] = file:/Users/fredfortier/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
[ERROR] urls[2] = file:/Users/fredfortier/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
[ERROR] urls[3] = file:/Users/fredfortier/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
[ERROR] urls[4] = file:/Users/fredfortier/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
[ERROR] urls[5] = file:/Users/fredfortier/.m2/repository/org/codehaus/plexus/plexus-utils/2.0.4/plexus-utils-2.0.4.jar
[ERROR] urls[6] = file:/Users/fredfortier/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[7] = file:/Users/fredfortier/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[8] = file:/Users/fredfortier/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[9] = file:/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/../lib/ant-javafx.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
`

Here is my maven version info:
`
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_31, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11", arch: "x86_64", family: "mac"
`

I am using version 8.5 of the plug-in.

**Comment by FibreFoX** [comment]
Please update to current version of the JDK, 1.8.0 update 31 is more than outdated.

Note to myself: don't rely on JDK-enums ... use hard-coded nasty strings instead ... :-1:
