### ISSUE TITLE
if I want to support java 7 (the version 80), what version should I use?

### ISSUE THREAD

**Issue by johnny5550822** [javafx-maven-plugin/javafx-maven-plugin#218]
If i have java 7, do I still use:

```
<plugin>
    <groupId>com.zenjava</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version>8.5.0</version>
    <configuration>
        <mainClass>your.package.with.Launcher</mainClass>
    </configuration>
</plugin>
```

**Comment by johnny5550822** [comment]
Also, what is your.package.with.Launcher?

**Comment by FibreFoX** [comment]
There is no support for Java 7, regarding "your.package.with.Launcher", just see the tag-name, it's the main class of your project.

There won't be any java 7 support (as java 7 is already out of updates)

**Comment by johnny5550822** [comment]
@FibreFoX ok, thanks.
