### ISSUE TITLE
17-secondary-launchers fails on MacOS (JDK 1.8.0_92, Maven 3.3.9)

### ISSUE THREAD

**Issue by sa-wilson** [javafx-maven-plugin/javafx-maven-plugin#219]
Test `17-secondary-launchers` from 8.5.0 is failing on MacOS 10.11.6 w/ JDK 1.8.0_92 and Maven 3.3.9 (MacPorts).

`javafx-maven-plugin/src/it/17-secondary-launchers/verify.bsh` is looking for a pair of configuration files in `target/jfx/native/javafx-maven-plugin-test-17-secondary-launchers-1.0/app/` and failing to find them, as they appear to be located at `target/jfx/native/javafx-maven-plugin-test-17-secondary-launchers-1.0.app/Contents/Java/` on MacOS, inside of an App bundle. The aforementioned directory does not exist, only the .app bundle, .dmg and .pkg installer.

**Comment by FibreFoX** [comment]
Thanks a lot, I personally don't have any MacOSX-system, so everything mac-related requires support by the community ;)
I will change the test, thanks for finding this.

**Comment by sa-wilson** [comment]
You're welcome.

I've been away from Java since early University and never worked with Beanshell, but looking into it I figured I'd do the pull request for you. Works on my mac and the build completes now.
