### ISSUE TITLE
Incorrect Javadocs on NativeMojo#bundler

### ISSUE THREAD

**Issue by ST-DDT** [javafx-maven-plugin/javafx-maven-plugin#221]
Sorry that this is very small issue, but
[`NativeMojo#bundler`](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/master/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L104), specifies 

> For a full list of available bundlers on your system, call `mvn jfx:list-bundler` inside your project.

but the actual maven goal ist `jfx:list-bundlers` (missing `s`).

**Comment by FibreFoX** [comment]
Feel free to create a simple pull-request ;) while creating my keyboard must have missed on me once again ;)
