### ISSUE TITLE
Can a JAVAfx application can be created as sh file for linux

### ISSUE THREAD

**Issue by gclouds** [javafx-maven-plugin/javafx-maven-plugin#225]
I am trying to create a tool work on different linux platforms but its long very long process to generate working copy for other platforms.

So can we create a sh file application that will work on accross linux platform

**Comment by FibreFoX** [comment]
Hi @gclouds, this is just a wrapper for the java(fx)packager, and currently it isn't supported by that application. But you can make your own bundler which provides you such a functionality, you just need to extend the `AbstractImageBundler`-class [like the LinuxAppBundler](https://github.com/teamfx/openjfx-8u-dev-rt/blob/master/modules/fxpackager/src/main/java/com/oracle/tools/packager/linux/LinuxAppBundler.java) does. That is the prefered way for building native bundles, it is even described by oracle as the way to go, no cross-compilation.
