### ISSUE TITLE
Set custom folder permission

### ISSUE THREAD

**Issue by fabry00** [javafx-maven-plugin/javafx-maven-plugin#228]
Is it possible to set custom folder permissions for a specific folder?
This is my pom code:

`<plugin>

                <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>8.1.5</version>
                <configuration>
                    <vendor>${vendor}</vendor>
                    <mainClass>${exec.mainClass}</mainClass>
                    <verbose>true</verbose>
                    <identifier>${macos.identifier}</identifier>
                    <needShortcut>true</needShortcut>
                    <needMenu>true</needMenu>
                    <additionalAppResources>conf</additionalAppResources>
                </configuration>
                <executions>
                    <execution>
                        
                        <id>create-jfxjar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build-jar</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>create-native</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build-native</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>`

As you can see I've added the 'conf' directory as additionalResources.
Inside the conf folder there are the log4j.properties and the log folder (with a dummy file inside it). In my project directory I've set the conf (recursively) directory permission to 777.
When I install my application using the .deb generated the structure of my installed application is the follow:
/opt/myprj/app/log4j.properties
/opt/myprj/app/log/dummy
The log folder has the follow permission: drwxrwxr-x
The log4j.properties and dummy file have the follow permission: -rwxrwxr-x
but when I start the application I've got the permission denied error. If I set 777 to log folder then the error disappear.

Thank you

**Comment by FibreFoX** [comment]
Hi @fabry00,
first of all please use the latest version of this plugin: `8.6.0`

Your question is related to the tool `dpkg-deb`, so this can be overridden with own `template.`-file. To see what file is used, please look at the output done with `<verbose>true</verbose>`, somewhere it should say something about "using default".

As this is nothing done by this maven-plugin, this issue will get closed. You are required to read the documentation for `dpkg-deb`
