### ISSUE TITLE
mvn jfx:jar don't bundle dependency is system type to lib-folder

### ISSUE THREAD

**Issue by astarring** [javafx-maven-plugin/javafx-maven-plugin#231]
For example, if I have a ojdbc.jar want's copy to bundled lib-folder, 
```
<dependency>
            <groupId>com.oracle</groupId>
            <artifactId>ojdbc14</artifactId>
            <version>10.2.0.3.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/resources/lib/ojdbc14.jar</systemPath>
</dependency>
```
but seems mvn jfx:jar or mvn jfx:native don't bundle the system scope jar to lib-folder

**Comment by FibreFoX** [comment]
That's correct and wanted behaviour. Defining some dependency with system-scope means that this File is already on the System, not only the development-system, but the targeted System too. You need to put your oracle-jdbc-library into some private maven-repository. The only exception to this is the packager.jar, which the plugin searches for.

As a solution for you which is recommended in your case: you put it into a different folder like `src/main/additionalFiles/lib` and set `<additionalAppResources>src/main/additionalFiles/</additionalAppResources>`, as you never have libs inside a jar-file. The bundler will copy all files inside that folder including the folder-structure.

**Comment by astarring** [comment]
Thanks for your reply!  I will try to use```additionalAppResources```.
