### ISSUE TITLE
Duplicated maven lifecycle

### ISSUE THREAD

**Issue by myron0815** [javafx-maven-plugin/javafx-maven-plugin#237]
"mvn clean deploy" works
"mvn clean install deploy" is executing a duplicated maven lifecycle when javafx-maven-plugin is there!

(basically we're using "clean install javadoc:jar sources:jar deploy" on buildserver, to get some additional jars; but this short "install deploy" already has this issue)

Usually "deploy" skips all phases it has already done - but when adding your plugin, it completely starts over from beginning (Maven behaves immediately correct when commenting out that plugin)
Are you using some special plugin mojo annotations which interfere with the default lifecycle?

execution plan for "clean deploy":
> [INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ myApp ---
> [INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ myApp ---
> [INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ myApp ---
> [INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ myApp ---
> [INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ myApp ---
> [INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ myApp ---
> [INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ myApp ---
> [INFO] --- maven-source-plugin:2.4:jar-no-fork (attach-sources-nofork) @ myApp ---
> [INFO] --- maven-site-plugin:3.4:attach-descriptor (attach-descriptor) @ myApp ---
> [INFO] --- javafx-maven-plugin:8.7.0:build-jar (create-jfxjar) @ myApp ---
> [INFO] --- javafx-maven-plugin:8.7.0:build-native (create-native) @ myApp ---
> [INFO] --- maven-assembly-plugin:2.6:single (make-assembly) @ myApp ---
> [INFO] --- maven-jar-plugin:2.6:test-jar (default) @ myApp ---
> [INFO] --- maven-install-plugin:2.5.2:install (default-install) @ myApp ---
> [INFO] --- maven-deploy-plugin:2.8.2:deploy (default-deploy) @ myApp ---

execution plan for "clean install deploy":
> [INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ myApp ---
> [INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ myApp ---
> [INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ myApp ---
> [INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ myApp ---
> [INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ myApp ---
> [INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ myApp ---
> [INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ myApp ---
> [INFO] --- maven-source-plugin:2.4:jar-no-fork (attach-sources-nofork) @ myApp ---
> [INFO] --- maven-site-plugin:3.4:attach-descriptor (attach-descriptor) @ myApp ---
> [INFO] --- javafx-maven-plugin:8.7.0:build-jar (create-jfxjar) @ myApp ---
> [INFO] --- javafx-maven-plugin:8.7.0:build-native (create-native) @ myApp ---
> [INFO] --- maven-assembly-plugin:2.6:single (make-assembly) @ myApp ---
> [INFO] --- maven-jar-plugin:2.6:test-jar (default) @ myApp ---
> [INFO] --- maven-install-plugin:2.5.2:install (default-install) @ myApp ---
> [INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ myApp --- **<-- deploy restarts here!!**
> [INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ myApp ---
> [INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ myApp ---
> [INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ myApp ---
> [INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ myApp ---
> [INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ myApp ---
> [INFO] --- maven-source-plugin:2.4:jar-no-fork (attach-sources-nofork) @ myApp ---
> [INFO] --- maven-site-plugin:3.4:attach-descriptor (attach-descriptor) @ myApp ---
> [INFO] --- javafx-maven-plugin:8.7.0:build-jar (create-jfxjar) @ myApp ---
> [INFO] --- javafx-maven-plugin:8.7.0:build-native (create-native) @ myApp ---
Exception: java.io.IOException: Access is denied
> [INFO] --- maven-assembly-plugin:2.6:single (make-assembly) @ myApp ---
> [INFO] --- maven-jar-plugin:2.6:test-jar (default) @ myApp ---
> [INFO] --- maven-install-plugin:2.5.2:install (default-install) @ myApp ---
> [INFO] --- maven-deploy-plugin:2.8.2:deploy (default-deploy) @ myApp ---

plugin is configured according to http://javafx-maven-plugin.github.io/ -> windows-native-mavenlifecycle (with the 2 executions)

**Comment by FibreFoX** [comment]
Why not just calling `mvn clean deploy`?? It already contains the install-phase.

This plugin binds the `jfx:jar`-goal to its own lifecycle, because we need to make sure `maven-jar-plugin:jar` gets called. I will look into this a bit, but you just might want to adjust your build-call ... e.g. making two of them. Is there any reason to "install deploy"?

**Comment by FibreFoX** [comment]
Any chance to get some reproduceable project from you? That `Exception: java.io.IOException: Access is denied` seems suspicious.

**Comment by FibreFoX** [comment]
Calling `mvn fr.jcgay.maven.plugins:buildplan-maven-plugin:list -Dbuildplan.tasks=clean,install,deploy` shows these duplicated calls ... now the big question remains: bug or no-bug ... I would tend to "no bug", because you are specifying to call all these phases.

**Comment by FibreFoX** [comment]
To reproduce I used some project where some plugin was added with some execution to the verify-phase, makes me even more to consider this as non-bug. Seems like normal behaviour of maven when calling two phases where one contains the other.

**Comment by myron0815** [comment]
After banging my head a few times on table, i could remember WHY we did this :)
This orginated a few years ago.
Idea was, to be sure that all modules of a multimodule build are deployed equally on nexus.
If module 3 breaks, 1+2 are already deployed on nexus, and might not work with the old 3 there together.
So, basically "mvn clean install javadoc:jar deploy" let maven first run up to install, to check if everything is ok, and then deploys it.

---

Since a "install deploy" gets normalized by Maven, i was thinking that Maven does this ALWAYS (since this might be the ultimatively workflow maven could archive; only ONE lifecycle execution). But a "mvn install install install deploy" gives me the same quirks... so i guess, this IS intentional :|
So i'm fine marking this as "no bug"
MNG-5666 (for Maven 4) might changes that finally!

---

The javadoc & sources plugin for example, have the same issue.
calling "javadoc:javadoc" calls the generate-sources phase.
This is fine, but for executing within a continous lifecycle tool, they made a special "jar-no-fork" goal, which doesn't rely on that phase. (it does the same, but requires the user to handle the correct execution order)
Could be an alternative for fx aswell?

---

The "access denied" issue
This comes from the duplicate execution.
The first install run worked flawlessly, but when deploy did run the phase again - it works only half.
(This was when i reported the linked issue)

> 14:45:59 Creating app bundle: myApp in d:\jenkins\workspace\myApp\target\jfx\native
> 14:46:00 Exception: java.io.IOException: Access is denied
> 14:46:00 Detected [iscc.exe] version 0 but version 5 is required.

In works on my machine, but doesn't on the other.
Guess this has to be something like correct access controls on created folders or something like.
IMHO, the plugin should FAIL here - it couldn't do its job, and produced a not working native directory.

---

Thx for the info on the buildplan plugin - really nice :)

---

Thanks for your effort on this!

**Comment by FibreFoX** [comment]
No problem, I have to thank you too, because you reported this here and provided some very useful information. As this was one of my very first contributions to this plugin (it did not support multiple executions before 8.1.3), it really hit me like a surprise that this might be buggy. I just keep learning since maintaining this project ;)

Thanks for pointing to [MNG-5666](https://issues.apache.org/jira/browse/MNG-5666), will try to keep an eye on this!

The idea of not breaking the build is, that if more than one bundler is used, this should just skip all faulty bundlers (imagine the scenario: SUCCESS FAILED SUCCESS SUCCESS ... only ONE failed, and having `<verbose>` set to `true` should reveal this while development-phase).

**Comment by myron0815** [comment]
ah ok, makes sense for multiple builders - never thought of this.
On the other side - when i specify multiple ones, i want them all and there is no reason for one to fail?!
(i usually do not look at successful builds - only failing ones)
Javadoc (and other plugins) have a dedicated failOnError configurable element ;)

Meanwhile i changed my build and it now sucessfully works on the problematic build slave :)

**Comment by FibreFoX** [comment]
This plugin is not developed for CI in mind, mostly the idea is to have it on the local machine working, fixing every missing piece while having verbose-mode on, and the pushing it onto the CI-server.

I will think about failing the build when only one bundler was specified!

**Comment by FibreFoX** [comment]
@myron0815 I created a separate issue about this, it's a good idea and hopefully makes other users not being confused about "there is no output"-states ;) while the build was successful
