### ISSUE TITLE
Unfiltered resources are being ignored when creating JAR

### ISSUE THREAD

**Issue by AlexeyKovynev** [javafx-maven-plugin/javafx-maven-plugin#240]
Steps to reproduce:
1. Create Maven JavaFX project which uses filtered (usual) and not filtered resources (binary, e.g. *.xlsx) as described at the bottom of this page: http://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html
2. Create JAR file using javafx-maven-plugin `mvn jfx:jar`
3. Open created JAR using an archiver (or launch the JAR and try functionality which depends from unfiltered resources)

Actual result:
Only filtered resources added to created JAR

Expected result:
All resources added to Jar. You could try my app to reproduce the issue: https://github.com/AlexeyKovynev/TaskHelper
I use template in it to export an Excel file. Excel file should not be filtered when using it from resources, so I put it into another resource folder and have configured everything as said in maven guideline (Step 1).
When I tried to export processes as Excel file using my app - function doesn't work because it uses template from resources. BUT everything works perfectly after adding tmp.xlsx file (you can see it in Git project sources) to created JAR manually.
![screen](https://cloud.githubusercontent.com/assets/5086678/19216130/488a65de-8db9-11e6-86d1-2755bc71d85c.png)

P.S. Thank you for this plugin, and I apologize for my low quality code - it's my first JavaFX app and I'm newbie in programming generally.

**Comment by FibreFoX** [comment]
Hi there,

this is no bug, you just need to adjust your `pom.xml`:
```xml

        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
            </resource>
            <resource>
                <directory>src/main/resources-filtered</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
```

**Comment by AlexeyKovynev** [comment]
Works perfectly now! My bad.
Thank you a lot.
