### ISSUE TITLE
The getParameters() method should be able to get launch paramaters

### ISSUE THREAD

**Issue by zenbones** [javafx-maven-plugin/javafx-maven-plugin#242]
Creating a native bundle, specifying <launcherArguments>, which are described as...

        <parameter>
          <name>launcherArguments</name>
          <type>java.util.List</type>
          <required>false</required>
          <editable>true</editable>
          <description>You can specify arguments that gonna be passed when calling your application.</description>
        </parameter>

...and using getParameters(), which is described as...

     * Retrieves the parameters for this Application, including any arguments
     * passed on the command line and any parameters specified in a JNLP file
     * for an applet or WebStart application.

...yields an empty set.

I'm looking to specify the command line arguments passed to the launcher and available via getParameters(). I know there are other ways of getting parameters passed as JVM args, but that's not what I'm looking for. Any help appreciated.

**Comment by FibreFoX** [comment]
Hi @zenbones , sorry but I can't follow you ... are you asking how you can access the parameters passed to the javafx-application, or are you asking about how to setup the maven-configuration to have some parameters always being present when executing the native launcher?

Maybe you want to look at this project: https://github.com/javafx-maven-plugin/javafx-maven-plugin/tree/master/src/it/11-access-application-and-jvm-parameters

**Comment by FibreFoX** [comment]
Ping @zenbones

**Comment by zenbones** [comment]
Sorry, life intervened with an immediate response. I know there are other ways of accessing parameters passed into the jvm/application, but I'm interested in using the getParameters() method available in javafx.application.Application, so I am asking about how to setup the the maven-configuration to have some parameters always being present when executing the native launcher. Specifically for the getParameters() method. Of course, as this is maven configuration, it is open to being parameterized upon build from a number of sources (env var, settings, profiles, etc.), which happens to be exactly the kind of flexibility I'm looking for. The best thing is that, from my perspective, hopefully, the getParameters() method should be stable across all build types (native, web, etc.), and so I have a single way to deal with start-up configuration in my code.

**Comment by FibreFoX** [comment]
I assume you didn't checked the project I linked you to, please look for yourself:
https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/master/src/it/11-access-application-and-jvm-parameters/src/main/java/com/zenjava/test/Main.java#L24

The `getParameters()`-method is getting used. The project was to show the multiple ways of having parameters being used and set up.

Do you can confirm, that this question is answered now?

**Comment by FibreFoX** [comment]
If the linked project is what you searched for, please close this issue.

**Comment by zenbones** [comment]
Checking it out...

**Comment by zenbones** [comment]
So I used the argument config in your pom and the code for printing out the various arguments and noticed that these lines...

      printMap(getParameters().getNamed(), "named args within jfx > ");
      printList(getParameters().getRaw(), "raw args within jfx");
      printList(getParameters().getUnnamed(), "unnamed args within jfx");

...print absolutely nothing, indicating that, however arguments are being passed in the example, they are not passed in a way that makes them available to the getParameters() method, which is the way I'm interested in.  I do see output for the other access methods. So, as an example of how this integration doesn't work, it's effective. My question still stands, however. Is there a way to add parameters to the configuration for the plugin that will be seen by the getParameters() method?

**Comment by FibreFoX** [comment]
Have you looked into the created `test.txt`-file? Everything should be written to that file, not printed out.

**Comment by zenbones** [comment]
I used your var config and copied the variable access code, but replaced your file output with logger output. And I do see the logger output for everything but the getParameter() methods which output nothing. To answer your questions...

I ran the app by going to .../target/jfx/native/myapp-<version> and clicking on the myapp-<version>.exe

 <plugin>
            <groupId>com.zenjava</groupId>
            <artifactId>javafx-maven-plugin</artifactId>
            <configuration>
              <mainClass>com.whatever.Application</mainClass>
              <vendor>Vendor</vendor>
              <title>My App</title>
              <description>My Description</description>
              <jvmArgs>
                <jvmArg>-DArgument1=hello_jvmArg</jvmArg>
              </jvmArgs>
              <jvmProperties>
                <Argument2>world_jvmProperty</Argument2>
              </jvmProperties>                    
              <userJvmArgs>
                <Argument3>someValue3_userJvmArgs</Argument3>
              </userJvmArgs>
            </configuration>
            <executions>
              <execution>
                
                <id>create-jfxjar</id>
                <phase>package</phase>
                <goals>
                  <goal>build-jar</goal>
                </goals>
              </execution>
              <execution>
                <id>create-native</id>
                <phase>package</phase>
                <goals>
                  <goal>build-native</goal>
                </goals>
                <configuration>
                  <nativeOutputDir>${project.build.directory}/jfx/native</nativeOutputDir>
                </configuration>
              </execution>
              <execution>
                <id>create-web</id>
                <phase>package</phase>
                <goals>
                  <goal>build-native</goal>
                </goals>
                <configuration>
                  <nativeOutputDir>${project.build.directory}/jfx/web</nativeOutputDir>
                  <bundler>jnlp</bundler>
                  <noBlobSigning>true</noBlobSigning>
                  <bundleArguments>
                    <jnlp.allPermisions>true</jnlp.allPermisions>
                    <jnlp.outfile>research-sales</jnlp.outfile>
                  </bundleArguments>
                  <keyStore>${project.basedir}/src/main/resources/keystore/keystore.jks</keyStore>
                  <keyStoreAlias>signFiles</keyStoreAlias>
                  <keyStorePassword>---</keyStorePassword>
                  <keyPassword>---</keyPassword>
                </configuration>
              </execution>
            </executions>
          </plugin>

**Comment by zenbones** [comment]
> 
          <plugin>
            <groupId>com.zenjava</groupId>
            <artifactId>javafx-maven-plugin</artifactId>
            <configuration>
              <mainClass>com.whatever.Application</mainClass>
              <vendor>Vendor</vendor>
              <title>MyApp</title>
              <description>My Descriptionl</description>
                    <jvmArgs>
                        <jvmArg>-DArgument1=hello_jvmArg</jvmArg>
                    </jvmArgs>
                    <jvmProperties>
                        <Argument2>world_jvmProperty</Argument2>
                    </jvmProperties>                    
                    <userJvmArgs>
                        <Argument3>someValue3_userJvmArgs</Argument3>
                    </userJvmArgs>
            </configuration>
            <executions>
              <execution>
                
                <id>create-jfxjar</id>
                <phase>package</phase>
                <goals>
                  <goal>build-jar</goal>
                </goals>
              </execution>
              <execution>
                <id>create-native</id>
                <phase>package</phase>
                <goals>
                  <goal>build-native</goal>
                </goals>
                <configuration>
                  <nativeOutputDir>${project.build.directory}/jfx/native</nativeOutputDir>
                </configuration>
              </execution>
              <execution>
                <id>create-web</id>
                <phase>package</phase>
                <goals>
                  <goal>build-native</goal>
                </goals>
                <configuration>
                  <nativeOutputDir>${project.build.directory}/jfx/web</nativeOutputDir>
                  <bundler>jnlp</bundler>
                  <noBlobSigning>true</noBlobSigning>
                  <bundleArguments>
                    <jnlp.allPermisions>true</jnlp.allPermisions>
                    <jnlp.outfile>stuff</jnlp.outfile>
                  </bundleArguments>
                  <keyStore>${project.basedir}/src/main/resources/keystore/keystore.jks</keyStore>
                  <keyStoreAlias>signFiles</keyStoreAlias>
                  <keyStorePassword>---</keyStorePassword>
                  <keyPassword>---</keyPassword>
                </configuration>
              </execution>
            </executions>
          </plugin>

**Comment by FibreFoX** [comment]
Hm ... sound odd, I will check this out and will create some dedicated example-project for this ;) maybe some parts are too confusing.

Btw: it's nice to see `noBlobSigning` being used :D does it work as expected?

**Comment by FibreFoX** [comment]
Hi @zenbones , sometimes I'm just blind ;) I got confused by these options, what you are seeking for [is already existing](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/3d2a4b9e46de4a6e42e925c2de4607e494168994/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L141). Please change your configuration like this:
```xml

<plugin>
    <groupId>com.zenjava</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version>8.7.0</version>
    <configuration>
        <mainClass>com.zenjava.test.Main</mainClass>
        <!-- don't add JRE to native distribution bundle (reduces build-time, but has some risks (see documentation for this) -->
        <bundleArguments>
            <runtime />
        </bundleArguments>
       
        <launcherArguments>
            <launcherArgument>arg1</launcherArgument>
            <launcherArgument>arg2</launcherArgument>
            <launcherArgument>arg3</launcherArgument>
        </launcherArguments>
    </configuration>
</plugin>
```

This should be the thing you are looking for, right?

**Comment by zenbones** [comment]
Yes, and I swear I had tested this first thing and it didn't work, but now it certainly does. Thank you. Maybe I did something different this time, but I guess I'll keep doing that. This ticket can be closed.
