### ISSUE TITLE
how can i add ico to my app?

### ISSUE THREAD

**Issue by wtksana** [javafx-maven-plugin/javafx-maven-plugin#244]

**Comment by FibreFoX** [comment]
It depends on what outcome you want to produce:
* Windows: put some ICO-file at `src/main/deploy/package/windows/{appname}.ico`, where `{appname}` is the configured appname of your application
* Mac OS(X): put some ICNS-file at `src/main/deploy/package/macosx/{appname}.icns`, where `{appname}` is the configured appname of your application
* Linux: put some PNG-file at `src/main/deploy/package/linux/{appname}.png`, where `{appname}` is the configured appname of your application

On Linux the icon is used for the installer, not the native launcher.

**Comment by wtksana** [comment]
grateful for your help
