### ISSUE TITLE
Passing on external arguments ta native javafx app

### ISSUE THREAD

**Issue by freabemania** [javafx-maven-plugin/javafx-maven-plugin#248]
Hi,

I am currently developing an app which i would like to handle certain filetypes. In order to do so the Explorer (on windows) or Open (on osx) probably passes arguments like this:
`"open MyJavaFX.app --args <filename>"`

In zenjava plugin (in conversation with FibreFoX) i was told to use (which ofcourse worked fine, but not for resolving the external variables)

```
<launcherArguments>
    <launcherArgument>arg1</launcherArgument>
    <launcherArgument>arg2</launcherArgument>
    <launcherArgument>arg3</launcherArgument>
</launcherArguments>

```
I would like something like the following:

```
<configuration>
	<mainClass>se.light.assembly64.fx.Main</mainClass>
	<launcherArguments>
	   <launcherArgument>${arg0}</launcherArgument>
	   <launcherArgument>${arg1}</launcherArgument>
        </launcherArguments>
</configuration>
```

There does not seem to be any way to resolve and map external arguments and piping them into my app. Or did i miss anything of the obvious (could be se ;-)) 

I will try to also have a look at this, but right now it's blocking me major!

Thx for this great plugin btw!

Cheers,
Fredrik

**Comment by FibreFoX** [comment]
Hi there,

maybe I didn't fully get what you wanted to archieve on the other issue :) hopefully I will unterstand you here.

So let me re-phrase what I understood you want to do, maybe you can point me to the piece, I am missing here.

You want to create some native launcher, which gets some arguments per default, always being the same values, right?

```xml
<launcherArguments>
    <launcherArgument>arg1</launcherArgument>
    <launcherArgument>arg2</launcherArgument>
    <launcherArgument>arg3</launcherArgument>
</launcherArguments>
```
This configuration-block means, that the listed arguments are added to the native launcher call! Let me make some example how this works, if you have the listed configuration-fragment active:
If you call `yourApp.exe arg4 arg5 arg6`, this will get "translated" into something like `java -jar lib/yourApp.jar arg1 arg2 arg3 arg4 arg5 arg6`, which ends up into being available inside the main-method, or `getParameters().getRaw()` and ´getParameters().getUnnamed()`.

Maybe you can describe a bit more clearly what you are expecting to reach, and how you want the application to behave.

**Comment by freabemania** [comment]
Hi, 

Yes, this works great. I misinterpreted how to get the arguments. Thx for good explanation! 

Closing this ☺️

Cheers 
Fredrik
