### ISSUE TITLE
native bundle with lib folder

### ISSUE THREAD

**Issue by harry12345** [javafx-maven-plugin/javafx-maven-plugin#25]
Parameter should be created to allow native bundle creation with lib folder. Dependent jars should be placed into lib folder. In the current version 1.5 one merged jar is created it causes serious problems, file overrides, file conflicts with the same name in the same folder between jars. Final solutions should be a parameter to allow bundle creation with lib folder.

**Comment by FibreFoX** [comment]
Closed due to rewritten plugin.
