### ISSUE TITLE
"Cross-compile" native apps?

### ISSUE THREAD

**Issue by senderle** [javafx-maven-plugin/javafx-maven-plugin#253]
This is a feature request rather than a bug report. I want to use the plugin to create native apps for multiple platforms, and it would be convenient if I could do so without actually having to maintain separate build machines for that purpose. Might there be a way to build (for example) a windows-native executable app on an OS X machine? I have a vague hope that "cross-compilation" will be easier than it normally would be with a non-jvm-based language. Apologies if this is a dumb question!

**Comment by FibreFoX** [comment]
Hi there,

this is in now way a dumb question, I even want that myself, BUT: this plugin is just a wrapper around the existing ANT tooling of `javapackager` (formerly known as `javafxpackager`). The installers are built with installed software on the build-machine (InnoSetup or WiX on windows), which means on every system, native installed tools are used, which makes it impossible to "cross-create" installers nor binaries (for example: the native launcher icon on windows is replaced using some other exe-file with the generated generic exe file and the specified ico-file).

This even is specified by [the official documentation of oracle](https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html#A1307236)

> Package per target platform
> 
> Self-contained application packages are platform-specific and can only be produced for the same system on which you build. To deliver self-contained application packages on Windows, Linux, and OS X, you must build your project on all three platforms.

**Comment by nyholku** [comment]
The proprietary and rather expensive JWrapper does complete cross builds ... so that should be the goal of Java community too.

**Comment by FibreFoX** [comment]
@nyholku JWrapper is not open-source! What should that application solve what's not already done by `javapackager`?

**Comment by nyholku** [comment]
Yes, I told you it is proprietary. But it does allow building for Linux/Windows on Mac and vice versa. And it is rather polished IMO, both at build time and runtime, for example functional splash screen, proper 'task manager' behavior, i.e. application built with it is almost indistinguishable from real native apps.. Having said that I've just ditched it from my projects because of the cost. It used to be free for small ops but now there is no free option and the latest free version fails on MacOs High Sierra :(

**Comment by nyholku** [comment]
If you are interested in details why not check their website:

https://www.jwrapper.com/features

forgot to mention: my app when packaged with javapackager is 117 MB, JWrapper stuffs it into 25 MB
