### ISSUE TITLE
Publish Maven Site

### ISSUE THREAD

**Issue by puce77** [javafx-maven-plugin/javafx-maven-plugin#254]
Please publish the Maven Site with the plugin goals documentation and/ or share the link.

**Comment by FibreFoX** [comment]
There is always to offline-way of calling `mvn jfx:help` which is the same.

**Comment by FibreFoX** [comment]
Remaining stuff from maven-site got cleaned (was outdated since years), working on gitbook the next days

**Comment by puce77** [comment]
You don't want to provide a Maven Site for this plugin? This is kind of standard for mature Maven plugins and I often use them as source for information or to discuss things colleagues.
With my projects I copy them to the GitHub pages, so one does not exclude the other.
