### ISSUE TITLE
updateExistingJar property seems to have no effect

### ISSUE THREAD

**Issue by puce77** [javafx-maven-plugin/javafx-maven-plugin#256]
Setting the updateExistingJar property to true doesn't seem to have any effect. The Manifest file is not updated.

**Comment by FibreFoX** [comment]
Hi @puce77, it's something special from the underlaying `javapackager`, I will check what's going on. Thanks for reporting

**Comment by FibreFoX** [comment]
https://github.com/Debian/openjfx/blob/fe76e38df3ebb582e3c9103e13bdefb2b1b61c8f/modules/fxpackager/src/main/java/com/sun/javafx/tools/packager/PackagerLib.java#L150
It should print some message for updating your jar-file. Can you make sure that it's printed out when having verbose set to true?

**Comment by FibreFoX** [comment]
ping @puce77

**Comment by puce77** [comment]
Here is the verbose output:

```
--- javafx-maven-plugin:8.8.0-SNAPSHOT:build-jar (default-build-jar) @ myproject-application ---
Building JavaFX JAR for application
Adding 'deploy' directory to Mojo classpath: /somepath/myproject-application/src/main/deploy
Updating jar file: /somepath/myproject-application/target/myproject-application-0.1-SNAPSHOT.jar
```

**Comment by FibreFoX** [comment]
@puce77 Can you send me a stripped down project for this? As this is done by the javapackager, it might be tricky to find the problem without a proper example.

**Comment by puce77** [comment]
@FibreFoX Please see the integration test in Pull Request #264

**Comment by FibreFoX** [comment]
Hi there, I tried it with some small project, and can't confirm.

Maybe there is some confusion about what jar-file gets "reused". As this maven-plugin relies on the existence of the jar-packaging, the normal jar-file, which gets generated, is reused as input to the javapackager-libs. Which means if you want to have special entries inside the jfx-jar manifest, they have to be inside the normal jar-file. 

Despite of that PR (which I can't accept), I need to reproduce your bug first.

**Comment by puce77** [comment]
Maybe there was a misunderstanding:  
The "normal" jar is what gets deployed to the Maven Repository Manager when running the goal deploy:deploy (for jar packaging this is bound to the deploy phase). 
My understanding was that using this property would update the "normal" jar, so that the jar which is deployed to the Maven Repository Manager contains all additions such as Manifest entries generated by the JavaFX Maven Plugin.

Are you saying this is not the intend of this property? It rather just switches the "source" from the output-dir to the "normal" jar? The Javadoc says "[...]updating the existing jar[...]" but in this case the existing jar doesn't get updated.

**Comment by puce77** [comment]
The PR was meant as a test showing the issue and can be used for test driven development.

**Comment by FibreFoX** [comment]
`Are you saying this is not the intend of this property?` you are right, it's not the intention. This plugin is "just" a wrapper around the existing tooling from the JDK (namely the `javapackager`), which comes packed with the same option.

As the packaging-type of the project is JAR, and nothing like "jfx" (which might be charming), this plugin does not change the generated jar-file. The property is ment to update the already generated jar-file (imagine the situation where developers to not call `mvn clean package` but just `mvn package`, or have a custom workflow where they are pre-generating that jfx-jar).

**Comment by FibreFoX** [comment]
Hi @puce77 , I got confused and checked again.

The `<updateExistingJar>`-parameter works in multiple ways :
1. when calling `mvn clean package` and having custom manifestEntries configured inside the generated "normal" jar-file, these manifest-entries are reused inside the generated jfx-jar. Example:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-jar-plugin</artifactId>
    <configuration>
        <archive>
            <manifestEntries>
                <something>special</something>
            </manifestEntries>
        </archive>
    </configuration>
</plugin>
```
This generates a normal jar, which contains this:
```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Built-By: FibreFoX
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_112
something: special
```

When the parameter is set to false, the generated jfx-jar ignores these entries, and generates their own:
```
Manifest-Version: 1.0
Permissions: sandbox
JavaFX-Version: 8.0
Class-Path: 
Created-By: JavaFX Packager
Main-Class: com.zenjava.test.Main
```

When it is set to `true`, all entries are reused (but not all), and generates this file:
```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Built-By: FibreFoX
Permissions: sandbox
JavaFX-Version: 8.0
Class-Path: 
Created-By: JavaFX Packager
Build-Jdk: 1.8.0_112
something: special
Main-Class: com.zenjava.test.Main
```

Which means that these entries did not get copied: 
```
Archiver-Version: Plexus Archiver
Built-By: FibreFoX
Build-Jdk: 1.8.0_112
something: special
```

2. when calling `mvn package`, having the jfx-jar existing and MODIFIED BY HAND, these by-hand modifications are reused (but not all, like with numer one).

**Comment by FibreFoX** [comment]
Just one small additional note: this parameter is used when using the maven-proguard-plugin, it rewrites some parts and changes the manifest, therefor this option is working as expected.

**Comment by FibreFoX** [comment]
@puce77 any questions about this? Would like to close this issue and corresponding PR #264.

**Comment by puce77** [comment]
Yeah, sorry for the confusion.

It didn't quite follow you on point 2, though.

It also would be great if we could update the Javadoc to make this a little bit more clear, e.g.

`    
    /**
     * Flag to switch on updating the existing jar created with Maven.
     *
     * <p>
     * If set to true, the following jar file is taken as source for the jfx-jar: '${project.basedir}/target/${project.build.finalName}.jar'.
     * <p>
     * This makes all entries inside MANIFEST.MF being transfered to the jfx-jar. The source jar is left unchanged.
     * <p>
     * If set to false, the jfx-jar is created based on '${project.build.outputDirectory}'.
     *
     *
     * @parameter property="jfx.updateExistingJar" default-value=false
     */
`

or something similar.

**Comment by FibreFoX** [comment]
I will work on a more precise description. ` The source jar is left unchanged.`  ;) it is always left unchanged.

As I'm currently active working on the plugin, and to avoid you working on similar things, please do not put effort into this for the next two days (and I hope it does not sound too harsh).

**Comment by puce77** [comment]
@FibreFoX OK, I've already merged the master branch to the PR https://github.com/javafx-maven-plugin/javafx-maven-plugin/pull/259 , though, and also created integration tests following the new "_properties" pattern.
And I'm also working on a new PR (work in progress): https://github.com/Drombler/javafx-maven-plugin/compare/develop-drombler...Drombler:native
I stopped working on this plugin now. Please tell me when I can continue.
