### ISSUE TITLE
Possible to add additional information to manifest file?

### ISSUE THREAD

**Issue by danielpeintner** [javafx-maven-plugin/javafx-maven-plugin#258]
I wonder whether one can add additional information (e.g., compileTime) to the generated manifest file.

**Comment by FibreFoX** [comment]
Only what maven does provide as property: https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/1a11696f63f449295215f4e1edde6a5be724966c/src/main/java/com/zenjava/javafx/maven/plugin/JarMojo.java#L92

**Comment by FibreFoX** [comment]
@danielpeintner does this answer your question? If so, please close this issue.

**Comment by danielpeintner** [comment]
thanks @FibreFoX! It works!

Just in case someone is wondering what needs to be done... below an example 


```
<plugin>
	<groupId>com.zenjava</groupId>
	<artifactId>javafx-maven-plugin</artifactId>
	<version>8.7.0</version>
	<configuration>
		<mainClass>...</mainClass>
		<manifestAttributes>
			<Build-Time>${maven.build.timestamp}</Build-Time>
		</manifestAttributes>
	</configuration>
</plugin>
```
