### ISSUE TITLE
Jarsigner -tsa and -tsacert options

### ISSUE THREAD

**Issue by martind574** [javafx-maven-plugin/javafx-maven-plugin#260]
Hi,

Recently bought a Comodo signing certifcate which requires a timestamp -tsa URL when signing. Don't seem to be able to produce a valid webstart without it. I could not see a signing option for this.. apologies if there is.. so I added options "-tsa" and "-tsacert" to your plugin here: https://github.com/martind574/javafx-maven-plugin.

Thanks,

Martin.

**Comment by FibreFoX** [comment]
Hi there, thanks for using this plugin.

The `jarsigner` was added by me as a workaround of that old blob-signing, and yes, it's missing some tweaks, but instead of making a parameter for each other special parameter of `jarsigner`, this should be solved in a more generic way. Will work on this and create a new release the next days, including a lot of other stuff.

**Comment by martind574** [comment]
Hi Danny,

Thanks for the reply. Plugin helped make the ant 2 maven jump fairly painless, great work.

Look forward to the new release.


Martin.

**Comment by FibreFoX** [comment]
@martind574 you might want to check my pull-request to adjust your plugin-configuration, I'm working hard on releasing this week

**Comment by FibreFoX** [comment]
This even got migrated into javafx-gradle-plugin: https://github.com/FibreFoX/javafx-gradle-plugin/commit/48952ce57675ac0d7d7e955382e4bf08f863c396

**Comment by FibreFoX** [comment]
@martind574 Can you try with current `<version>8.8.0-SNAPSHOT</version`> ?

Please add the sonatype-repository for "-SNAPSHOT"-versions of plugins:
```xml
<pluginRepositories>
    <pluginRepository>
        <id>oss-sonatype-snapshots</id>
        <url>https://oss.sonatype.org/content/groups/public/</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </pluginRepository>
</pluginRepositories>
```

**Comment by martind574** [comment]
Hi Danny,

Sorry for the late reply - now trying it.

Martin.

-----Original Message-----

**Comment by martind574** [comment]
Hi Danny,

At first run, I get "Only one alias can be specified". At first glance
of code, I think jarSignerParameters is being added instead of
additionalJarSignerParameters to jarsigner args?

Will have a closer look tomorrow.

Thanks for your work,


Martin.



-----Original Message-----

**Comment by FibreFoX** [comment]
Could you try to set `<verbose>` to `true`? It should print the used commandline before executing.

**Comment by martind574** [comment]
Hi Danny,

Please ignore my previous report - I had misconfigured
additionalJarParameters, but have corrected it:

<additionalJarsignerParameters>
    <additionalJarsignerParameter>-tsa http://timestamp.comodoca.com</a
dditionalJarsignerParameter>;
</additionalJarsignerParameters>

However, I get this now (I have had to replace my company name with
question marks):

[INFO] Running command: jarsigner -strict -keystore
/home/martind/Projects/technical/techsys/eclipse_ws2/Docker/ComodoSigni
ngCert.p12 -storepass abc3077 -keypass abc3077
/home/martind/Projects/technical/techsys/eclipse_ws2/TechSysClient/targ
et/jfx/native/lib/jboss-ejb-client-2.1.4.Final.jar ?????? ?????????
comodo ca limited id -tsa http://timestamp.comodoca.com -verbose
[INFO] Signing JAR files for jnlp bundle using jarsigner-method
Illegal option: -tsa http



Martin.






  
  





{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c554
93e4bb","name":"GitHub"},"entity":{"external_key":"github/javafx-maven-
plugin/javafx-maven-plugin","title":"javafx-maven-plugin/javafx-maven-
plugin","subtitle":"GitHub repository","main_image_url":"https://cloud.
githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.c
om/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/javafx-maven-plugin/javafx-maven-
plugin"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Reope
ned #260."}],"action":{"name":"View
Issue","url":"https://github.com/javafx-maven-plugin/javafx-maven-
plugin/issues/260#event-947684876"}}}

**Comment by FibreFoX** [comment]
You might want to add `"`-signs to it, as it gets executed as it is ;)

**Comment by FibreFoX** [comment]
@martind574 Haha, stupid me :D I forgot one detail: the order of the arguments. Will change it in a few moments.

**Comment by martind574** [comment]
Ok no worries - thanks.

**Comment by FibreFoX** [comment]
@martind574 Can you recheck using `mvn clean package -U` (the `-U` flag makes maven updating snapshot-versions).

**Comment by FibreFoX** [comment]
@martind574 
Comparing with the [commit on your fork](https://github.com/martind574/javafx-maven-plugin/commit/fdb721cbb502fc5cd20ed9c0c26ade5e4088afb4), the latter configuration should work, regardless of the order ... I often forget about ProcessBuilder working here ;)

**Comment by FibreFoX** [comment]
Version 8.8.0 got released, should work with configuration from this comment: https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/260#issuecomment-277465513

**Comment by martind574** [comment]
Hi @FibreFoX - as you suggested:

```
<additionalJarsignerParameters>
     <additionalJarsignerParameter>-tsa</additionalJarsignerParameter>
     <additionalJarsignerParameter>http://timestamp.comodoca.com</additionalJarsignerParameter>
</additionalJarsignerParameters>
```

Did the trick...

My previous config:
`
<additionalJarsignerParameter>-tsa http://timestamp.comodoca.com</additionalJarsignerParameter>
`
was the issue.
