### ISSUE TITLE
JavaFX API version

### ISSUE THREAD

**Issue by VulturRe** [javafx-maven-plugin/javafx-maven-plugin#270]
After updating IntelliJ IDEA to the latest version Scene Builder use 8.0.112 JFX API's version, but plugin use 8.0.111 version. So it gives a warning 

> фев 06, 2017 4:32:08 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.111

**Comment by FibreFoX** [comment]
Just for the records, the plugin uses the local installed version, nothing else is used.
