### ISSUE TITLE
Build failure 

### ISSUE THREAD

**Issue by aurora7795** [javafx-maven-plugin/javafx-maven-plugin#278]
Am new to Maven so this maybe a schoolboy error!
Am using Idea as my IDE on OS X and Windows - attempted to add a module with maven plugin as the architype and got the attached error, is there something i'm missing? Tried in Eclipse and it worked first time.
[java fx maven error.txt](https://github.com/javafx-maven-plugin/javafx-maven-plugin/files/760787/java.fx.maven.error.txt)

**Comment by FibreFoX** [comment]
You have to integrate this plugin into a project with `<package>jar</package>`-type, not the pom-type.

Just create a normal java-jar-project, and add this plugin to your build-tag.

**Comment by FibreFoX** [comment]
Even if a bit outdated, you can try to click your configuration with this website: http://javafx-maven-plugin.github.io/

The JavaFX-Maven-Plugin is a plugin, no archetype
