### ISSUE TITLE
Windows patform: Custom App icon

### ISSUE THREAD

**Issue by ouaibsky** [javafx-maven-plugin/javafx-maven-plugin#285]
Hi

I try to set a custom icon to my javafx application that is package with native bundler 

I success to customize installer icon by adding a ${appname}.ico into: 
> src/main/deploy/package/windows

Installer contains this icon but when I launch the application I still have the horrible java icon (grey).

Looks like the native packager is removing / taking priority on my code that is setup-ing an app icon programmatically

* Do i missed something ?
* Always on windows, is there a way to provide a .png in place of .ico ?

Thx in advance
Christophe

```xml
  <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>${javafxMavenPluginVersion}</version>
                <configuration>
                    <mainClass>sgcib.cascade.onyx.testing.ui.OnyxTestingApplication</mainClass>
                    <verbose>true</verbose>
                    <vendor>SGCIB</vendor>
                    <bundler>exe</bundler>
                    <!--<nativeReleaseVersion>1.0</nativeReleaseVersion>-->
                    <nativeReleaseVersion>${project.version}</nativeReleaseVersion>
                    <appName>${project.artifactId}</appName>
                </configuration>
                <executions>
                    <execution>
                        <id>create-jfxjar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build-jar</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>create-native</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build-native</goal>
                        </goals>
                        <configuration>
                        </configuration>
                    </execution>
``

**Comment by FibreFoX** [comment]
`Always on windows, is there a way to provide a .png in place of .ico ?` this is currently the limitation of the used `javapackager` itself, but converting isn't always the best idea (but mostly fitting approach).

About the gray icon: do you mean the created EXE-file, or do you mean the tiny icon from the window when launching?

**Comment by FibreFoX** [comment]
One note about the nativeReleaseVersion: you should make sure this is using [SEMVER](http://semver.org/spec/v2.0.0.html), as some bundlers might freak out

**Comment by FibreFoX** [comment]
Haha, after re-reading your question, I found the culprit: `src/main/resources/deploy/package/windows` this is wrong, you have to place your files in `src/main/deploy/package/windows` (without `resources`)

**Comment by ouaibsky** [comment]
Sorry I did a mistake on my issue description. Icon are well in **src/main/src/main/deploy/package/windows**

I didn't get any pb with my version number which is align on semver.

The installer itself (the .exe generated by the plugin) contains the custom icon. No issue there.
The pb is after when I start the installed application (so mine), the icon in task-bar is the one set by javafx natvie packager I guess (grey java logo). It looks like it override my javafx instruction (inside my app, setted with **stage.getIcons().addAll(image);**) 

Christophe

**Comment by FibreFoX** [comment]
Can you try to create some small project where I can reproduce this?

**Comment by ouaibsky** [comment]
Ya, I'll do it after office hours because company proxy is blocking pushing on internet.

**Comment by FibreFoX** [comment]
@ouaibsky any progress?

**Comment by FibreFoX** [comment]
Hey @ouaibsky , any progress on some example project?

**Comment by Parvesh-outcome** [comment]
how can i do in Mac?

**Comment by BouchkatiTarek** [comment]
I had the same issue today .......
As workaround I've done the following, and it worked for me


            <plugin>
                <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>8.6.0</version>
                <configuration>
                    <bundleArguments>
                        <icon>${project.basedir}/path/to/icon.ico</icon>
                    </bundleArguments>
                    <mainClass>${mainClass}</mainClass>
                    ..........
                </configuration>
                ..........
            </plugin>

**Comment by FibreFoX** [comment]
A common misunderstanding is the filename, because it has to contain the VERSION too (which is sometimes "-SNAPSHOT" and changes a lot), therefor you can fixate this by setting `appName`.
