### ISSUE TITLE
Problem with "Code Signing" on Windows using SignTool: Access is denied

### ISSUE THREAD

**Issue by McRender** [javafx-maven-plugin/javafx-maven-plugin#286]
Hi there...

I'am in the process if sigining my native build created with the javafx-maven-plugin and the Inno Setup script file. For code signing I'am using Microsoft's signtool.exe called from within the Inno Setup script file. When running a sample application directly from Inno Setup Compiler I do not get any errors but when executing the build process from within my Netbeans 8.2 IDE I get the following error:

```
Creating setup files
   Updating icons (SETUP.EXE)
   Signing: C:\Users\xxxxx\AppData\Local\Temp\fxbundler5707342220609073797\images\win-exe.image\xxxx\xxxx.exe
   Running Sign Tool command: "E:\Users\xxxxx\Desktop\Code Signing\002_Tools\signtool.exe" sign /f "E:\Users\xxxxx\Desktop\Code Signing\001_Certificate\xxxxx.p12" /t http://timestamp.comodoca.com/authenticode /p xxxxxx "C:\Users\xxxxxx\AppData\Local\Temp\fxbundler5707342220609073797\images\win-exe.image\xxxx\xxxx.exe"
Done Adding Additional Store

Number of errors: 1

SignTool Error: Access is denied.
SignTool Error: An error occurred while attempting to sign: C:\Users\xxxx\AppData\Local\Temp\fxbundler5707342220609073797\images\win-exe.image\xxxx\xxxx.exe

   Sign Tool command failed (Sign Tool failed with exit code 0x1). Will retry (2 tries left).
```

It looks like there is a security issue somewhere. Under which user it the Inno Setup process called? The one who is running Netbeans in my case?

**Comment by FibreFoX** [comment]
Hm ... thats strange, normally it should run as the same user as the maven-process is running. Maybe something else is different.

So you are saying when calling Maven from CLI directly, you don't get the problem, and only when calling maven from the IDE?

**Comment by McRender** [comment]
You are fast, man! I was saying that when calling the Inno Setup example application from within the inno setup compiler, the application (not java) gets signed without any problems. But when calling the .iss file from within the maven lifecycle for my own java fx application the access denied error get's thrown.

**Comment by McRender** [comment]
I'am not sure if this is Inno Setup or maven related :-(

**Comment by FibreFoX** [comment]
;) yes, I'm getting mails from new issues, so this is normal when I'm having my email-client open.

Don't know if there are some restrictions about the whole access issue ... maybe you can SEE it when using something like [ProcessExplorer](https://technet.microsoft.com/en-us/sysinternals/bb896653.aspx) with "User Name"-Column added ... can you try this?

**Comment by McRender** [comment]
Looks like it is running under the current logged in user. Hmmmm

**Comment by FibreFoX** [comment]
Have you tried to add quoting-signs for that URL inside the plugin-configuration?
> `/t http://timestamp.comodoca.com/authenticode`

**Comment by FibreFoX** [comment]
Just stupid question: did you try to call that command by hand yourself?

**Comment by McRender** [comment]
No luck with the quoting-signs

**Comment by FibreFoX** [comment]
Hm ... maybe your answer wasn't clear enough for me:
Does this happen when calling maven from CLI directly too? Or just from within the IDE?

**Comment by McRender** [comment]
Good point with the command by hand. Calling it results in the same error... Even when calling it in an adimistrator cmd. Looks like it has to do something with the security of the cerificate. Not a maven issue, sorry :-)

**Comment by McRender** [comment]
Ok got it. The folder permissions in the AppData folder where somehow limited to read only. This is an issue :-) Signtool.exe is not able to modify the executable in this folder.

**Comment by McRender** [comment]
Do you know where the build paths are set? Is this a maven parameter?

**Comment by FibreFoX** [comment]
Thats .... hard ... good catch tho.

**Comment by FibreFoX** [comment]
Let me check if this build-workspace thing can be changed ... but I'm not sure, because there is a lot of "Files.createTemp"-stuff is inside the bundlers ... but it really looks like some "special windows feature"-problem ;)

https://social.technet.microsoft.com/Forums/windowsserver/en-US/c7521b8d-44be-40cd-8482-e002d9edeb5f/signtool-this-app-cant-run-on-your-pc?forum=winserversecurity
http://stackoverflow.com/a/6677411/1961102
http://stackoverflow.com/questions/16063860/signtool-error-access-is-denied

**Comment by FibreFoX** [comment]
Please try this configuration:

```xml
<plugin>
    <artifactId>maven-antrun-plugin</artifactId>
        <executions>
        <execution>
            <id>create-jfx-build-space-folder</id>
            <phase>generate-sources</phase>
            <goals>
                <goal>run</goal>
            </goals>
            <configuration>
                <tasks>
                    <mkdir dir="target/jfx-build-space"/>
                </tasks>
            </configuration>
        </execution>
    </executions>
</plugin>
<plugin>
    <groupId>com.zenjava</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version><!-- your chosen version ;) --></version>
    <configuration>
        <!-- other stuff -->
        <bundleArguments>
            <!-- change "build space" for javapackager bundlers from TEMP -->
            <buildRoot>target/jfx-build-space</buildRoot>
        </bundleArguments>
    </configuration>
    <!-- your executions -->
</plugin>
```

Haven't tested this, but it should change it from the TMP-folder to somewhere below the normal maven-target-folder.

**Comment by McRender** [comment]
Same problem here... The created folder has the same locked attributes

![grafik](https://cloud.githubusercontent.com/assets/5795337/24304079/839b6f88-10b8-11e7-9f65-20eb18daa898.png)

**Comment by McRender** [comment]
Can we define the access permission when creating a folder with mkdir?

**Comment by FibreFoX** [comment]
;) I was already searching for this

http://ant.1045680.n5.nabble.com/Set-up-folder-permission-in-Windows-with-Ant-td1373124.html

>  You need to edit ACLs, which you can do by <exec>-ing CACLS

http://grokbase.com/p/ant/user/021kt8sbdg/changing-file-permissions-in-win32
> There's a DOS command "attrib" which does exactly that.

**Comment by FibreFoX** [comment]
As this is windows-specific, I will close this issue, but will help to find a working solution

**Comment by McRender** [comment]
I'am fine with that. It might be usefull in a FAQ or something like that.

**Comment by FibreFoX** [comment]
Just to double-check: it still does not work with that configuration-adjustments, still getting the same error about "Access denied"?

**Comment by McRender** [comment]
Yes you are right. It sill does not work when using your configuration. The created folder has the same access permission like the one in the AppFolder.

**Comment by FibreFoX** [comment]
So the other stuff works normally? Just wanted to know if this actually really works ;) because redirecting the build-workspace is cool sometimes, especially when developing on SSD+HDD-systems, where this can provide some speedup.

**Comment by McRender** [comment]
THe other stuff (building, packing etc) works normally. I'am not sure why it only happens with the code signing tool. It might be because I'am using the x64 edition. I'll check if this also happens with the x86 version. What I don't understand is, the building and packing also involves reading and writing and there it works.

**Comment by FibreFoX** [comment]
As this is a "normal" problem regarding windows world ... there are a lot of issues with AppData-access problems :/ im crossing fingers that you might find it

**Comment by McRender** [comment]
I'll post an update here if I find a solution. Let me know if you have an idea where to look next, otherwise thank you very much for spending your time on this one :-)

**Comment by McRender** [comment]
It looks like I finally have found a solution for my issue. If someone else runns in the same situation here is how I could manage to successfully sign my application with the signtool.exe:

To ensure that the exe file is writable add under package/windows/ the file MyProject-post-image.wsf:

```
<?xml version = "1.0" ?>
<package>
    <job id="CodeSign">
    <script language = "VBScript">
        <![CDATA[    
            'Set File as Normal. . .

            Dim objFSO, objFile
            Set objFSO = CreateObject("Scripting.FileSystemObject")
            Set objFile = objFSO.GetFile("MyProject\MyProject.exe")
            objFile.Attributes = 0

        ]]>
    </script>
    </job>
</package>
```
