### ISSUE TITLE
deb package gives me maintainer-address-malformed warning

### ISSUE THREAD

**Issue by mrlimbic** [javafx-maven-plugin/javafx-maven-plugin#289]
How do I set the maintainer correctly? 

I get the message when using the package "package is of bad quality".

It still works if you click ignore but looks bad for an installer to start that way.

**Comment by FibreFoX** [comment]
On what system are you installing your deb-file? Can you provide a project where I can reproduce this?

**Comment by mrlimbic** [comment]
Ubuntu 14 but am just upgrading to Ubuntu 16 to see if my app still runs on 16.

I think it is expecting an email address for the maintainer but it is showing my actual name as the 'problem'. I assume it got my name from the <developer> tag in the maven pom.

**Comment by mrlimbic** [comment]
I've just realised I was still using 8.7.0 plugin. Just changing it to 8.8.3 to see if that helps.

**Comment by mrlimbic** [comment]
It is now installing without complaint on Ubuntu 16 using 8.8.3 javafx plugin. Not sure whether Ubuntu 16 fixed it or upgrading the plugin did.

However it shows no icon, no useful info. Everything in the install process says 'unknown' and shows a jigsaw icon.

How can I make the installer show more info and make it show my icon? I'm used to doing this on Mac and Windows, but new to doing it on Ubuntu.

**Comment by FibreFoX** [comment]
So this is "just" some problem with the install manager of Ubuntu, right? I'm always willing to help users to generate their installers, even when not that much related to this plugin, but I do NEED some project where I can reproduce this.

**Comment by FibreFoX** [comment]
Closing this as [MCVE](http://stackoverflow.com/help/mcve) is missing.
