### ISSUE TITLE
Native bundles without runtime

### ISSUE THREAD

**Issue by AlexP11223** [javafx-maven-plugin/javafx-maven-plugin#293]
Is it possible to create native bundles (only app, not installer) without including JVM runtime?

If I simply delete the `runtime` directory, it gives error instead of using the system JVM,

**Comment by FibreFoX** [comment]
If you want to remove the JRE from the bundle, just add this to your plugin-configuration:
```xml
<bundleArguments>
    <runtime />
<bundleArguments>
```

The location of the JRE is included inside the generated `.cfg`-file, if there is `runtime=` the locally installed JRE will be used (you have to have JRE_HOME being set on Linux-systems).

To only have the native application without being bundled inside an installer, you can specify the bundler:
```xml
<plugin>
    <groupId>com.zenjava</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version>8.8.3</version>
    <configuration>
        <mainClass>com.zenjava.test.Main</mainClass>
        
        <!-- <bundler>mac.app</bundler> -->
        <!-- <bundler>linux.app</bundler> -->
        <bundler>windows.app</bundler>
    </configuration>
</plugin>
```
