### ISSUE TITLE
Skipping Certain Native Bundles on OSX

### ISSUE THREAD

**Issue by nartz** [javafx-maven-plugin/javafx-maven-plugin#295]
Hi - 

I'm doing a native build for a javafx app on OSX. I'd like to only build the DMG and:
- skip building the .app and .pkg
- skip the 'Mac App Store Ready Bundler' and 'WebStart JNLP Bundler'.

Presumably this can be done with possibly some bundle arguments?

Thank you!

**Comment by FibreFoX** [comment]
Just set the bundler ;)
```xml
<plugin>
    <groupId>com.zenjava</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version>8.8.3</version>
    <configuration>
        <vendor>YourCompany</vendor>
        <mainClass>your.package.with.Launcher</mainClass>
        
        <!-- this will only run Mac DMG bundler -->
        <bundler>dmg</bundler>
    </configuration>
</plugin>
```

**Comment by nartz** [comment]
Is there a place to see what the correct <bundle /> and <bundleArguments /> options to pass are? I see the oracle build docs themselves, but I'm asking more about this plugin.

Specifically:
Is there a way to specifically turn on multiple? i.e. DMG and APP? what is the recommended syntax?
What the right way to finely turn off Mac App Store Ready Bundler, etc?

Thank you!

**Comment by FibreFoX** [comment]
short answer: 😄 yes and no

long answer: Regarding the values for `<bundle />`: just call `mvn jfx:list-bundlers` to see the list for your local available bundlers. These IDs are the hard-coded values of the bundlers provided via the JDK, including their public visible tag-names for the `<bundleArguments />`-entries. A LOT of them are NON-PUBLIC, because the way they need to be registered isn't implemented in a well defined manner.  I often need to take a look into the source-code of these bundlers, and they even are changing from release to release. The tag-names are far from stable, that the reason they have to be provided via `<bundleArguments />` and are somewhat directly passed to the used bundler.

The plugin provides out-of-the-box two separate ways to execute the bundlers: calling ALL bundler (by omitting the `<bundle />` or call only ONE specific of them. But you can call the plugin multiple times with separate `<execution>`-entries within the `pom.xml`. You can collect all shared/generic configuration on the plugin-configuration level and add bundler-ids to the specific `<execution>`.

**Comment by nartz** [comment]
So as an example, I'm trying to only run the dmg and .app osx native build - I'm not sure what to put for the phase or goal of the excution, as well as where to actually put the <bundleArguments> configuration - do I need a separate <configuration> (possibly inherited) block in these? Is this `build-native` goal? I've left a few question marks below - thanks for your help.

<plugin>
    <groupId>com.zenjava</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version>8.8.3</version>
    <configuration>
        <appName>MyApp</appName>
        <mainClass>com.myCompany.myApp.Main</mainClass>
        <identifier>MyApp</identifier>
        <jfxMainAppJarName>myapp.jar</jfxMainAppJarName>
    </configuration>
    <executions>
        <execution>
            <id>create-jfxjar</id>
            <phase>package</phase>
            <goals>
                <goal>build-jar</goal>
            </goals>
        </execution>
        <execution>
            <id>build-osx-native-app</id>
            <phase>package???</phase>
            <goals>
                <goal>??</goal>
            </goals>
            <bundleArguments>??</bundleArguments>
        </execution>
        <execution>
            <id>build-osx-native-dmg</id>
            <phase>???</phase>
            <goals>
                <goal>??</goal>
            </goals>
            <bundleArguments>??</bundleArguments>
        </execution>
    </executions>
</plugin>

**Comment by FibreFoX** [comment]
Hi @nartz ,

I assume you never got in touch with that detail from maven ;) no problem, I can help here:
```xml
<plugin>
    <groupId>com.zenjava</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version>8.8.3</version>
    <configuration>
        <appName>MyApp</appName>
        <mainClass>com.myCompany.myApp.Main</mainClass>
        <identifier>MyApp</identifier>

        <!-- following is not required -->
        <jfxMainAppJarName>myapp.jar</jfxMainAppJarName>
    </configuration>
    <executions>
        <!-- generate the jfx-, others are depending on this -->
        <execution>
            <id>create-jfxjar</id>
            <phase>package</phase>
            <goals>
                <goal>build-jar</goal>
            </goals>
            <!-- no separate configuration-block, all of the above is inherited here -->
        </execution>
        
        <!-- generate native app -->
        <execution>
            <id>build-osx-native-app</id>
            <phase>package</phase>
            <goals>
                <goal>build-native</goal>
            </goals>
            <!-- all from above gets merged with following configuration (existing ones are overwritten) -->
            <configuration>
                <bundler>mac.app</bundler>
            </configuration>
        </execution>

        <!-- generate native app bundle (DMG) -->
        <execution>
            <id>build-osx-native-dmg</id>
            <phase>package</phase>
            <goals>
                <goal>build-native</goal>
            </goals>
            <!-- all from above gets merged with following configuration (existing ones are overwritten) -->
            <configuration>
                <bundler>dmg</bundler>
                <!-- example for making default to install on desktop instead of system wide -->
                <!-- for details please lookup inside com.oracle.tools.packager.mac.MacDmgBundler -->
                <bundleArguments>
                    <systemWide>false</systemWide>
                </bundleArguments>
            </configuration>
        </execution>
    </executions>
</plugin>
```

When calling `mvn package` all of them are build, but you might split them into separate build-profiles. Does this help?
