### ISSUE TITLE
where to find the log file if I use slf4j?

### ISSUE THREAD

**Issue by mfkenson** [javafx-maven-plugin/javafx-maven-plugin#297]
It only gave us a alert window: Oops! An unrecoverable error has occurred.....

I can see the log file if I run the code in my IDE inside the working directory. After compiling and packaging into exe, I cannot find the generated log file. Where is it?

**Comment by FibreFoX** [comment]
@mfkenson Can you post some project, where I can check? Might be something special inside your configuration.

**Comment by mfkenson** [comment]
i found the log file inside the "app" folder! thanks!
