### ISSUE TITLE
Native packages have all lower-case filenames

### ISSUE THREAD

**Issue by TMiguelT** [javafx-maven-plugin/javafx-maven-plugin#298]
If you set the `appName` config field in your `pom.xml` to a string with capital letters and then generate native packages, the generated files will have filenames that are all lower case.

For example:
```bash
$ grep appName < pom.xml
                    <appName>XMageLauncher</appName>
$ ls target/xmage*
target/xmagelauncher-0.3.8-1.x86_64.rpm  target/xmagelauncher-0.3.8.deb
```

Is this intentional, or a bug?

**Comment by FibreFoX** [comment]
Hm, interesting ... will check this, maybe it's something which was added in the last release...

**Comment by FibreFoX** [comment]
@TMiguelT what JDK are you using for this? which plugin-version are you using?

**Comment by TMiguelT** [comment]
Oh, I should have included that. For the plugin it's:
```xml
<groupId>com.zenjava</groupId>
<artifactId>javafx-maven-plugin</artifactId>
<version>8.8.3</version>
```

Java is:
```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.17.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by FibreFoX** [comment]
Looking at the code of the plugin, i can't see a problem, maybe the javapackager does some magic. Let me check this :)

**Comment by FibreFoX** [comment]
> target/xmagelauncher-0.3.8-1.x86_64.rpm  target/xmagelauncher-0.3.8.deb
this is very special ... do you do copy-stuff after calling the javafx-maven-plugin? normally this should reside inside `target/jfx/native`

**Comment by TMiguelT** [comment]
Yes, I set the output directory to `target` using `<nativeOutputDir>${project.build.directory}</nativeOutputDir>`

My full config is this:
```xml
<!--Package for Windows/Mac using the javafx bundler-->
            <plugin>
                <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>8.8.3</version>
                <configuration>
                    <appName>XMageLauncher</appName>
                    <nativeReleaseVersion>${version}</nativeReleaseVersion>
                    <nativeOutputDir>${project.build.directory}</nativeOutputDir>
                    <vendor>XMage</vendor>
                    <mainClass>com.xmage.launcher.XMageLauncher</mainClass>
                    <needShortcut>true</needShortcut>
                    <needMenu>true</needMenu>
                </configuration>
                <executions>
                    <execution>
                        <!-- required before build-native -->
                        <id>create-jfxjar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build-jar</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>create-native</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build-native</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by FibreFoX** [comment]
@TMiguelT can you reproduce this filename on Windows and Linux? Or just on one platform? Have you tried with OracleJDK instead of OpenJDK/OpenJFX?

**Comment by FibreFoX** [comment]
Regarding the filename of the RPM-installer, the openjfx-code does have some restriction too:
```
    // Fedora rules for package naming are used here
    // https://fedoraproject.org/wiki/Packaging:NamingGuidelines?rd=Packaging/NamingGuidelines
    //
    // all Fedora packages must be named using only the following ASCII characters.
    // These characters are displayed here:
    //
    // abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._+
    //
```

The RPM-bundler DOES lowercase that installer too, mostly to have linux-installers lowercased in general.

**Comment by FibreFoX** [comment]
Please keep in mind, that the native launcher will be upper-case, only the installer is lower-cased.

This is nothing I can handle here, as the official javapackager does this (because of the restrictions inside the comments above).

**Comment by FibreFoX** [comment]
For RPM-packages, there is a nice hack (untested):
```xml
<configuration>
    <appName>XMageLauncher</appName>
    <nativeReleaseVersion>${version}</nativeReleaseVersion>
    <nativeOutputDir>${project.build.directory}</nativeOutputDir>
    <vendor>XMage</vendor>
    <mainClass>com.xmage.launcher.XMageLauncher</mainClass>
    <needShortcut>true</needShortcut>
    <needMenu>true</needMenu>
    <bundleArguments>
        <linux.bundleName>XMageLauncher<linux.bundleName>
    </bundleArguments>
</configuration>
```

The "linux.bundleName" is normally gathered from "appName" when not set, which makes it lower-case. Inside the RPM-bundler, the regexp is case-insensitive, so this should work, because we are setting that special field explicitly.

**Comment by TMiguelT** [comment]
Ah yes, good point. When I run this on OSX or Windows I get `XMageLauncher-0.3.8.dmg` and `XMageLauncher-0.3.8.msi`. Strange that Fedora supports capital letters in RPMs but they actively convert the name to lower-case anyway. But you're right, this looks like it's `javapackager` behaviour.
