### ISSUE TITLE
Native mojo does not add 'deploy' directory

### ISSUE THREAD

**Issue by ennerf** [javafx-maven-plugin/javafx-maven-plugin#299]
**Problem**
When the native mojo is executed by itself (i.e. without the jar mojo), the deploy directory is not added and verbose output doesn't work. This prevents custom icons from being loaded.

After looking at the source code I found that the native mojo never calls to AbstractJfxToolsMojo::getPackagerLib() which adds the 'deploy' dir and sets up verbose logging.

**Use Case**
I'd like to use the packager with proguard output (copied via the copy-resources plugin) instead of using the default jar packaging.

**Workaround**
For now I've gotten around the issue by adding a dummy "build-web" target that does call getPackagerLib() before the native mojo gets executed.

**Comment by FibreFoX** [comment]
The "build-native"-MOJO is intended to be called after the "build-jar", the goal "jfx:native" even is registered to call the "jfx:jar"-goal. If you are using "build-native" without "build-jar", this is a problem of your project-setup. To use proguard, there is an existing example-project: https://github.com/javafx-maven-plugin/javafx-maven-plugin/tree/master/src/it/08-build-with-proguard

**Comment by ennerf** [comment]
Thanks. My problem was the code in the example always copied the dependencies into the lib folder instead of only using the shrunk uber-jar.

In case anyone else runs into the same issue: I got it to work with a combination of setting the proguard output to the default name (${project.build.finalName}.jar) and the properties below.

<updateExistingJar>true</updateExistingJar>
<skipCopyingDependencies>true</skipCopyingDependencies>
