### ISSUE TITLE
The files from META-INF (from the Spring jars) overwrite each other in executable jar

### ISSUE THREAD

**Issue by vannhi** [javafx-maven-plugin/javafx-maven-plugin#3]
Hello,
I'm trying to use your plugin in my project but I have the same issue in packaging as Maven Assembly described here: http://jira.codehaus.org/browse/MASSEMBLY-360

I have spring.handlers and spring.chemas in 2 dependencies spring-context.jar and spring-beans which get overwritten when packaging, so the application is unable to start.

Can you do something about it, like maven-shade-plugin does?

**Comment by FibreFoX** [comment]
closed, because plugin was reworked and no further feedback was provided (feel free to re-open or create a new issue)
