### ISSUE TITLE
Specifying Multiple additionalAppResources

### ISSUE THREAD

**Issue by nartz** [javafx-maven-plugin/javafx-maven-plugin#300]
Currently on OSX, we are wonddering if its possible to use multilple additionalAppResources for the build. The code seems to suggest 'no', but we are wondering if there may be other ways to achieve what we need.

We have tried to use maven-resources-plugin to copy everything into a single folder that is specified as additionalAppResources, however, maven-resources-plugin doesnt work when copying symlinks. Are there any suggested workarounds that are platform independent? We could use exec of course and provide a shell script, but thats not very platform independent =D

Thanks.

**Comment by FibreFoX** [comment]
I will consider making `additionalAppResources` a list of entries (this is a reasonable feature-request). About that symlink-thing: this will only work on filesystems that are supporting this, might not work on all build-systems.
