### ISSUE TITLE
installdirChooser does not work.

### ISSUE THREAD

**Issue by maxiwu** [javafx-maven-plugin/javafx-maven-plugin#302]
I tested with plugin version 8.6.0 and 8.8.3, with and without systemWide. All tests get same result.

			<plugin>
				<groupId>com.zenjava</groupId>
				<artifactId>javafx-maven-plugin</artifactId>
				<version>8.8.3</version>
				<configuration>
					<vendor></vendor>
					<mainClass>myapp.Main</mainClass>
					<verbose>true</verbose>
					<bundleArguments>
						<identifier>756603d3-3f6a-4f5f-8810-37e1552a5089</identifier>
						<systemWide>true</systemWide>
						<installdirChooser>true</installdirChooser>
					</bundleArguments>
				</configuration>

The temporary .iss still disabled the dir page
```ini
[Setup]
AppId={{756603d3-3f6a-4f5f-8810-37e1552a5089}}
AppName=myapp
AppVersion=1.0
AppVerName=
AppPublisher=test
AppComments=
AppCopyright=Copyright (C) 2017
;AppPublisherURL=http://java.com/
;AppSupportURL=http://java.com/
;AppUpdatesURL=http://java.com/
DefaultDirName={pf}\myapp
DisableStartupPrompt=Yes
DisableDirPage=Yes
DisableProgramGroupPage=Yes
DisableReadyPage=Yes
DisableFinishedPage=Yes
DisableWelcomePage=Yes
```

**Comment by FibreFoX** [comment]
This is no feature of the javafx-maven-plugin, but the used JDK. What version of the JDK are you using?

**Comment by FibreFoX** [comment]
https://stackoverflow.com/questions/28370655/javafx-self-installer-with-inno-setup-5-allow-user-to-change-install-directory/36933061?noredirect=1#comment78220011_36933061
