### ISSUE TITLE
How to add . to MANIFEST.MF classpath and put resources out?

### ISSUE THREAD

**Issue by Comup-X** [javafx-maven-plugin/javafx-maven-plugin#303]

**Comment by FibreFoX** [comment]
@Comup-X can you elaborate your question a bit? What is your use-case for this, what is your goal?

**Comment by Comup-X** [comment]
@FibreFoX 
sorry,my English is poor.
How to compile the project resource to the project jar dir not put in the jar file.
I have some ini file it can't open and write when it in the jar file.

**Comment by FibreFoX** [comment]
For adding files to the bundle, which do not reside inside the jfx-jar, use the `<additionalAppResources>`-parameter:
```xml
<configuration>
    <mainClass>your.mainclass</mainClass>
    <additionalAppResources>${project.basedir}/src/main/additionalFiles/</additionalAppResources>
</configuration>
```

**Comment by FibreFoX** [comment]
@Comup-X any progress ?
