### ISSUE TITLE
Unable to generate certificate

### ISSUE THREAD

**Issue by charlieH1** [javafx-maven-plugin/javafx-maven-plugin#306]
using the command 
`mvn jfx:generate-key-store -DcertDomain=com.myOrg -DcertState=UK -DcertCountry=UK`

Is producing an error saying that "The Property certDomain must be provided to generate a new certificate.

This is using version 8.8.3

**Comment by charlieH1** [comment]
Fix - update or provide docs 
`mvn jfx:generate-key-store -Djfx.certDomain=com.myOrg` etc

**Comment by FibreFoX** [comment]
This change was made due to the DromblerFX project, therefor the `jfx.`-prefix is required. Thanks for reporting this.

When creating a keystore via plugin-execution-block this should work normally.
