### ISSUE TITLE
Is it possible to swap the "Java Coffee Logo" during installation?

### ISSUE THREAD

**Issue by maxiwu** [javafx-maven-plugin/javafx-maven-plugin#307]
I have successfully swap the ico of the installer by installing Wix and put the ico file into /src/main/deploy/package/windows/.
I've also turn on the install directory option by <installdirChooser>true</installdirChooser>

I thought the logo on the page where the has to select the destination location will also be the new ico. But I was wrong, it is still the Java Coffee.

Could I replace that logo using this plugin?

**Comment by FibreFoX** [comment]
What "Java Coffee Logo" do you mean? The EXE-installer picks up the ICO-file for the installer-icon, and the tiny image in the upper corner uses some BMP-file: `{appName}-setup-icon.bmp`

Please set `<verbose>true</verbose>` to see what images are used. You should see something likes this:
```
  Config files are saved to C:\Users\youruser\AppData\Local\Temp\fxbundler7984932082881498593\windows. Use them to customize package
```

**Comment by maxiwu** [comment]
yes, I am referring to setup icon, it works, thank you for the nimble response.
