### ISSUE TITLE
Native launcher not working on x86 windows

### ISSUE THREAD

**Issue by stugal** [javafx-maven-plugin/javafx-maven-plugin#308]
Hello,

I'm having issues running the application via the native launcher on windows x86. On x64 everything works like a charm. I found a thread explaining how to build x86 distro on x64 system which i followed without success, the application simply doesn't start when launched via the app-name.exe, it works without problem when calling java -jar app-name-jfx.jar in the app folder.
I then tought it might be something weird due to the x86 build process on x64 OS so on my other machine i installed win 7 x86 and run the build there - no change, double clicking the .exe doesn't do anything while calling the jar file starts the application without a problem, is there any way to debug whats going on?

**Comment by FibreFoX** [comment]
Hi there, why that close/reopen?

To be honest, I'll close this, as this is no issue of the plugin. The documentation about this is clear: 

> **Package per target platform**
Self-contained application packages are platform-specific and can only be produced for the same system on which you build. To deliver self-contained application packages on Windows, Linux, and OS X, you must build your project on all three platforms.

https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html#JSDPG586

This "per platform" is meaning "bit achitecture" too. You need to use 32bit JDK for 32bit target and 64bit JDK for 64bit target. You could have found this:
https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/305
https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/81
