### ISSUE TITLE
Windows native bundle doesn't work if username/package contains non-latin symbols

### ISSUE THREAD

**Issue by Lexxxxik** [javafx-maven-plugin/javafx-maven-plugin#309]
Each time I build installer on the same machine where then trying to run.
For example:
Application works only if:
1. appName - latin only (MyApplication.exe)
2. Windows User name - latin only (admin)
and the final installed path is: C:\Users\\**admin**\AppData\Local\\**MyApplication**\MyApplication.exe

If any of points has non-latin symbols I recieve a lot off different messages like:
1. User name non-latin. Path:C:\Users\\**ЖЮЖЮ**\AppData\Local\AccessImport\AccessImport.exe
![image](https://user-images.githubusercontent.com/30318541/30865202-a2ca94e8-a2de-11e7-892e-4517b55f672a.png)
![image](https://user-images.githubusercontent.com/30318541/30865342-f91f0b3a-a2de-11e7-804f-0c6707013746.png)

2. appName - non-latin (ИмпортРежимов.exe). Path: C:\Users\\**ЖЮЖЮ**\AppData\Local\ИмпортРежимов\
![image](https://user-images.githubusercontent.com/30318541/30865486-68a2df36-a2df-11e7-9763-445441687e59.png)
![image](https://user-images.githubusercontent.com/30318541/30865496-7318757a-a2df-11e7-9de7-49cee807df80.png)

Is it possible to fix at least working with non-latin windows users? Actually I can't ask all my users to recreate their window account with latin symbols only.

**Comment by FibreFoX** [comment]
Hi there, this is the fault of the JDK and nothing I can do about. There is another related issue already here: #209

[launcher crashes if started with non english arguments](https://bugs.openjdk.java.net/browse/JDK-8133034)
[Generated bundle is not executable when main class contains unicode](https://bugs.openjdk.java.net/browse/JDK-8138642)

Nothing I can do about, sorry :(

**Comment by Lexxxxik** [comment]
Ohhh, bad news
Is there any flag to install application not to user folder, but to Program Files with admin privs?

**Comment by FibreFoX** [comment]
Oh, thats possible! Just set this inside your plugin-configuration:
```xml
<configuration>
    ...
    <bundleArguments>
        <installdirChooser>true</installdirChooser>
    </bundleArguments>
    ...
</configuration>
```

**Comment by Lexxxxik** [comment]
Thanks a lot.
I tried to google whole list of arguments bundleArguments, but nothing
Could you please give a link for all plugin-configurations settings?

**Comment by FibreFoX** [comment]
https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/89#issuecomment-327702187

For the JDK 8 I always looked into the sourcecode of each bundler, but with JDK 9 these values are documented. Please note, that this plugin is not JDK9 ready yet.
