### ISSUE TITLE
Create a native javafx app with Inno Setup and Maven

### ISSUE THREAD

**Issue by SylvainCharroy** [javafx-maven-plugin/javafx-maven-plugin#31]
I've a little JavaFX app and I use Maven for managing the dependencies thanks to the javafx-maven-plugin.

I want to use the option who will build a native installer based on the settings (mvn jfx:build-native) using InnoSetup (on windows)

That's work pretty well but I can't find where I can specify all the Inno Setup options (like those visible here : http://www.jrsoftware.org/ishelp/index.php?topic=setup_setupiconfile). Did I have to add something on my pom ? Did I have to create a .iss file ? If yes, how to specify the link to this file ?

Any idea ?

**Comment by FibreFoX** [comment]
the plugin was reworked since this issue, goal is now ```jfx:native```
