### ISSUE TITLE
Config Inno directory

### ISSUE THREAD

**Issue by waideman** [javafx-maven-plugin/javafx-maven-plugin#310]
I want my build as self contained and I don't want to install items such as Inno mannually. I'm thinking about add Inno files in my repository and compile my script in this directory.

Is there any way to set Inno directory on plugin instead of just look for inno in PATH?

**Comment by FibreFoX** [comment]
The underlying javapackager does several attempts to find InnoSetup:
http://hg.openjdk.java.net/openjfx/8u-dev/rt/file/aefb29b5a599/modules/fxpackager/src/main/java/com/oracle/tools/packager/windows/WinExeBundler.java#l103

By setting some additional `<bundleArguments>`, you might reach what you want. Just set `<win.exe.iscc.exe>` to the exe-path, but I strongly disadvise using that attempt, there might be problems with the tool itself.

**Comment by FibreFoX** [comment]
@waideman any feedback?
