### ISSUE TITLE
Exclude resources by OS target

### ISSUE THREAD

**Issue by dsardari** [javafx-maven-plugin/javafx-maven-plugin#315]
I'm inheriting a project that uses this plugin and was wondering if there's a way to exclude resources based on the OS target.

For example, we rely on a native dependency that will be a dll, so or dylib based on the OS target. It would be useful if we could exclude all unrelated dependencies when building.

Is this possible through this plugin or is there a feature on maven you could point me to process before the plugin stage?

**Comment by dsardari** [comment]
Yeah, that's pretty much the same solution I just came across. Seems like that'll do the trick. Thanks!

**Comment by FibreFoX** [comment]
If it happens that you can NOT use maven-profiles, there is a rather undocumented property inside the `create-jar`-mojo:
https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/6bbb98adca0763979db0e53e566ed3129727f0e6/src/main/java/com/zenjava/javafx/maven/plugin/JarMojo.java#L117

```xml
<plugin>
    <groupId>com.zenjava</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version>8.8.3</version>
    <configuration>
        <classpathExcludes>
            <dependency>
                <groupId>someGroupId</groupId>
                <artifactId>someArtifactId</artifactId>
            </dependency>
        </classpathExcludes>

        <!-- normal stuff -->
        <vendor>YourCompany</vendor>
        <mainClass>your.package.with.Launcher</mainClass>
    </configuration>
</plugin>
```

The idea was to create an application package where some libs are located at some special location, which are getting copied by some different maven-plugin. But in your case I would rely on maven-profiles ;)
