### ISSUE TITLE
Support for PKG post-install scripts

### ISSUE THREAD

**Issue by chrisrohr** [javafx-maven-plugin/javafx-maven-plugin#317]
Hi,

I was wondering if there was a way through the plugin configuration or folder structure of including Mac post-install scripts for the PKG bundler?  I wasn't sure how to find out what options were given to the pkgbuild command by javapackager.

Thank you in advance and I apologize if I missed a previous answer or piece of documentation.

**Comment by FibreFoX** [comment]
Hi @chrisrohr, I will take a look at the PKG-bundler if this is supported. As the javafx-maven-plugin is just a wrapper for the javapackager, it depends on the JDK. Will head back to you with information about this.

**Comment by FibreFoX** [comment]
As far as I can see, you have to put some file at this location: `src/main/deploy/package/macosx/[APP_NAME]-post-image.sh`.

**Comment by chrisrohr** [comment]
Thank you for taking a look.

**Comment by McRender** [comment]
Hi there,

Did you manage to get this working? As far as I understand this `[APP_NAME]-post-image.sh` script, it only runs after you have created the DMG file with the javapackager. So you can change for example the content of the DMG file for localization... I would like to know if there is a possibility to add a `post-install` script so I can copy some files to the user > library > application support folder after the application has been installed. There are several ways to do that with a installer packages .pkg file but I am not sure how to combine this directly with the javapackager so I don't have to unpack and repack the .pkg again.

Would love to here from you

**Comment by chrisrohr** [comment]
@McRender unfortunately I went in a different direction.  I was able to use this plugin to generate my executables, but I used another install builder to generate my installers.

**Comment by McRender** [comment]
@chrisrohr  thanks you for the quick response. I've just checked out the [Packages App](http://s.sudre.free.fr/Software/Packages/about.html) which is able to take the output generated by the` javafx-maven-plugin` and is capable of running pre- and postflight scripts. I mean the `javapackager` is using the same toolchain as the Packages App is so there must be a way to hand those scripts over via `javafx-maven-plugin`. I'll have a deeper look if I find the time to. Solutions or hints are welcome

**Comment by McRender** [comment]
@FibreFoX I'll give it a try, thanks. Do you know if there is a naming convention how to name those scripts or how does the packager takes those files as input? Could you point me to a good documentation of the packager itself?

**Comment by FibreFoX** [comment]
@McRender atually there is no other documentation than the packager source code itself: http://hg.openjdk.java.net/openjfx/8u-dev/rt/file/e47cf0f75de3/modules/fxpackager/src/main/java/com/oracle/tools/packager/mac/MacPkgBundler.java#l67

These filenames are hardcoded, but they should appear inside the build-log when having `verbose` enabled.

**Comment by FibreFoX** [comment]
@McRender 
;) did you name it `postinstall.sh` or `postinstall` (without `.sh`)?

**Comment by McRender** [comment]
Tried both ;-)
