### ISSUE TITLE
jvmArgs are not set

### ISSUE THREAD

**Issue by Enigo** [javafx-maven-plugin/javafx-maven-plugin#319]
Hello there! Trying to add jvmArgs but it seems that there are not set.

I have configuration like this:
```
<plugin>
    <groupId>com.zenjava</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version>8.8.3</version>
    <configuration>
        <mainClass>com.analyzer.Launcher</mainClass>
        <jvmArgs>
            <jvmArg>-Xmx2g</jvmArg>
            <jvmArg>-Djava.net.preferIPv4Stack=true</jvmArg>
        </jvmArgs>
    </configuration>
</plugin>
```
Then in the main method I'm trying to get'em like this:
```
    public static void main(String[] args) {
       RuntimeMXBean runtimeMxBean = ManagementFactory.getRuntimeMXBean();
       List<String> arguments = runtimeMxBean.getInputArguments();

       log.info(System.getProperty("java.vm.name"));
       log.info(System.getProperty("java.net.preferIPv4Stack"));
       log.info(arguments.toString());
       launch(args);
    }
```
And the output is:
```
2017-12-23 19:11:32,253 INFO  com.analyzer.Launcher - Java HotSpot(TM) 64-Bit Server VM
2017-12-23 19:11:32,254 INFO  com.analyzer.Launcher - 
2017-12-23 19:11:32,254 INFO  com.analyzer.Launcher - [-Dfile.encoding=windows-1251]
```

To build the jar file I perform maven clean, install and then jfx jar.

What do I miss here?

**Comment by FibreFoX** [comment]
Hi there, these JVM-arguments are stored when having native launchers, not the jar-file itself. Are you trying to execute the generated jfx-jar, or the jfx native launcher?

**Comment by Enigo** [comment]
@FibreFoX, I'm trying to execute the jar located in target/jfx/app.

**Comment by FibreFoX** [comment]
@Enigo thats exactly what I thought, the `<jvmArgs>` are for the native launcher only, this means when running your JFX-JAR-file, the parameters are not "included", as you are expected to launche the jar with these parameters yourself.

Did you expect `<jvmArgs>` to work for the jfx-jar?

**Comment by Enigo** [comment]
@FibreFoX, well, actually I did) 
Just, FYI, my use-case is quite simple: I use the plugin to build executable jar file that I later send to other colleagues.
For now I ended up with .bat file that simply runs the jfx-jar file with `jvmArgs`
Generally speaking, can this be implemented for jfx-jar file as well?

**Comment by FibreFoX** [comment]
No, this is not possible, it would require to re-spawn the JVM with the additional JVM-arguments (Chicken-and-egg dilemma). These arguments are only for the native launcher, because they are creating their own instance of the JVM, including these parameters.
