### ISSUE TITLE
A mix of Windows and Linux directory format : Could not find artifact javafx-packager:javafx-packager 

### ISSUE THREAD

**Issue by refactormyself** [javafx-maven-plugin/javafx-maven-plugin#324]
I am trying to run a JavaFx app on Eclipse, I am getting this error. I noticed the packager could not be found maybe because of this mixture of "\" and "/" : C:\Program Files\Java\jre1.8.0_151/../lib/ant-javafx.jar

>  Failed to execute goal com.zenjava:javafx-maven-plugin:8.8.3:jar (default-cli) on project JavaFxMaven: Execution default-cli of goal com.zenjava:javafx-maven-plugin:8.8.3:jar failed: Plugin com.zenjava:javafx-maven-plugin:8.8.3 or one of its dependencies could not be resolved: Could not find artifact javafx-packager:javafx-packager:jar:1.8.0_20 at specified path C:\Program Files\Java\jre1.8.0_151/../lib/ant-javafx.jar -> [Help 1]
[ERROR]

**Comment by FibreFoX** [comment]
Providing any path within maven should be provided using linux-style slashes. You need to make sure having JDK 8 with at least Update 40 being installed, JDK 9 support is not yet finished (but it should work with JDK 10, at least from source-code it's fixed).

But as you are required to have set the JDK inside of eclipse, this is some misconfiguration of your IDE (eclipse uses the JRE by default, not the JDK).

**Comment by silverzag** [comment]
I have the same troubleshooting even if all my system variables was correctly configured (JAVA_HOME, M2, M2_HOME)
![VariablesSys](https://user-images.githubusercontent.com/48753944/54680689-d3ff7080-4b0a-11e9-9bf6-7cb36de8140f.png)
What misconfiguration I have!!!
