### ISSUE TITLE
How to exclude resource files?

### ISSUE THREAD

**Issue by rwalter** [javafx-maven-plugin/javafx-maven-plugin#325]
How can certain resource files (src/main/resources) be excluded from being included into the created jar archive?

When I build a stand alone version of my Java project the resulting app jar (jfx/app/<my program>.jar) contains all resource file (src/main/resources).

**Comment by FibreFoX** [comment]
Thats the convention of normal maven jar projects, nothing specific from the javafx-maven-plugin.

https://stackoverflow.com/a/5663653/1961102

**Comment by rwalter** [comment]
Thank you a lot. By excluding the files via <resources> tag I could prevent javafx-maven-plugin from including the files. However, as far as I understand, these exclusions are set for all plugins. Is there any way to exclude files for javafx-maven-plugin only?

**Comment by FibreFoX** [comment]
With "tag" you ment the XML-tags, right?

Excluding resources only when creating the javafx-bundle is possible by creating maven-profiles, where you exclude that files only when running that profile. But this is nothing specific to the javafx-maven-plugin, there is no way for excluding single files from the generated jfx-jar.

**Comment by rwalter** [comment]
> With "tag" you ment the XML-tags, right?

Yes, right.

Thank you again for your fast response.
