### ISSUE TITLE
How to include WixUIExtension

### ISSUE THREAD

**Issue by hmkhaos** [javafx-maven-plugin/javafx-maven-plugin#328]
Dear creator of javafx-maven-plugin,

When I am using javafx-maven-plugin with WIX toolset, I have some problems with using WixUIExtension, after setting verbose to true, I can see the following command, 

Running [C:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe, -nologo, -spdb, -sice:60, C:\cygwin\tmp\fxbundler6789653381051801336\tmp\myApplicationName.wixobj, -ext, WixUtilExtension, -out,  \target\jfx\native\myApplicationName-1.0.msi] in C:\cygwin\tmp\fxbundler6789653381051801336\images\win-msi.image\myApplicationName

it doesn't include WixUIExtension in -ext, is there a way that i can make it happen? And why WixUtilExtension is included by default?

Many thanks!!

**Comment by FibreFoX** [comment]
;) the original creator isn't the maintainer of this project anymore, but I think as a maintainer I can answer too.

Please have a look at this comment: https://github.com/FibreFoX/javafx-gradle-plugin/issues/101#issuecomment-364536554

If you have some license configured, or set the "installation directory chooser" to be used, this plugin is getting added.

```xml
<configuration>
    <bundleArguments>
        <installdirChooser>true</installdirChooser>
    </bundleArguments>
</configuration>
```

**Comment by hmkhaos** [comment]
Dear Danny,
It works perfectly for me. Thanks a lot!! Really appreciate your help!! :)

> 
           <plugin>
                <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>8.1.4</version>
                <configuration>
                    <mainClass>${javafx.application.class}</mainClass>
                    <verbose>true</verbose>
                    <additionalAppResources>keys</additionalAppResources>
                    <jvmArgs>
                        <argument>-Dlogback.configurationFile=logbackFile.xml</argument>
                    </jvmArgs>
                    <bundleArguments>
                        <installdirChooser>true</installdirChooser>
                    </bundleArguments>
                </configuration>
            </plugin>
