### ISSUE TITLE
Code Signing

### ISSUE THREAD

**Issue by danielpeintner** [javafx-maven-plugin/javafx-maven-plugin#331]
Hi,

I have a digicert certificate and I can sign jars on the command shell as suggested in https://www.digicert.com/code-signing/java-code-signing-guide.htm by using the following command.

`jarsigner -tsa http://timestamp.digicert.com -keystore c:\path\to\your\keystore.jks -storepass YourPassword c:\path\to\your\file.jar YourAlias`

I tried to use the same input for javafx-maven-plugin but I fail. Somehow signing does not kick in.

```
			<plugin>
				<groupId>com.zenjava</groupId>
				<artifactId>javafx-maven-plugin</artifactId>
				<version>8.8.3</version>
				<configuration>
					<appName>myFOO</appName>
					<mainClass>MyFooApp</mainClass>
					<!-- Code Signing -->
					<noBlobSigning>true</noBlobSigning> <!-- this setting is required for the new "jarsigner"-feature -->
					<verbose>true</verbose>
					<keyStoreAlias>server</keyStoreAlias>
					<keyStorePassword>XXXXXX</keyStorePassword>
					<additionalJarsignerParameters>
						<additionalJarsignerParameter>-keystore</additionalJarsignerParameter>
						<additionalJarsignerParameter>foo.jks</additionalJarsignerParameter>
						<additionalJarsignerParameter>-tsa</additionalJarsignerParameter>
						<additionalJarsignerParameter>http://timestamp.digicert.com</additionalJarsignerParameter>
					</additionalJarsignerParameters>
				</configuration>
			</plugin>
```

I looked at https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/260 or https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/291 or https://stackoverflow.com/questions/43594938/maven-jnlp-creation-with-ev-code-signing.

Are there any other requirements in the POM so that signing kicks in. I tried to look at the "verbose" log but there is even no mentioning about signing (or signing issues).

Thanks for you help,

-- Daniel

**Comment by FibreFoX** [comment]
Can you try with this configuration?
```xml
<plugin>
    <groupId>com.zenjava</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version>8.8.3</version>
    <configuration>
        <appName>myFOO</appName>
        <mainClass>MyFooApp</mainClass>
        <noBlobSigning>true</noBlobSigning>
        <verbose>true</verbose>
        <keyStoreAlias>server</keyStoreAlias>
        <keyStorePassword>XXXXXX</keyStorePassword>
        
        <!-- keystores are project-relevant, it defaults to "src/main/deploy/keystore.jks", please make sure your cert is in there -->
        <keyStore>foo.jks</keyStore>
        
        <!-- the following is intended for """""additional""""" parameters -->
        <!-- the following are not required: storepass, keypass, keystore-->
        <additionalJarsignerParameters>
            <additionalJarsignerParameter>-tsa</additionalJarsignerParameter>
            <additionalJarsignerParameter>http://timestamp.digicert.com</additionalJarsignerParameter>
        </additionalJarsignerParameters>
    </configuration>
</plugin>
```

Signing JARs (using jarsigner) only gets done when creating a native bundle, not just the jar-bundle (means `mvn jfx:jar` does not sign, only `mvn jfx:native`, which might be a stupid idea I had while implementing this, sorry)

**Comment by FibreFoX** [comment]
That sounds tricky ... can you create some reproducable project for this? Maybe it's something trivial I'm just overlooking here.

**Comment by danielpeintner** [comment]
Sure! I pushed a sample project without any jks file to https://github.com/danielpeintner/JavaSignTest.

Attached also the verbose log I get on Windows7 64bit.
[log.txt](https://github.com/javafx-maven-plugin/javafx-maven-plugin/files/1838504/log.txt)

Thanks for looking into that issue!

**Comment by danielpeintner** [comment]
Some more updates on my side.

I did look into the plugin code and the entry point for jarsigner seems to be [`applyWorkaroundsAfterBundling`](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/976875eca2572118adbf620261de16c1709c4175/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L762) where one can find some mentioning of jarsigner (see https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/976875eca2572118adbf620261de16c1709c4175/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L799-L815)

Anyhow, debugging the code showed that even before that in `if( "jnlp".equals(currentRunningBundlerID) ){` it does not step in given that `currentRunningBundlerID== "windows.app"`.
Moreover, the next `if` statements do not kick in either.

I did try resolve the issues but did not succeed. I hope this information helps.

**Comment by FibreFoX** [comment]
Wait a moment, are you trying to sign jar-files which are going to be used when having native launchers? This happens a lot and I'm missing to see the point of signing the jar-files when running "*.app"-bundlers. What are the advantages of having signed jar-files when having some EXE launcher which does not care about signed JAR-files?

Is there any advantage of having signed jar-files?

**Comment by danielpeintner** [comment]
> are you trying to sign jar-files which are going to be used when having native launchers? 

Correct. My use-case is to share the outcome of `target\jfx\app` (without the EXE launcher).

Anyhow, I can also imagine it to be a valid use case for the installer in `target\jfx\native`. Let's assume the installer is run and the content unpacked it is still useful to have _signed_ Jars.

Not sure if that makes sense to you. Is there any (technical) reason why signing should be limited to Java Web Start?

**Comment by FibreFoX** [comment]
The reason for this limitation is the type of plugin this is: just a wrapper around the javapackager. The original javapackager itself just had signing jar-files for JNLP (as far as I understood the source-code), which made me not implement a generic way.

Technically the chain-of-trustability is incomplete when doing native launcher-stuff and installers (which was the mainpoint of javapackager and this plugin).

I'm already tinkering some (hopefully) alternative to this plugin, as the focus of the javafx-maven-plugin is to be a wrapper. I hope to have more insights on this very soon.

**Comment by danielpeintner** [comment]
Thanks for your insights! I did use `javapackager` for standalones/runnable fat Jars and it worked just fine for me...  

Anyhow, thanks again and keep us informed about the focus change (or alternative plugin)!
NB: Feel free to close this issue...
