### ISSUE TITLE
Launch on windows startup

### ISSUE THREAD

**Issue by kaisteel** [javafx-maven-plugin/javafx-maven-plugin#335]
I want to make the application launch on Windows startup to do so I came across [this](https://stackoverflow.com/a/13246430/4800126) SO question.
How can I use this configuration in the plugin?
Also what other tags I can pass under `<bundleArguements>` tag.
Lastly, is there a way I can attach an external script of Inno Setup to this maven plugin.

**Comment by FibreFoX** [comment]
Please enable `<verbose>true</verbose>` to see further output, the location of the generated InnoSetup-configuration will be printed out. To "override" the used default one, you can place it in this folder: `src/main/deploy/packager/windows/{appName}.iss`

**Comment by FibreFoX** [comment]
Further configuration belongs to using InnoSetup, not this plugin.
