### ISSUE TITLE
Is it possible to internationalize the installation package? 

### ISSUE THREAD

**Issue by JRSofty** [javafx-maven-plugin/javafx-maven-plugin#338]
So using the plugin configurations, an installer file is created (.exe type file). When I run this installer all of the dialogs are in English. Is there a way to configure them to use German, or do I have to create my own installer files? This is not very clearly explained in the documentation for the plugin only saying that InnoSetup or WiX is required but not how to perform any modifications.

**Comment by FibreFoX** [comment]
The tools `InnoSetup` and `WiX Toolkit` are used by the underlying `javapackager` to create EXE- and MSI-installers. These tools require their own project-files to create these installers. As part of the creation, the java-application resources are used aside of that project-file. Just making sure to have these details being kept in mind ;) as they are not really good described anywhere than the source-code.

Now getting to the solution of your question:
If you are setting <verbose> to true, you will see some output from the bundler, where you can find some files for further processing (these files will be removed in the case `<verbose>` is not set as it defaults to `false`).

As stated by the website http://www.jrsoftware.org/ishelp/topic_languagessection.htm you are required to change the corresponding value, you might need some additional files from the vendor itself: http://www.jrsoftware.org/files/istrans/

You probably will end up having this:

```ini
[Languages]
Name: "en"; MessagesFile: "compiler:Default.isl"
Name: "de"; MessagesFile: "compiler:Languages/German.isl"
```

Now the real important part about **"how do I use this with the plugin"**! You will be shown some path after building your installer with some path, something like this:

```
Successful compile (7,719 sec). Resulting Setup program filename is: C:\...\target\jfx\native\application-1.0.exe
Installer (.exe) saved to: C:\....\target\jfx\native
Config files are saved to C:\....\Local\Temp\fxbundler3948695136808469560\windows.
Use them to customize package.
```

If you go to that folder, you will see all override-able files, which are required so be copied to some special location inside your project: `src/main/deploy/package/windows`
When everything went right, your verbose output will change from

```
Using default package resource [Inno Setup project file]  (add package/windows/application.iss to the class path to customize)
```
to

```
Using custom package resource [Inno Setup project file]  (loaded from package/windows/application.iss)
```

There is only one "problem" with that approach: some of the values are fixed, changing something like GUIDs or AppId or even the application-name will not work with that file. To have this working, you are required to use a different file stored inside the JDK you are using:
`%java_home%\lib\ant-javafx.jar:\com\oracle\tools\packager\windows\template.iss`

Just open that JAR-file with any ZIP-compatible packager to extract that file in case you need to take a peek about the actual template-file, and to have an idea about which parts you can copy-paste from there. The used "custom file" in the "src/main/deploy/package/windows" folder fill be processed and all placeholder are replaced "as normal".

For MSI-installers I haven't looked into it, but it might not be possible as there is no special way for adding parameters to the `candle.exe` file, as described on the documentation: http://wixtoolset.org/documentation/manual/v3/howtos/ui_and_localization/build_a_localized_version.html

**Comment by FibreFoX** [comment]
@JRSofty which JDK are you using? Maybe you should open another issue on this project, sometimes it's just a simple thing which is not included inside the package. Normal way to find out is to launch the exe-launcher created by the `jfx:native` goal, if that isn't working, try to call `java -jar yourApp-jfx.jar` inside the app-folder, sometimes some jar-files are missing.

**Comment by JRSofty** [comment]
@FibreFoX The problem may be something with the bundler itself, but I haven't found the evidence. I'm using JDK 1.8.0_152. The jar files seem to be there, but the launching executable doesn't even get to them as it fails to find the jvm.dll even though the path seems correct. 

I've since handled the bundling issue using a couple of different plugins, and I only need to create the installer which now that I'm not using the JavaFX bundler I have a little more control on the language.

**Comment by FibreFoX** [comment]
Hm, that problem sounds familiar, please open another issue with a bit of your plugin-configuration, just in case you want to use this maven-plugin ;)
