### ISSUE TITLE
Allow adding of induvidual Manifest Entries

### ISSUE THREAD

**Issue by og0815** [javafx-maven-plugin/javafx-maven-plugin#34]
Hi,

it would be nice to have the option to add individual entries to the generated Manifest.
(Like in the maven-jar-plugin) 
e.g.:
Something like this
```XML
<plugin>
  <artifactId>maven-jar-plugin</artifactId>
  <configuration>
    <archive>
      <manifestEntries>
        <SplashScreen-Image>splash.png</SplashScreen-Image>
      </manifestEntries>
    </archive>
  </configuration>
</plugin>
```
Would produce a mainfest entry of:
SplashScreen-Image: splash.png

I asume it is possible to do with
com.sun.javafx.tools.packager.CreateJarParams.setManifestAttrs(Map<String, String> manifestAttrs)

If I get some time the weekend I might supply a patch

**Comment by FibreFoX** [comment]
Fixed with PR https://github.com/javafx-maven-plugin/javafx-maven-plugin/pull/36
