### ISSUE TITLE
How to change the default installation path

### ISSUE THREAD

**Issue by fangdong116** [javafx-maven-plugin/javafx-maven-plugin#340]
For windows, the default path is C:\Users\Administrator.XKZCNO\AppData\Local\{appName}. How to change it?

**Comment by FibreFoX** [comment]
Duplicate, please use the SEARCH next time :) there are a lot of answers already here, including comments and code.
https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/89#issuecomment-327647348

```
<configuration>
    ...
    <bundleArguments>
        <installdirChooser>true</installdirChooser>
    </bundleArguments>
    ...
</configuration>
```
