### ISSUE TITLE
appName issue

### ISSUE THREAD

**Issue by algakzru** [javafx-maven-plugin/javafx-maven-plugin#344]
```
<!-- my project version -->

<version>1.0.1-SNAPSHOT-2</version>

<!-- javafx-maven-plugin config -->

<plugin>
	<groupId>com.zenjava</groupId>
	<artifactId>javafx-maven-plugin</artifactId>
	<version>8.8.3</version>
	<configuration>
		<mainClass>com.trackmeeasy.cloudprint.MainApplication</mainClass>
		<verbose>true</verbose>
		<appName>Cloud Print Service</appName>
		<nativeReleaseVersion>${project.version}</nativeReleaseVersion>
	</configuration>
</plugin>
```

For some reason the above `pom.xml ` produces native bundle with filename 

> Cloud Print Service-1.0.12.exe

 instead of

>  Cloud Print Service-1.0.1-SNAPSHOT-2.exe

how can I fix it ?

**Comment by FibreFoX** [comment]
Oh, this is done because of the requirements of "nativeReleaseVersion", some bundlers do not like other stuff like SemVer. This is no bug, it is intended behaviour, but clearly in your case confusing. All non-numbers are stripped, which means `1-SNAPSHOT-2` is converted to `12`.
