### ISSUE TITLE
No documentation available

### ISSUE THREAD

**Issue by xadagaras** [javafx-maven-plugin/javafx-maven-plugin#349]
Hi,

you say in the readme, that we should go to http://javafx-maven-plugin.github.io for reading how to configure the plugin. Sadly this page returns a 404 Not Found.

Can you please provide some resources for how we can configure the plugin?

Thanks

Daniel

**Comment by ribasco** [comment]
I was also looking for the docs, until now the link is broken. Is this project dead?

**Comment by Lonzak** [comment]
No Problem the interactive version is still available here:
http://web.archive.org/web/20170926160512/http://javafx-maven-plugin.github.io:80/

Note: For the initial load of the page I had to wait several minutes but it is worth to wait...

**Comment by FibreFoX** [comment]
The old configurator got "revived": https://zenjava.net/javafx-maven-plugin/
