### ISSUE TITLE
JavaFX-Fallback-Class

### ISSUE THREAD

**Issue by hexid** [javafx-maven-plugin/javafx-maven-plugin#35]
Currently, I can't find any way of setting a fallback class.

This could be accomplished with `CreateJarParams.setFallback(String fallback)`

Also, the following should be noted from the source of `PackagerLib.packageAsJar(CreateJarParams createJarParams)`:

    //Default fallback class uses "private" interface to
    // get additional error paramters. Do not add it to manifest
    // explicitly to avoid treating it as custom
    if (createJarParams.fallbackClass != null && 
            !createJarParams.defaultFallbackApp.equals(
            createJarParams.fallbackClass)) {
        attr.put(new Attributes.Name("JavaFX-Fallback-Class"), 
                createJarParams.fallbackClass);
    }

**Comment by FibreFoX** [comment]
Already fixed with PR https://github.com/javafx-maven-plugin/javafx-maven-plugin/pull/37
