### ISSUE TITLE
Building with Openjdk

### ISSUE THREAD

**Issue by rahulvsin** [javafx-maven-plugin/javafx-maven-plugin#351]
Hi 
I'am using openjdk-1.8.0 for creating native bundle.  After running mvn jfx:native it creates all the required files in target along with .exe file. But I couldn't run the .exe file. It is not just starting.
Previously I was using oracle JDK 1.8 for creating the same. But It worked fine.
Can you please help me on this. Thank you

**Comment by FibreFoX** [comment]
Will have to take a look into OpenJDK-support on Windows.
