### ISSUE TITLE
Could not find artifact javafx-packager:java javafx.jar

### ISSUE THREAD

**Issue by 743834110** [javafx-maven-plugin/javafx-maven-plugin#358]
Hello, there was an error occured when running with jfx:native, it likes that:
>[INFO] BUILD FAILURE
[INFO] ---------------------------------------------------
[INFO] Total time: 2.406 s
[INFO] Finished at: 2018-09-17T15:10:52+08:00
[INFO] ---------------------------------------------------
[ERROR] Failed to execute goal com.zenjava:javafx-maven-pl
.zenjava:javafx-maven-plugin:8.8.3:jar failed: Plugin com.
 be resolved: Could not find artifact javafx-packager:java
javafx.jar -> [Help 1]

I'm new for JavaFx, How can I do for it?

**Comment by FibreFoX** [comment]
@743834110 which JDK are you using?

**Comment by 743834110** [comment]
@FibreFoX JDK1.8U144

**Comment by FibreFoX** [comment]
@743834110 please make sure maven uses the correct location by calling `mvn -v`, when having something like `C:\Program Files (x86)\Java\jdk1.8.0_144\jre`. Do you have several JDKs installed? Are you working on Windows, Linux or MacOS?

**Comment by 743834110** [comment]
I have installed serveral JDKs and I am working on Win 7.
When I call `mvn -v` ,  it shows 
![1](https://user-images.githubusercontent.com/30767963/45626691-b18c8c00-bac2-11e8-9969-411f6bdd360e.png)

**Comment by FibreFoX** [comment]
Ah, I see the problem ;) you missed to set `JAVA_HOME` to the JDK-location. When having the environment variable set correctly, this issue will resolve.

**Comment by 743834110** [comment]
It's maybe some mistakes. I think I have
 setted enviroment correctly.
![_20180917221509](https://user-images.githubusercontent.com/30767963/45628828-7d679a00-bac7-11e8-8dd3-8db07f64bd8d.png)
![_20180917221527](https://user-images.githubusercontent.com/30767963/45628884-a25c0d00-bac7-11e8-8993-6806714e0de3.png)

**Comment by FibreFoX** [comment]
But maven is not picking it up, did you re-open your command-line prompt? Changes to environment-variables require to reopen that. Please check your PATH and recheck `mvn -v` to verify your changes are getting applied.

**Comment by silverzag** [comment]
Actually I have the same problem. I can't execute  **jfx:jar** goal as showed by the exception display!! I don't know what I had missed!?
[Console_Error.txt](https://github.com/javafx-maven-plugin/javafx-maven-plugin/files/2987632/Console_Error.txt)

**Comment by FibreFoX** [comment]
@silverzag You did not setup JAVA_HOME to point to a JDK but the JRE. Your local dev-setup isn't correct:
`C:\Program Files\Java\jre1.8.0_201/../lib/ant-javafx.jar` it should be something like `C:\Program Files\Java\jdk1.8.0_201/jre/../lib/ant-javafx.jar`

**Comment by silverzag** [comment]
Here is my system configuration 
![VariablesSys](https://user-images.githubusercontent.com/48753944/54681519-e5497c80-4b0c-11e9-9e9f-057e8004e0c4.png)

**Comment by FibreFoX** [comment]
@silverzag JAVA_HOME points to a JRE instead of the JDK.

**Comment by nmggithub** [comment]
I know this is an old issue, but it appears javafx-packager no longer exists.
