### ISSUE TITLE
桌面图标无效-windows 测试

### ISSUE THREAD

**Issue by zhangxianweihebei** [javafx-maven-plugin/javafx-maven-plugin#359]
我在/src/main/deploy  下放置了 系统图标
安装后在Windows 启动菜单里 可以显示我自定义的图标
但是桌面和任务栏上还是显示的默认JAVA图标
<needShortcut>true</needShortcut>  创建的桌面快捷方式
![image](https://user-images.githubusercontent.com/15844529/45705989-a4989700-bbad-11e8-9ad6-2f402733e6af.png)

![image](https://user-images.githubusercontent.com/15844529/45706003-b5490d00-bbad-11e8-80f3-0774574292ea.png)

![image](https://user-images.githubusercontent.com/15844529/45706034-cabe3700-bbad-11e8-8a4c-8f93e2193cee.png)
![image](https://user-images.githubusercontent.com/15844529/45706220-428c6180-bbae-11e8-9dba-160487652352.png)

**Comment by zhangxianweihebei** [comment]
自己手动创建快捷方式  是可以的

**Comment by FibreFoX** [comment]
@zhangxianweihebei could you please ask in english?

**Comment by zhangxianweihebei** [comment]
@FibreFoX 
The shortcut icon created by computer desktop is the default icon. I have set the custom icon.

**Comment by zhangxianweihebei** [comment]
@FibreFoX It is strange that if I manually open the SkynetApp.ico in the installation directory, the desktop will be normal.

**Comment by zhangxianweihebei** [comment]
Is there any problem with my picture?

**Comment by zhangxianweihebei** [comment]
Is it because there is no signature?

**Comment by zhangxianweihebei** [comment]
@FibreFoX It seems to be a computer problem. I have changed two computers.

**Comment by FibreFoX** [comment]
Sometimes it's a caching-problem of windows, when going into the properties of that shortcut, windows shows the up2date icon.

**Comment by zhangxianweihebei** [comment]
yes
