### ISSUE TITLE
When can we support jdk11?

### ISSUE THREAD

**Issue by MaxBill** [javafx-maven-plugin/javafx-maven-plugin#362]
When can we support jdk11?
 
No problem with jdk8. Change to jdk11, prompt when packing :Could not find artifact javafx-packager:javafx-packager:jar:1.8.0_20 at specified path /home/shuai/deve/javabox/jdk11/../lib/ant-javafx.jar -> [Help 1]

**Comment by liunewshine** [comment]
the same problem

**Comment by reebr** [comment]
JDK12 😄

**Comment by lanzisun** [comment]
same request.

**Comment by geisterfurz007** [comment]
JavaFX applications with maven should probably use https://github.com/openjfx/javafx-maven-plugin for their build.

**Comment by Alexilmarranen** [comment]
@geisterfurz007 Only run, not packaging, unfortunately

**Comment by FibreFoX** [comment]
I know the pressure of projects having to be "on latest version of Java", but as the JavaFX-part got heavily reworked on the packaging-part, this will get closed.
