### ISSUE TITLE
Main Class not found

### ISSUE THREAD

**Issue by vincenzopalazzo** [javafx-maven-plugin/javafx-maven-plugin#364]
Hello,

I have a small problem in launching the application (linux), after installing the deb file I try to launch the application from the launcher created by deb but this application does not start, while starting the application in the / opt / folder dirProject / file.jar without any problem 

`[INFO] No workaround for native launcher issue 205 needed. Continuing.
The jar lib/sisu-inject-bean-1.4.2.jar has a main class org.sonatype.guice.bean.containers.Main that does not match the declared main my.package.MainClass`

During the creation of the native goal I have always noticed that I get the following log printouts and then when I go to manually run the application in the / opt / dirproject folder I get the following error 

![selection_012](https://user-images.githubusercontent.com/17150045/50560681-7d507a80-0d03-11e9-9408-86075588b929.jpg)

Also I ask, the application after the generation of the native is launched through the launch (args) method?

**Comment by FibreFoX** [comment]
That `[INFO]` is normal and has nothing to do with this maven-plugin.
That error-message when starting your app can be confusing, but as you wrote that the jar-file itself works, there might be a problem with the bundled JRE, or the configuration inside that INI-file.

Can you create some example-project for that?

**Comment by vincenzopalazzo** [comment]
@FibreFoX , 
'm sorry the problem was caused by me, javafx launches the application using only the lauch () method, I omitted and I did everything very bad, now I have corrected my code and the application starts.

I would like to ask you a question, if I package my application with java 8, does the installe incorporate all the necessary dependencies to start for example on java 11?

Thank you
