### ISSUE TITLE
Set up javafx-maven-plugin in maven but compilation cannot find the package javafx

### ISSUE THREAD

**Issue by meifish** [javafx-maven-plugin/javafx-maven-plugin#368]
This is the set up in pom.xml:

         <plugin>
               <groupId>com.zenjava</groupId>
               <artifactId>javafx-maven-plugin</artifactId>
               <version>8.1.4</version>
               <configuration>
                   <mainClass>Main.Main</mainClass>
               </configuration>
               <executions>
                   <execution>
                        <id>create-jfxjar</id>
                        <phase>package</phase>
                        <goals>
                              <goal>build-jar</goal>
                        </goals>
                   </execution>
               </executions>
            </plugin>

--------------------------------------------------------------------------------------------------------
This is the errors I got:

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /mnt/c/Users/meifi/Documents/Photoshop-Ultra-Light/src/main/java/Layers/ImageLayer.java:[3,25] error: package javafx.scene.image does not exist
[ERROR] /mnt/c/Users/meifi/Documents/Photoshop-Ultra-Light/src/main/java/Layers/ImageLayer.java:[4,25] error: package javafx.scene.image does not exist
[ERROR] /mnt/c/Users/meifi/Documents/Photoshop-Ultra-Light/src/main/java/Layers/ImageLayer.java:[5,26] error: package javafx.scene.layout does not exist
[ERROR] /mnt/c/Users/meifi/Documents/Photoshop-Ultra-Light/src/main/java/Layers/Layer.java:[4,25] error: package javafx.beans.value does not exist
[ERROR] /mnt/c/Users/meifi/Documents/Photoshop-Ultra-Light/src/main/java/Layers/Layer.java:[5,25] error: package javafx.beans.value does not exist

I am relatively new to Maven, so please me know if any information is required to help debugging. Thanks!

**Comment by meifish** [comment]
For more info: I am using `java-1.8.0-openjdk-amd64`

In the same pom.xml configuration. I am also using another plugin `maven-compiler-plugin`:

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <fork>true</fork>
                    <compilerVersion>1.8</compilerVersion>
                    <verbose>true</verbose>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>

Thanks!

**Comment by FibreFoX** [comment]
When using OpenJDK, you need to install OpenJFX too. OracleJDK 8 contains these requried packages.

**Comment by meifish** [comment]
Ah ok, I see. I'll mark this as solved. Thank you!

**Comment by meifish** [comment]
Ah ok, I see. I'll mark this as solved. Thank you!
