### ISSUE TITLE
including JDK in DMG and not JRE

### ISSUE THREAD

**Issue by Meshredded** [javafx-maven-plugin/javafx-maven-plugin#369]
is there a way to include a JDK in the generated native app (dmg) instead of a JRE ?

**Comment by FibreFoX** [comment]
There is no way, probably due to licensing issues of the JDK itself. I already looked into this, but the used JRE is even stripped down inside the underlying packager from the dev-JDK.

But you just could create a ZIP of some JDK you want to provide.
