### ISSUE TITLE
Default inno setup uninstaller does not work without admin rights

### ISSUE THREAD

**Issue by joha78** [javafx-maven-plugin/javafx-maven-plugin#370]
Hi! Thank you so much for this great and helpful plugin!

I have recognized that the generated uninstaller "unins000.exe" does not work as expected when the person that installed the app has no admin rights. Actually the "unins000.exe" does it's job, but only when started manually via the Windows Explorer. When the user is using the Windows App Uninstall view from Windows settings for uninstalling, then the uninstaller asks for an admin password and removes all the files including "unins000.exe" but the entry for the app still remains in the  Windows App Uninstall View in Windows Settings. I think this is because the Uninstaller runs with admin privelliegs and tries to remove the information about the app in the admin's registry, not in the registry of the user who installed the app. 

Does anybody has suggestions how to solve this?

Thank you!

**Comment by FibreFoX** [comment]
This is nothing this plugin can solve, sorry, you might want to open a bug on the OpenJDK project for this. Or maybe this is an issue of the installer-software, but again nothing this plugin can solve. Sorry
