### ISSUE TITLE
how can I skip test in idea

### ISSUE THREAD

**Issue by MintBlue** [javafx-maven-plugin/javafx-maven-plugin#371]
I use idea to build the project by javafx-maven-plugin.when I click jfx:native to build EXE file,how can I skip the tests?

**Comment by xadagaras** [comment]
You can pass - DskipTests to maven or set the option inside the maven panel in idea where the tooltip tells you Toggle skip tests

Regards, 
Daniel

**Comment by MintBlue** [comment]
@xadagaras that works ，thank you
