### ISSUE TITLE
How can I build it  with the JDK environment?

### ISSUE THREAD

**Issue by lhalcyon** [javafx-maven-plugin/javafx-maven-plugin#372]
How can it work on the computer without jdk ?

**Comment by lhalcyon** [comment]
I built the native bundle and got the exe stuff. Then I gave it to a friend , he opened it and got 'lauch jvm failed" .

**Comment by FibreFoX** [comment]
How did you build your bundle? Did you include the bundled JRE? You need to keep the created folder-structure 😉 but I do not know what you did send your friend.

In addition it is important that you both have the same "architecture" (32bit VS 64bit)

**Comment by lhalcyon** [comment]
Well . Here is the situation:
I used `mvn jfx:native` to  get the native bundle  , then I send the whole directory to him .  The result was that it workded well on parts of his computer , the rest were not  with launch error 'can't find the main Class' .  And The computers in his studio almost don't have the JDK environment.

**Comment by lhalcyon** [comment]
Like this , 
![image](https://user-images.githubusercontent.com/21357951/57673533-eb606300-764e-11e9-95bb-d2de26ff0e32.png)

**Comment by FibreFoX** [comment]
There is an issue with non-latin folder names, can you try to check if when being placed in a different folder that your tool works? As said, this is a known issue of the launcher (which comes from the JDK itself).

**Comment by lhalcyon** [comment]
I try and it work !  .  Thanks a lot !!
