### ISSUE TITLE
 Resources folder

### ISSUE THREAD

**Issue by LeoneIgesa** [javafx-maven-plugin/javafx-maven-plugin#373]
Hi everyone, I want to make sure that the resources folder with all the properties and fxml is not included in the jar. That is, I want to make sure that through the exe it is installed externally so as to modify the files more quickly. it can be done? do not include resource in the jar
Help me..........Thanks

**Comment by FibreFoX** [comment]
You have to write your own download-process, this has nothing to do with this bundler, as this is your own kind of "bootstrapping".
