### ISSUE TITLE
How to force the build jar to include the Maven dependencies? 

### ISSUE THREAD

**Issue by WaningMatrix** [javafx-maven-plugin/javafx-maven-plugin#374]

**Comment by FibreFoX** [comment]
@WaningMatrix do you mean some kind of fat-jar?

**Comment by WaningMatrix** [comment]
Basically yeah. I know you have said in the past you won't be doing it but can you make like a experimental feature or something?
It'd be really helpful for me.
Thanks.

**Comment by aekrylov** [comment]
You can add `maven-shade-plugin` to your build, and then set `updateExistingJar` to true in `javafx-maven-plugin`, [see this for example](https://github.com/aekrylov/vic2_economy_analyzer/blob/5987ca091f8503759f37731da0811c644172e99e/pom.xml#L45)
