### ISSUE TITLE
Code protecting

### ISSUE THREAD

**Issue by PawelSzymanski89** [javafx-maven-plugin/javafx-maven-plugin#376]
Hello, how to prevent our native app code. Disable access to class files in jar?

**Comment by FibreFoX** [comment]
It is not clear what you want to do here. The native launcher is only a wrapper around the JVM which requires access to the JAR files.

If you want to obfruscate your JAR files, you might want to check out ProGuard: https://github.com/javafx-maven-plugin/javafx-maven-plugin/tree/master/src/it/08-build-with-proguard

Other protection mechanisms are out of scope of this project.
