### ISSUE TITLE
Pass a script-file to Inno Setup

### ISSUE THREAD

**Issue by aliebelt** [javafx-maven-plugin/javafx-maven-plugin#38]
First of all: Thank you for this great plugin!

For customizing the installation-process of the Installer generated by Inno Setup (e.g. licence, desktop Icon, installation folder) it would be very useful to pass a script-file to Inno Setup.

Looking into the (icon-) paths if there exists a script-file might be a good idea:
Windows: src/main/deploy/package/windows/[project-final-name].iss
Mac: src/main/deploy/package/macosx/[project-final-name].iss

**Comment by FibreFoX** [comment]
This is closed, because we already have this feature.

**Comment by aliebelt** [comment]
Ah, cool! Is there a documentation how to use this feature?

**Comment by FibreFoX** [comment]
There isn't a website yet, but I'm working on it. Meanwhile you can see my comment here: https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/89#issuecomment-97534100

**Comment by aliebelt** [comment]
Great, thanks!
