### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by gir1yaphets** [javafx-maven-plugin/javafx-maven-plugin#381]
Hi,
I think I got correct configuration for the plugin but I cannot run the jar which said `Could not find or load main class application.Main`. Here's some screenshots for my project configuration. My java version is  `1.8.0_251`.

<img width="464" alt="Screen Shot 2020-07-24 at 5 22 03 PM" src="https://user-images.githubusercontent.com/18441124/88444499-3f79e200-cdd2-11ea-842c-74dc51e7d22c.png">
<img width="224" alt="Screen Shot 2020-07-24 at 5 22 21 PM" src="https://user-images.githubusercontent.com/18441124/88444500-41dc3c00-cdd2-11ea-94e0-93085b540400.png">

**Comment by FibreFoX** [comment]
Normally maven-projects have their java-files in `src/majn/java` and not directly under `src`, so you might want to check your normal compiled JAR-file.

**Comment by FibreFoX** [comment]
@gir1yaphets any update?

**Comment by fanties** [comment]
I had the same problem. Unable to start because the run path contains Chinese characters. I hope it can support Chinese character path.

**Comment by FibreFoX** [comment]
This is due to the JDK provided native launchers, nothing I can do sadly. It is a know issue, that executing with non-latin parts in filenames, paths and classes makes a lot of problems.
