### ISSUE TITLE
adding javafx  to a maven project but failed! Help~~

### ISSUE THREAD

**Issue by Michellezqy** [javafx-maven-plugin/javafx-maven-plugin#384]
hi,I have already got a maven program.Now I wanna to add javafx environment into this project.
I did exactly what you teach to do in the Readme file,but did not work,and the error says"Failed to execute goal com.zenjava:javafx-maven-plugin:8.8.3:jar (jar) on project UM2: Execution jar of goal com.zenjava:javafx-maven-plugin:8.8.3:jar failed: Plugin com.zenjava:javafx-maven-plugin:8.8.3 or one of its dependencies could not be resolved: Could not find artifact javafx-packager:javafx-packager:jar:1.8.0_20 at specified path C:\Program Files\Java\jdk-12.0.1/../lib/ant-javafx.jar"

I check the path C:\Program Files\Java\jdk-12.0.1/,it did lack the ant-javafx.jar,but the question is I don't know how to get the file.
I don't know how to add the javafx environment into my maven project.Please help me~
Thank you very much.Looking forward to contacting me.My email is also available:1206814310@qq.com

**Comment by FibreFoX** [comment]
Right now this plugin is not compatible with JDK9 or later (this includes JDK12), as it uses some internal components, which got changed since Jigsaw and got reworked/removed later on.

**Comment by FibreFoX** [comment]
Closed as duplicated of #287
