### ISSUE TITLE
JVM arguments are getting ignored

### ISSUE THREAD

**Issue by marcin-chwedczuk** [javafx-maven-plugin/javafx-maven-plugin#385]
Creating a new issue as requested by: https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/18

I tried all the methods presented by the issue https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/18, including `jvmArgs` and `userJvmArgs`.
What worked for me is this:
```xml
<plugin>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version>0.0.6</version>
    <configuration>
        <mainClass>pl.marcinchwedczuk.rfid.gui.App</mainClass>
        <options>
            <!-- Workaround for BUG: https://stackoverflow.com/a/65062759/1779504 -->
            <option>-Dsun.security.smartcardio.library=/System/Library/Frameworks/PCSC.framework/PCSC</option>
        </options>
    </configuration>
</plugin>
```

You should at least improve documentation and make it explicit that `option` should be used to pass JVM arguments. Please also add a note to the closed issue pointing to the improved docs. That issue was the first thing to pop up while googleing for this problem.

For folks that try to debug the args, you can use this code:
```java
    public static void main(String[] args) {
        printJvmOptions();
        launch();
    }

    private static void printJvmOptions() {
        RuntimeMXBean runtimeMxBean = ManagementFactory.getRuntimeMXBean();
        List<String> arguments = runtimeMxBean.getInputArguments();
        System.out.println("JVM ARGUMENTS:");
        System.out.println(String.join(System.lineSeparator(), arguments));
        System.out.println();
    }
```
It will print JVM arguments, so it will be easy to debug.

**Comment by FibreFoX** [comment]
`<groupId>org.openjfx</groupId>` you are barking at the wrong project ;)

**Comment by marcin-chwedczuk** [comment]
🤦  That explains a lot... I did not realise that there are two plugins in the first place.

**Comment by FibreFoX** [comment]
Yes, sadly my personal time for this vanished, and the openjfx-folks seem to have something similar working in the meantime.
