### ISSUE TITLE
Relationship to openjfx/javafx-maven-plugin?

### ISSUE THREAD

**Issue by jensli** [javafx-maven-plugin/javafx-maven-plugin#386]
What is the relationship between this project and [openjfx/javafx-maven-plugin](https://github.com/openjfx/javafx-maven-plugin)?

What are the technical differences between the two projects? Are there non-technical differences?

That would be useful information for the read-me file!

Thanks for your work on this project, it looks really well-made!

**Comment by FibreFoX** [comment]
There is no relationship, these are two different projects.

This project is for JavaFX using JDK 8 and the other is for the newer OpenJFX with JDK 11. In short after that Jigsaw-impact this project got a bit lost behind, making the Gluon-developers being in need for a short "make it run quick"-maven-plugin.
