### ISSUE TITLE
Document is mssing

### ISSUE THREAD

**Issue by swiftech** [javafx-maven-plugin/javafx-maven-plugin#388]
the link http://javafx-maven-plugin.github.io shows 404 now, I can't find any document to describe how to use this plugin.

**Comment by FibreFoX** [comment]
Same as https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/349

For more examples, please look at the integration-tests: https://github.com/javafx-maven-plugin/javafx-maven-plugin/tree/master/src/it
