### ISSUE TITLE
Plugin doesnt support parallel building

### ISSUE THREAD

**Issue by namoscagnm** [javafx-maven-plugin/javafx-maven-plugin#390]
Hi, my compile times are really slow, and I am trying to speed them up by using many threads with the command:

`mvn -T100 jfx:jar`

However, during build, I get the following message:

```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in BlaBla:
[WARNING] com.zenjava:javafx-maven-plugin:8.9.0-SNAPSHOT
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] *****************************************************************
```

Is it possible for you to adapt the plugin so that parallel execution is possible?

Im currently running maven with following version:
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Java version: 10.0.1, vendor: Oracle Corporation

**Comment by FibreFoX** [comment]
This plugin is not (yet?) compatible with JDK above 8.

Do you know any quick documentation about the parallel mode? @namoscagnm

**Comment by FibreFoX** [comment]
https://maven.apache.org/developers/mojo-api-specification.html

As this plugin is a wrapper around non-thread-safe tools, I highly doubt that this can ever be threadsafe. But you could try to create the jfx-stuff as part of some additional build-step via maven profile?
