### ISSUE TITLE
"class com/cxsj/client/AppStartup not found"when I start the app

### ISSUE THREAD

**Issue by javaCR7** [javafx-maven-plugin/javafx-maven-plugin#396]
<mainClass>com.cxsj.client.AppStartup</mainClass>

**Comment by FibreFoX** [comment]
Hm, I need more details about that issue. Please provide some example project files, your installed java-version, your OS ... and how you are starting your application.

**Comment by javaCR7** [comment]
您好，邮件已收到。感谢您的来信，我将尽快回复。谢谢。

**Comment by FibreFoX** [comment]
;) I assume auto-responder, please english-only, as I'm not familiar with chinese.

**Comment by javaCR7** [comment]
win10-64bit, jdk version is 1.8.301 
<properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <feign.version>10.9</feign.version>
        <java.version>1.8</java.version>
        <jfoenix.version>8.0.10</jfoenix.version>
        <datafx.version>8.0.2</datafx.version>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>8.8.3</version>
                <configuration>
                    <vendor>cxsj</vendor>
                    <mainClass>com.cxsj.client.AppStartup</mainClass>

                    <needMenu>true</needMenu>
                    <needShortcut>true</needShortcut>

                </configuration>
            </plugin>
        </plugins>
    </build>
    
![image](https://user-images.githubusercontent.com/38103065/158285669-f43750cb-9b65-4451-ba55-8e6caa2bbfd0.png)

**Comment by javaCR7** [comment]
win10 64bit ,java version is 1.8.301
![image](https://user-images.githubusercontent.com/38103065/158285898-778ad67e-f6da-4884-84bf-05dec09a894e.png)
![image](https://user-images.githubusercontent.com/38103065/158285927-fc748b2e-e6cf-4a5a-ba3d-867b92a51417.png)

**Comment by FibreFoX** [comment]
Hm, from what I see, there is no problem. Just a wild guess: are you executing the application in a path that contains non-latin chars? Like chinese characters inside the path?

What are you executing, the jfx-jar itself, or via the native launcher?

**Comment by javaCR7** [comment]
Thank you for your letter and I will get back to you as soon as possible。

**Comment by javaCR7** [comment]
I had checked it. The paths are all in English.
I don‘’t understand your mean"jfx-ar" or via the native launcher"
I built the project using Maven.IDE is "Intelli idea".I specify its startup class in the configuration and it works fine.
![image](https://user-images.githubusercontent.com/38103065/158402959-c35550b2-6a5e-410e-8f62-8456e3bc9d1a.png)

**Comment by FibreFoX** [comment]
Oh there it is, IntelliJ does things a bit different, please use the maven plugin of IntelliJ IDEA for the "jfx:run" task.
![grafik](https://user-images.githubusercontent.com/1042579/158419377-cfd57f9e-7c8e-48d5-a8d9-5afe95584804.png)

**Comment by javaCR7** [comment]
I tried it with with ‘mvn jfx:run’
![image](https://user-images.githubusercontent.com/38103065/158510693-73372cba-3bc7-4197-85d3-8dbb4c7d3877.png)

![image](https://user-images.githubusercontent.com/38103065/158510535-87996188-0812-432b-b69c-32ea1e91c82d.png)
It looks like there is no external jar package loaded into the reference

**Comment by FibreFoX** [comment]
Oh I see, SYSTEM-scoped dependencies are not getting pulled into the outcome. You might want to change your project-setup, as with that approach maven is loosing its capabilities to handle transitive dependencies.

I have a GIST for that "in-project repository" stuff: https://gist.github.com/FibreFoX/d9a5b9ad39efef0123f92f5626e9dd77
