### ISSUE TITLE
plugin not work in Win11 

### ISSUE THREAD

**Issue by cxd2013** [javafx-maven-plugin/javafx-maven-plugin#399]
i have used this plugin success to build exe program  in my win10 laptop, but it not worked in my Win11 computer, even no native folder

**Comment by FibreFoX** [comment]
Please post the plugin-configuration-part of your `pom.xml` and what JDK you used.

**Comment by cxd2013** [comment]
thanks for your attention, the problem has been resolved, but there is a new problem, how to make  a windows 32bit not 64bit program use this plugin?

**Comment by FibreFoX** [comment]
This is actually not the part of this plugin and has already answered several times:
#305 `How to package a 32 bit installer on a 64 bit machine?`
#81 `Ability to create a 32-bit native Windows installer in a 64-bit Maven build process JVM (and vice versa)`

In short: the underlying JDK is responsible for this, so you need to use 32bit JDK (which might not be provided for all systems, like MacOS)
