### ISSUE TITLE
jfx:web - Signing Jars

### ISSUE THREAD

**Issue by HellsCargo** [javafx-maven-plugin/javafx-maven-plugin#40]
A couple of issues:
JSE1.7 u25+_ requires new attributes on jar signing meaning that running an JNLP will give errors "Missing Permissions manifest attribute for {jarfile}". See http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/no_redeploy.html

Secondly, field values in the JNLP are missing in the jfx config e.g. \<description\>. Also, I'm not seeing \<organization\> migrate from the main .pom to the JNLP.

Thanks for this great plug in!

**Comment by FibreFoX** [comment]
```<vendor>```-tag is filled with project.organisation.name, but description is missing currently. Still valid with version 8.1.2!

**Comment by FibreFoX** [comment]
same goes for ```<title>```-tag, 'cause it's not implemended.

**Comment by maxd** [comment]
@FibreFoX These parameters should be defined in `MANIFEST.MF` file. Right?

**Comment by FibreFoX** [comment]
generated ```.jnlp```-file contains these information too, don't know about manifest.
