### ISSUE TITLE
runing mvn jfx: native error

### ISSUE THREAD

**Issue by Lingakg** [javafx-maven-plugin/javafx-maven-plugin#400]
Could not find artifact javafx-packager:javafx-packager:jar:1.8.0_20 at specified path /Users/chennwanlin/Library/Java/JavaVirtualMachines/openjdk-18.0.1.1/Contents/Home/../lib/ant-javafx.jar

env：
jdk： 18
Sys：Mac

**Comment by FibreFoX** [comment]
This mavne-plugin right now is not compatible with JDKs above JDK 8.

**Comment by FibreFoX** [comment]
Closed as duplicate to #287
