### ISSUE TITLE
Ability to customize MSI installer

### ISSUE THREAD

**Issue by cowwoc** [javafx-maven-plugin/javafx-maven-plugin#42]
We should be able to customize the MSI installer as mentioned in the JavaFX documentation. See http://stackoverflow.com/q/18667061/14731 for more information.

**Comment by FibreFoX** [comment]
This feature is already possible, please take a look into this comment: https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/89#issuecomment-97534100

I'm going to prepare a current/fresh documentation for this plugin next week, in hope to avoid this type of questions ;)
