### ISSUE TITLE
FileNotFoundException: ...\target\jfx\web\lib

### ISSUE THREAD

**Issue by BorzdeG** [javafx-maven-plugin/javafx-maven-plugin#46]
If your project has no dependencies, the following error occurs for "jfx:web":

...
Signing (BLOB) ${project.build.directory}\jfx\web\lib
java.io.FileNotFoundException: ${project.build.directory}\jfx\web\lib (Can not find the file specified)
...

**Comment by FibreFoX** [comment]
This bug isn't fully fixed, because the signing-branch does not contain the fix ;) I am working on this, will be included with another PR.

**Comment by FibreFoX** [comment]
should be fixed with PR #103 and #106 
feel free to re-open when not working
