### ISSUE TITLE
Implementation Entries

### ISSUE THREAD

**Issue by codedragon76** [javafx-maven-plugin/javafx-maven-plugin#48]
I need to pass forward the maven version number into the running application. The maven-jar-plugin allows me to insert these records into the jar using addDefaultImplementationEntries. However these entries don't make it into the javafx manifest file. I assume you are possibly generating the manifest file from scratch? Is there a way to get these parameters through?

**Comment by FibreFoX** [comment]
Manifest will be created by bundler itself, not by our plugin, but we were missing to pass custom manifest entries to that bundler. My proposed PR #115 is trying to correct this. This will get merged, if @maxd has reviewed these changes.
