### ISSUE TITLE
Change classpath of dependencies

### ISSUE THREAD

**Issue by brevleq** [javafx-maven-plugin/javafx-maven-plugin#49]
I believe a plugin configuration option that permits the change of the dependencies in MANIFEST.MF file, like in maven-jar-plugin, could add more flexibility to the generated jar file. Something like this:

    <plugin>
        <groupId>com.zenjava</groupId>
        <artifactId>javafx-maven-plugin</artifactId>
        <version>2.0</version>
        <configuration>
                 <mainClass>com.hrgi.pdv.App</mainClass>
                 <jfxClasspathPrefix>../lib/</jfxClasspathPrefix>
        </configuration>
    </plugin>

**Comment by FibreFoX** [comment]
Because there is a working solution using another maven-plugin, no additions are needed.
