### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by Philipp91** [javafx-maven-plugin/javafx-maven-plugin#55]
A feature to add a license file would be great. This could be either by default a file named "license.txt", or a configurable name or maybe even a configuration section to allow specifying arbitrary resource file.

I think that the license fill can be added like this:
https://github.com/zonski/javafx-maven-plugin/blob/master/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java
somewhere add:
```
deployParams.addResource(jfxAppOutputDir (?), licenseFilePath, DeployResource.Type.license);
```

Alternatively, you could allow any resource file to be added via the pom, e.g. like this:
```
<resources>
   <resource>
      <file>${project.basedir}/src/main/deploy/license.txt</file>
      <type>license</type>
   </resource>
</resource>
```

**Comment by ssaring** [comment]
I would also vote for the solution from @tsbatista . Currently it's impossible to add license files, the installer always fails.

**Comment by FibreFoX** [comment]
May be fixed with PR https://github.com/javafx-maven-plugin/javafx-maven-plugin/pull/84

**Comment by FibreFoX** [comment]
Just leaving this here for reference: http://stackoverflow.com/a/36932827/1961102

```xml
<plugin>
    <groupId>com.zenjava</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version>8.4.0</version>
    <configuration>
        <mainClass>your.path.to.the.mainclass</mainClass>
        <verbose>true</verbose>
        <bundleArguments>
            <licenseFile>someFileThatIsTheLicense.rtf</licenseFile>
        </bundleArguments>
        <additionalAppResources>src/main/additionalAppResources</additionalAppResources><!-- name does not matter, it's just some folder :D -->
    </configuration>
</plugin>
```
