### ISSUE TITLE
"Main application jar is missing", if you rename main jar with <jfxMainAppJarName>

### ISSUE THREAD

**Issue by pjBooms** [javafx-maven-plugin/javafx-maven-plugin#59]
I have tried to customize main jar name with <jfxMainAppJarName> but now, native packaging stage is skipping due to the following:

  Skip [Windows Application Bundler] due to [Main application jar is missing.]
   [Make sure to use fx:jar task to create main application jar.]

However it works if you specify the name with the ".jar" extension

**Comment by javasparx** [comment]
you right man, thank you.

**Comment by FibreFoX** [comment]
I can't reproduce this anymore, maybe its already fixed with other changes. Please retry with current master and re-open this issue if needed.
