### ISSUE TITLE
Update jvmArgs documentation

### ISSUE THREAD

**Issue by FilterPunk** [javafx-maven-plugin/javafx-maven-plugin#60]
Is this the correct way to pass jvmArgs?
Can you please update the jvmArgs Documentation.
![jvmargs](https://cloud.githubusercontent.com/assets/4501171/3091331/9fbad884-e59b-11e3-8d64-e0c34c553a79.jpg)
The tag "jvmArg" should at least be mentioned.

**Comment by FibreFoX** [comment]
Will be documented with new website within next two weeks (I'm currently working on this).
