### ISSUE TITLE
Missing Application-Name manifest attribute

### ISSUE THREAD

**Issue by maqjav** [javafx-maven-plugin/javafx-maven-plugin#61]
Hello.

I've followed the tutorial at http://zenjava.com/javafx/maven/web-bundle.html# in order to create a webstarter of my app, and when I try to run it with the generated HTML I get this error: Missing Application-Name manifest attribute

I checked the manifest file in my JAR and it doesnt have the application-name defined. How can I add it with maven?

Thanks!

**Comment by FibreFoX** [comment]
```
deployParams.setAppName(build.getFinalName());
```

It works for me.
