### ISSUE TITLE
Issue with Windows binary

### ISSUE THREAD

**Issue by johnzeringue** [javafx-maven-plugin/javafx-maven-plugin#62]
I'm trying to use your plugin to generate native binaries for a project of mine (using Java 8) and it's working perfectly on Mac but not on Windows. When I run the Windows binary, it'll open the main page, but clicking a button that opens a new window doesn't work.

My guess is that it's choking on the external library that the button calls, because that's the first time the program uses any external software. I've confirmed that the JAR for that library is in the appropriate lib folder.

Do you have any recommendations? Is this a known issue?

The project I'm referring to is at https://github.com/cirdles/topsoil and the pom version that uses your plugin is currently HEAD on `dev`.

**Comment by FibreFoX** [comment]
Hi @johnzeringue , have you tried the latest version of javafx-maven-plugin?

Make sure your repository points to ```https://oss.sonatype.org/content/repositories/releases/```, not only to snapshots.
Current version is 8.1.2

**Comment by johnzeringue** [comment]
I'm no longer using a Maven build script (I've switched to Gradle), so I can't use this anymore. Perhaps this issue should be closed.
