### ISSUE TITLE
How to add obfuscation task in native building

### ISSUE THREAD

**Issue by rsc1975** [javafx-maven-plugin/javafx-maven-plugin#65]
Hi, I have a JavaFX application that I package with `javafx-maven-plugin`, but now I'm trying to obfuscate the code.

To achieve this I use an ant task using ProGuard, but my problem is that I couldn't find a way to call this obfuscation task between the `jfx:jar` and the `jfx:native` goals, both of them are called on `package` phase and the `jfx:native` calls **always** to `jfx:jar`, so I cannot use `mvn jfx:jar antrun:run jfx:native`.

My current workaround is to call `jfx:jar` and with ant I make the obfuscation and the native building, but I don't like too much this approach.

Is there any way to execute "something" between `jar` and `native` goals ?

Can be possible to avoid to launch the `jfx:jar` from `jfx:native` if jar file exists ? We always can launch a "clean jfx:native" if we want a clean building.

**Comment by FibreFoX** [comment]
Hi @rsc1975, when merged, this can be done easily by adding javafx-maven-plugin to the maven-lifecycle. For more information, please have a look into description of pull-request #108
