### ISSUE TITLE
mvn jfx:generate-key-store failure

### ISSUE THREAD

**Issue by takiri** [javafx-maven-plugin/javafx-maven-plugin#66]
Hello, 
first of all thank you for this great plugin!
I'm trying to generate a keystore with mvn jfx:generate-key-store but it fails. Can't figure out if I'm missing something in the POM or if this is a "relevant" bug...

Thanks a lot!

Here is the command line (in my project base directory): 
> mvn jfx:generate-key-store -DcertDomain=my.domain -DcertCountry=myCountry -DcertOrg=myOrg -DcertState=myState

(By the way, would it be possible to choose the validity period please?)

Here is the relevant part of my POM:
      <plugin>
        <groupId>com.zenjava</groupId>
        <artifactId>javafx-maven-plugin</artifactId>
        <version>2.0</version>
        <executions>
          <execution>
            <id>create-final-jar</id>
            <phase>package</phase>
            <goals>
              <goal>web</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <vendor>myOrg</vendor>
          <mainClass>path.to.my.MainClass</mainClass>
          
          <permissions>
            <permission>all-permissions</permission> 
          </permissions>
          
        </configuration>
      </plugin>

And here is (a piece of) the error message a got:

Failed to execute goal com.zenjava:javafx-maven-plugin:2.0:generate-key-store 
(default-cli) on project myProject: Unable to execute mojo: Execution null of goal org.codehaus.mojo:keytool-mav
en-plugin:1.2:generateKeyPair failed: Unable to load the mojo 'generateKeyPair' (or one of its required components) from the plugin 'org.codehaus.mojo:keytool-maven-plugin:1.2': com.google.inject.Prov
isionException: Guice provision errors:
1) No implementation for org.codehaus.mojo.keytool.KeyToolCommandLineBuilder was bound.
while locating org.codehaus.mojo.keytool.DefaultKeyTool
at ClassRealm[plugin>org.codehaus.mojo:keytool-maven-plugin:1.2, parent: sun.misc.Launcher$AppClassLoader@5c647e05]

**Comment by FibreFoX** [comment]
Could you try with current master-branch? I've updated internal usage of keytool-maven-plugin, so this should work again.

**Comment by FibreFoX** [comment]
Generating keystore with current master-branch and JDK 8u25 now works for me, should be fixed with PR #112.
If no feedback provided until the next days, this issue will be closed as fixed.

**Comment by FibreFoX** [comment]
This is fixed by upgrading used keytool-maven-plugin and other changes. Works for test-project within PR #116
