### ISSUE TITLE
Tests are failing via Maven pom.xml

### ISSUE THREAD

**Issue by skiwi2** [javafx-maven-plugin/javafx-maven-plugin#67]
Referencing an issue from TestFX/TestFX#131, such that you are aware.

I've got a pom.xml file there and building the JavaFX application fails, because the tests fail for some reason.

It works fine with Netbeans' native Ant JavaFX packager.

**Comment by FibreFoX** [comment]
Will be documented with new website within next two weeks (I'm currently working on this).

**Comment by FibreFoX** [comment]
I will close this, because I'm preparing the documentation. All existing issues will be reviewed for FAQ/known-issues.
