### ISSUE TITLE
Version 8.1.2 requires JDK8u20 or it fails

### ISSUE THREAD

**Issue by aalmiray** [javafx-maven-plugin/javafx-maven-plugin#73]
This is the same issue as gradle-javafx-plugin 40 (https://bitbucket.org/shemnon/javafx-gradle/issue/40/).
The following exception appears when attempting to package the application under JDK8u11

    -----------------------------------------------------
    realm =    plugin>com.zenjava:javafx-maven-plugin:8.1.2
    strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
    urls[0] = file:/Users/aalmiray/.m2/repository/com/zenjava/javafx-maven-plugin/8.1.2/javafx-maven-plugin-8.1.2.jar
    urls[1] = file:/Users/aalmiray/.m2/repository/org/twdata/maven/mojo-executor/2.2.0/mojo-executor-2.2.0.jar
    urls[2] = file:/Users/aalmiray/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
    urls[3] = file:/Users/aalmiray/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
    urls[4] = file:/Users/aalmiray/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
    urls[5] = file:/Users/aalmiray/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
    urls[6] = file:/Users/aalmiray/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
    urls[7] = file:/Users/aalmiray/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
    urls[8] = file:/Users/aalmiray/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
    urls[9] = file:/Users/aalmiray/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.1/plexus-utils-1.5.1.jar
    urls[10] = file:/Users/aalmiray/.m2/repository/org/codehaus/plexus/plexus-archiver/2.1.1/plexus-archiver-2.1.1.jar
    urls[11] = file:/Users/aalmiray/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
    urls[12] = file:/Users/aalmiray/.m2/repository/org/codehaus/plexus/plexus-io/2.0.3/plexus-io-2.0.3.jar
    urls[13] = file:/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre/../lib/ant-javafx.jar
    Number of foreign imports: 1
    import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

    -----------------------------------------------------

        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:125)
        ... 20 more
    Caused by: java.lang.NoClassDefFoundError: com/oracle/tools/packager/Log$Logger
        at com.zenjava.javafx.maven.plugin.AbstractJfxToolsMojo.getPackagerLib(AbstractJfxToolsMojo.java:108)
        at com.zenjava.javafx.maven.plugin.JarMojo.execute(JarMojo.java:122)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        ... 20 more
    Caused by: java.lang.ClassNotFoundException: com.oracle.tools.packager.Log$Logger
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
        ... 23 more
    [ERROR] 
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by FibreFoX** [comment]
Will be documented with new website within next two weeks (I'm currently working on this).
