### ISSUE TITLE
windows binary need msvcp100.dll, contains msvcr100.dll

### ISSUE THREAD

**Issue by sothawo** [javafx-maven-plugin/javafx-maven-plugin#74]
Hi, I'm using your plugin to build native apps, it works on the Mac, but on Windows I have a problem. I am using the following versions:
JDK 1.8.0_20
javafx-maven-plugin 8.1.2
Windows 8.1 64bit
Inno Setup 5.5.5
WIX 3.8

mvn clean jfx:native creates both the exe and the msi, but on installing the exe or when trying to run the installed mdi, I get a message that the program cannot be started because MSVCP100.DLL is missing. This seems to be true, as the jdk and the installed programs contain MSVCR100.DLL.

Has anybody some idea why the exe wants the c++ lib instead of the normal runtime? Or how to fix this?
greetings
Peter

**Comment by FibreFoX** [comment]
Closed, because it was a javafx-/ packager-bug.

**Comment by maxd** [comment]
FYI: It was fixed in JDK 8u40.
