### ISSUE TITLE
Specify Installation directory for native installation

### ISSUE THREAD

**Issue by RobzInadE** [javafx-maven-plugin/javafx-maven-plugin#75]
Hey!

I've been using this JavaFX plugin for a while now. It's great.

I have a question tho;
Is there any way I can allow the user to select where to install the native Windows program that you can build with jfx:native? Right now it puts it under the users home directory/AppData/Local/app

Also, is there any way to specify where files created by java (classpath) is stored after installation?

Regards

**Comment by FibreFoX** [comment]
Hi @RobzInadE, just for better development-handling: please create multiple issue-reports for each bug you encounter.

After some investigation, I documented this feature in this issue: https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/89
