### ISSUE TITLE
The javafx-maven-plugin has upgraded to 8.1.2, please upgrade javafx-basic-archetype

### ISSUE THREAD

**Issue by hawkxu** [javafx-maven-plugin/javafx-maven-plugin#77]
The javafx-maven-plugin has upgraded to 8.1.2, but the javafx-basic-archetype was 2.1.0 with javafx-maven-plugin 2.0 yet, please upgrade it, thanks!

**Comment by FibreFoX** [comment]
This will get updated as soon as these projects are transfered. Stay tuned ;)

**Comment by FibreFoX** [comment]
done, but not yet published to maven central.
