### ISSUE TITLE
Specify JRE Path for native bundling

### ISSUE THREAD

**Issue by aliebelt** [javafx-maven-plugin/javafx-maven-plugin#79]
Hi,

we want to create two different native installers: for Windows 32 Bit and 64 Bit.
We use JDK 8u25 with Inno Setup for EXE creation.

Our JAVA_HOME contains "C:\jdk\jdk_8u25_64bit". The Installer is created correctly with this JDK for 64 bit Windows. But currently we see no possibility to switch to "C:\jdk\jdk_8u25_32bit" during the maven build process to create a second installer for 32 bit Windows.

EDIT: Removed solution suggestion.

**Comment by FibreFoX** [comment]
Seems to be a dublicate, please have a look at the other issue: https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/81#issuecomment-98520400

**Comment by aliebelt** [comment]
In my opinion this is no duplicate of #81 because here is the topic simply the style of config. But apart from that: I think a documentation of how to configure a custom JRE is needed. It was quite hard to find out how to realize it. (See three comments above for the solution)

**Comment by FibreFoX** [comment]
I agree, this does need more documentation. I'll try to fix that in some days.
