### ISSUE TITLE
how to copy external resources to native/{project_name}/app directory

### ISSUE THREAD

**Issue by liudonghua123** [javafx-maven-plugin/javafx-maven-plugin#83]
Hello,
This plugin is great, but one problem I encountered is I couldn't copy the external resources directory under my project root folder to "target/jfx/native/{project_name}/app" when I run "mvn clean jfx:native", I have tried copy-resources plugin, but it's not work.
Below is some pieces of my pom.xml configuration.

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<jdk.version>1.8</jdk.version>
		<junit.version>4.12 </junit.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<finalName>${artifactId}</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.1</version>
				<configuration>
					<source>${jdk.version}</source>
					<target>${jdk.version}</target>
					<showWarnings>true</showWarnings>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.zenjava</groupId>
				<artifactId>javafx-maven-plugin</artifactId>
				<version>8.1.2</version>
				<configuration>
					<mainClass>com.liudonghua.apps.signapk_fx.MainApp</mainClass>
					<verbose>true</verbose>
				</configuration>
			</plugin>

			<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<version>2.7</version>
				<executions>
					<execution>
						<id>copy-resources-1</id>
						<phase>validate</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${basedir}/target/resources</outputDirectory>
							<resources>
								<resource>
									<directory>resources</directory>
									<filtering>false</filtering>
								</resource>
							</resources>
						</configuration>
					</execution>
					<execution>
						<id>copy-resources-2</id>
						<phase>validate</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${basedir}/target/jfx/native/signapk_fx/app/resources</outputDirectory>
							<resources>
								<resource>
									<directory>resources</directory>
									<filtering>false</filtering>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>

Hope someone can help me with this problem.
Thanks！

**Comment by FibreFoX** [comment]
My pull-request is NOT fixing this issue, im sorry to create any confusions.

What are you trying to put into the generated folders? Normally all resources should be transfered into the jar itself.

**Comment by maxd** [comment]
Seems ok. My LICENSE files was copied to `jfx/app` directory.
