### ISSUE TITLE
How add Permissions: all-permissions to manifest

### ISSUE THREAD

**Issue by metlaivan** [javafx-maven-plugin/javafx-maven-plugin#86]
How add Permissions: all-permissions to manifest. My pom:
```xml
<plugins>
            <plugin>
                <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>8.1.2</version>
                <configuration>
                    <mainClass>com.flamesgroup.MainApp</mainClass>
                    <allPermissions>true</allPermissions>
                    <keyStoreAlias>q</keyStoreAlias>
                    <keyStorePassword>q</keyStorePassword>
                </configuration>
            </plugin>
</plugins>
```
after I execute "mvn jfx:web"
in generated jar i did not found "Permissions: all-permissions"

**Comment by FibreFoX** [comment]
As far as i can see, it should work as you wrote:
https://github.com/zonski/javafx-maven-plugin/blob/master/src/main/java/com/zenjava/javafx/maven/plugin/WebMojo.java#L191

But it seems you are missing the keyStore with your configuration.

**Comment by metlaivan** [comment]
I added keyStore but did not found "Permissions: all-permissions" in my jar manifest.

**Comment by maxd** [comment]
Seems like this property [isn't using](https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/java/com/sun/javafx/tools/packager/DeployParams.java#L219) anymore.

Try to modify manifest file use `maven-jar-plugin` [plugin](http://maven.apache.org/shared/maven-archiver/examples/manifestEntries.html). Let us know if it will works.

**Comment by TapaniRundgren** [comment]
Added following into JarMojo execute() method to get it working
...
        Map<String, String> manifestAttributes = new HashMap();
        manifestAttributes.put("Permissions", "all-permissions");
        createJarParams.setManifestAttrs(manifestAttributes);    
...

**Comment by FibreFoX** [comment]
Confirmed, I hope to have this fixed with upcoming pull-request.
