### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by kishaningithub** [javafx-maven-plugin/javafx-maven-plugin#90]
In maven central http://search.maven.org/#search|ga|1|com.zenjava
the version is 8.1.2 whereas in git hub repo and your site
http://zenjava.com/javafx/maven/basic-config.html the version is
2.0.

Kindly update all your docs and may be include a section for java 8
if its ok.

**Comment by FibreFoX** [comment]
Documentation is very outdated, but I don't know if @shemnon (the new "maintainer" of this plugin, as stated [here](http://speling.shemnon.com//blog/2014/09/12/maven-javafx-plugin-8-dot-1-released/)  ) has access to that page. There are some pull-requests too which aren't commented or anything.

(yes, it feels a bit abandoned right now)

**Comment by FibreFoX** [comment]
I'm closing this, because we are updating the plugin and are preparing for a new website.
