### ISSUE TITLE
Unable to load jar manifest (dependencies need JavaFX but target project doesn't)

### ISSUE THREAD

**Issue by reccej** [javafx-maven-plugin/javafx-maven-plugin#95]
Hey,

I had a dumb question a day or two ago but it's leading me to this problem: I keep getting "unable to load jar manifest" errors when attempting to run the jar executable.

The project I am deploying (Project A) does not use any JavaFX methods in itself, but it references a local Maven dependency that does (Project B). I've tried having project B as a dependency, building project B as a javafx-maven jar then using that as a dependency (with the mainclass in that build being set to both the JavaFX main class and the Project A main class), but no combination seems to work. I've also tried building Project A normally with the mvn-javafx jar of Project B as a dependency but none of that works either. Is there something special about the build order when building a standalone executable that references a javafx-executable as a dependency? What main class should be invoked?

Thanks!

**Comment by FibreFoX** [comment]
Could you provide an example-project? I'm not quite sure about your setup ;) code would be better than words in situations like this.

**Comment by FibreFoX** [comment]
Closed due to no feedback provided.

Depending on project which itself is installed as JAR, does not provide any javafx-powers. The created jfx-jar is a special one, not the normal maven-result.
